neondatabase/website

src/components/shared/footer/footer.jsx, src/components/shared/header/header.jsx, src/components/shared/mobile-menu/mobile-menu.jsx, src/constants/menus.js
This PR brings a `constants/menus.js` file to keep all the links for the header, footer and mobile menus.
=> refactor: add constants file with menu links

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/components/shared/content/content.css, src/constants/seo-data.js, src/posts/2012-11-09-cilium126/index.md, src/posts/2018-08-21-cilium12/index.md, src/posts/2018-09-21-cilium123/index.md, src/posts/2019-02-12-cilium124/index.md, src/posts/2020-05-19-cilium127/index.md, src/posts/2021-11-21-cilium128/index.md, src/posts/2022-01-21-cilium125/index.md, src/static-pages/privacy-policy.md, src/styles/fonts.css, src/styles/global.css, src/styles/safe-paddings.css, src/templates/static.jsx
**Describe changes**
This PR brings various tasks [from this Notion page](https://www.notion.so/pixelpoint/Blog-leftovers-bb1c6b6dc19e439f9c62243188c8eb5e#3504b1e5232b4644bf08b2218e117723)
**Steps to test**
1. Go to [_/privacy-policy_](https://clever-wescoff-fd0120.netlify.app/privacy-policy) page as an example of a static page in this project
2. Confirm everything works and looks as expected
NB! Please review the code locally, as deploy preview is unavailable for now. 
**TODO**
=> feat & refactor: misc blog leftover tasks

content/docs/cloud/about.md, src/components/pages/home/hero/hero.jsx
A few change up suggestions for the "about" page and a recent typo on the hero section.
=> minor changes to wording (+ hero typo)

gatsby/createBlogPages.js, src/components/shared/layout/layout.jsx, src/components/shared/seo/seo.jsx, src/constants/seo-data.js, src/pages/early-access.jsx, src/pages/index.jsx, src/pages/jobs.jsx, src/pages/team.jsx, src/templates/blog-post.jsx, src/templates/blog.jsx, src/templates/doc.jsx, src/templates/static.jsx
This PR fixes `og:url` and `canonical` url
=> fix: fix og: and canonical urls

content/docs/cloud/integrations.md, content/docs/cloud/tutorials.md, content/docs/quickstart/django.md, content/docs/quickstart/go.md, content/docs/quickstart/java.md, content/docs/quickstart/prisma.md, content/docs/quickstart/sqlalchemy.md, content/docs/quickstart/symphony.md
Thanks to @volfco for the report!
=> fix: docs for the new proxy url format, without @neon in username

src/components/pages/early-access/hero/hero.jsx
=> fix: add custom event on success submit early access form

content/docs/conceptual-guides/compute-lifecycle.md, content/docs/get-started-with-neon/signing-up.md, content/docs/integrations/django.md, content/docs/reference/compatibility.md, content/docs/reference/roadmap.md, content/docs/sidebar.yaml
This debugs the sidebar errors
=> docs: sidebar link updates

content/docs/release-notes.md
bring back changes that I've accidentally overwritten with my commit
=> release notes cleanup

content/docs/release-notes.md
This PR adds the Release Notes for the [2022-07-20 release of the Console](https://github.com/neondatabase/cloud/pull/1858/commits)
=> Release notes for 2022-07-20

src/components/pages/team/team/team.jsx
Updating the title as listed in employment contract
=> Use correct title

src/components/shared/header/header.jsx, src/components/shared/layout/layout.jsx, src/components/shared/mobile-menu/mobile-menu.jsx
This pull request moves the topbar to Layout component to fix indent issues of the first sections on pages.
=> fix: move topbar to layout component

src/components/pages/blog/posts-list/posts-list.jsx, src/components/pages/home/community/community.jsx
This pull request brings the updates:
- checked if ACF field is available to prevent preview fail in WP
- fixed image path in Community on Home page
=> fix: check if ACF is available

src/components/pages/blog-post/hero/hero.jsx, src/components/pages/blog/posts-list/posts-list.jsx
This pull request checks if author ACF is available to prevent WP build failure.
=> fix: add check condition for author acf

gatsby-config.js, src/components/pages/home/advantages/advantages.jsx, src/components/pages/home/advantages/icon/icon.jsx, src/components/pages/home/advantages/icon/index.js, src/components/shared/footer/footer.jsx, src/components/shared/header/burger/burger.jsx, src/components/shared/header/header.jsx
This pull request brings performance improvements to the website. 
- added aria-label for non-text button
- lazy loaded icons in Advantages component
- added explicit size for logos in Header & Footer
- cached lotties assets and fonts
=> chore: perfomance improvements

content/README.md
This is a short guide for the sidebar, it should cover future questions about where new pages should go. If anything needs more detail or clarity, or you have questions that have not been addressed by this feel free to let me know and I'll expand on it further.
=> docs: Adds a guide to the sidebar 

content/docs/README.md
Add documentation about how to use the enableTableOfContents field.
=> docs: add `enableTableOfContents` field to readme

content/changelog/2022-06-08-console-release/index.md, content/changelog/2022-07-11-storage-release/index.md, content/changelog/2022-07-19-storage-release/index.md, content/changelog/2022-07-20-console-release/index.md, content/changelog/2022-08-02-storage-release/index.md, content/changelog/2022-08-04-console-release/index.md, content/changelog/2022-08-08-console-release/index.md, content/changelog/2022-08-15-console-release/index.md, content/changelog/2022-08-25-console-release/index.md, content/changelog/2022-08-30-console-release/index.md, content/changelog/2022-08-31-console-release/index.md, content/changelog/2022-09-01-storage-release/index.md, content/changelog/2022-09-02-console-release/index.md
Minor edits to release notes to improve readability.
=> Release notes edits

content/docs/reference/roadmap.md, content/docs/reference/technical-preview-free-tier.md
Mostly a general edit. Note that I have changed "summer of 2022" to "in the coming months". Links from one topic to another were added to address cloud issue #1722.
=> Revise the Neon roadmap and Technical Preview topics

content/changelog/2022-08-15-console-release/index.md, content/changelog/2022-08-25-console-release/index.md, content/changelog/2022-08-30-console-release/index.md
Reorder What's New and Bug Fixes sections in release notes so that What's new items come first.
=> Reorder What's new and Bug fixes sections in release notes

content/docs/conceptual-guides/architecture-overview.md, content/docs/get-started-with-neon/using-api-keys.md, content/docs/integrations/django.md, content/docs/integrations/hasura.md, content/docs/integrations/java.md, content/docs/integrations/node.md, content/docs/integrations/prisma.md, content/docs/integrations/sqlalchemy.md, content/docs/integrations/symfony.md, content/docs/integrations/vercel.md, content/docs/reference/compatibility.md, content/docs/reference/glossary.md, content/docs/reference/technical-preview-free-tier.md, content/docs/security.md
- Add right-hand TOC for topics with multiple sections
- Remove inconsistent use of "Step 1 -, Step 2 -, etc. from integration topics. We'll revisit all of these topics in the future for more substantive revisions
- Add some basic content for empty sections in Symfony section.
=> Enable right-hand toc and other edits

src/components/pages/early-access/hero/hero.jsx, src/hooks/use-local-storage.js
This pull request prevents email duplication for the form Get early access with localStorage.
=> fix: prevent email duplication with localStorage

content/docs/cloud/about.md, content/docs/how-to-guides/connectivity-issues.md, content/docs/how-to-guides/import-an-existing-database.md, content/docs/sidebar.yaml
For consideration:
- An initial reorganization of the TOC (a first step with the existing content)
- Shorten some top-level names
- Adjust a few topic titles
- Files have not been moved within the file structure to avoid broken links. We'll do that next if we like these changes
=> An initial TOC reorg and title changes

content/docs/cloud/about.md, content/docs/conceptual-guides/architecture-overview.md, content/docs/conceptual-guides/compute-lifecycle.md, content/docs/get-started-with-neon/connection-pooling.md, content/docs/get-started-with-neon/setting-up-a-project.md, content/docs/get-started-with-neon/signing-up.md, content/docs/reference/compatibility.md, content/docs/reference/roadmap.md, content/docs/reference/technical-preview-free-tier.md
- Fix broken links
- One title change
=> Fix broken links

content/docs/cloud/about.md, content/docs/conceptual-guides/architecture-overview.md, content/docs/conceptual-guides/branching.md, content/docs/conceptual-guides/compute-lifecycle.md, content/docs/get-started-with-neon/connection-pooling.md, content/docs/get-started-with-neon/query-with-psql-editor.md, content/docs/security.md
=> Minor edits and revisions.

src/components/pages/blog-post/social-share-bar/images/check.inline.svg, src/components/pages/blog-post/social-share-bar/images/link.inline.svg, src/components/pages/blog-post/social-share-bar/index.js, src/components/pages/blog-post/social-share-bar/social-share-bar.jsx, src/components/pages/blog-post/social-share/social-share.jsx, src/components/pages/doc/previous-and-next-links/previous-and-next-links.jsx, src/components/shared/search/input/input.jsx, src/components/shared/search/results/results.jsx, src/templates/blog-post.jsx
This pull request updates the design of docs navigation and adds social share bar on mobile
**Screenshot**
=> fix: update docs navigation & add social share bar on mobile 

src/components/shared/layout/layout.jsx, src/components/shared/seo/seo.jsx
This pull request removes the redundant SEO component in Layout.
=> fix: remove SEO component in Layout

content/docs/how-to-guides/hasura-heroku-migration.md, content/docs/sidebar.yaml
Migrate from Heroku
https://websitemain62807-dpriceherokumigration.gtsb.io/docs/how-to-guides/hasura-heroku-migration/
=> Add heroku migration draft

content/docs/integrations/vercel.md, content/docs/sidebar.yaml
- Current Next.js (Vercel) topic revisions, We'll revisit this content for the Vercel integration.
- Move under Develop heading in TOC
https://websitemain62807-dpriceverceltopicrevisions.gtsb.io/docs/integrations/vercel/
=> Next.js (Vercel) topic revisions.

content/docs/reference/compatibility.md
Update extension documentation to include h3_pg.
=> Update extension documentation to include h3_pg.

content/release-notes/2022-10-07.md
Deploy preview:
https://websitemain62807-relnotes1710222.gtsb.io/docs/release-notes/
=> feat: 2022-10-07 storage release notes

content/release-notes/2022-10-21.md, content/release-notes/2022-10-25.md
Also contains missing release notes for 2022-10-21.
https://websitemain62807-releasenotes2510.gtsb.io/docs/release-notes/
=> Storage release notes 2022-10-25.md

src/components/shared/topbar/topbar.jsx
Replacing the top bar message by: Neon supports PostgreSQL 15.
=> feat(constants): update topbar message

src/components/shared/topbar/topbar.jsx
=> feat(constants): update banner with tada emoji

content/docs/how-to-guides/using-branches.md
- Adds updated links to the branching concept guide
- Rewrites content into more article format
- Adds additional context about branching
=> Completing the using branches how to guide

src/utils/send-gtag-event.js
**Describe the changes**
This PR fixes typo in `send-gtag` function to avoid tracking discrepancies
=> fix: gtag function

content/docs/reference/glossary.md
Add definition for region.
We might be more specific about what resources are stored in a region. Compute and storage?
https://websitemain62807-dpriceregionglossarydefinition.gtsb.io/docs/reference/glossary/#region
=> Update glossary.md - Region definition

content/release-notes/2022-11-04.md
2022-11-04 Console release notes:
https://websitemain62807-antonycpatch127702.gtsb.io/docs/release-notes/2022-11-04/
=> 2022-11-04 console release

content/docs/guides/hasura.md
This pull request update the video codec from `h264` to `h265`, as on some Android devices h264 codec is not supported https://bugs.chromium.org/p/chromium/issues/detail?id=719023
Issue: https://github.com/neondatabase/website/issues/291
=> fix: video issue on hasura page

src/components/pages/blog-post/hero/hero.jsx, src/components/pages/blog/posts-list/posts-list.jsx, src/components/shared/blog-post-author/blog-post-author.jsx, src/components/shared/blog-post-author/index.js, src/templates/blog-post.jsx, src/templates/blog.jsx
This pull request brings the option of adding multiple authors for Blog posts.
[Preview](https://websitemain62807-blogauthors.gtsb.io/blog/)
**TODO**
=> feat: add multiple authors to blog

src/components/pages/doc/admonition/admonition.jsx, src/components/pages/doc/doc-footer/doc-footer.jsx, src/components/pages/doc/mobile-nav/mobile-nav.jsx, src/components/pages/doc/table-of-contents/table-of-contents.jsx, src/components/shared/code-block/code-block.jsx, src/components/shared/header/header.jsx, src/components/shared/layout/layout.jsx, src/templates/doc.jsx
This pull request brings the follow-up fixes and code refactoring for documentation.
**Changes**
- refactor the header theme logic 
- show copy button of code block on mobile
- change `span` to `h4` in Admonition
- refactor `toggleMenu` function in `MobileNav`
- adjust indents of TOC
=> refactor: doc logic and styles

content/docs/conceptual-guides/regions.md, content/docs/get-started-with-neon/query-with-neon-sql-editor.md, content/docs/get-started-with-neon/query-with-psql-editor.md, content/docs/get-started-with-neon/setting-up-a-project.md, content/docs/guides/django.md, content/docs/guides/go.md, content/docs/guides/node.md, content/docs/guides/sqlalchemy.md, content/docs/guides/vercel.md, content/docs/how-to-guides/import-from-heroku.md, content/docs/reference/technical-preview-free-tier.md, content/docs/security.md, content/release-notes/2022-11-04.md
Use admonition tags. For the branching topics, admonition tags are added under another PR.
=> Use admonition tags

src/components/shared/footer/footer.jsx, src/components/shared/header/header.jsx
This pull request updates the font-size of menu items in the Header & Footer from 18px to 16px.
=> fix: adjust font-size of menu items in header & footer

src/components/pages/doc/mobile-nav/mobile-nav.jsx, src/components/shared/layout/layout.jsx, src/hooks/use-body-lock-scroll.js
This pull request fixes the scroll of Documentation menu & Search modal on mobile devices
=> fix: enable scroll on mobile devices

src/styles/fonts.css, tailwind.config.js
This pull request brings the font optimization using [fontpie](https://github.com/pixel-point/fontpie), preventing layout shift by adjusting metrics of the fallback font.
=> feat: optimize fonts

content/release-notes/2022-11-17.md
Preview:
https://websitemain62807-antonycpatch159718.gatsbyjs.io/docs/release-notes/
=> control plane release 2022-11-17

content/docs/security.md
Updated to reflect that we now have regions outside of the USA, also bumped the year for the security roadmap
=> Update security page

content/docs/guides/laravel.md, content/docs/sidebar.yaml
This PR adds a guide on how to use Neon Database with Laravel.
=> Add Laravel guide

.github/workflows/linkinator.yml, README.md, linkinator.config.json, package-lock.json, package.json
npm script and GitHub CI Workflow for checking broken links on Neon website
=> feat: linkinator

content/docs/connect/connect-from-any-app.md, content/docs/connect/passwordless-connect.md, content/docs/connect/query-with-psql-editor.md, content/docs/get-started-with-neon/setting-up-a-project.md, content/docs/get-started-with-neon/signing-up.md, content/docs/guides/django.md, content/docs/guides/go.md, content/docs/guides/hasura.md, content/docs/guides/java.md, content/docs/guides/laravel.md, content/docs/guides/node.md, content/docs/guides/prisma.md, content/docs/guides/rust.md, content/docs/guides/sqlalchemy.md, content/docs/guides/symfony.md, content/docs/guides/vercel.md, content/docs/how-to-guides/import-an-existing-database.md, content/docs/how-to-guides/import-from-heroku.md, content/docs/introduction/regions.md, content/docs/introduction/roadmap.md, content/docs/reference/glossary.md
- Some changes related to dropping the invite gate
- Updated the Neon default database name (now neondb instead of main)
- Other edits
=> Dprice misc drop invite gate updates

content/release-notes/2022-12-06.md
https://websitemain62807-releasenotes20221206.gatsbyjs.io/docs/release-notes/
=> Release notes 2022-12-06

content/docs/manage/api-keys.md, content/docs/manage/branches.md, content/docs/reference/api-reference.md
Update cURL examples in the docs
- Do not use -X where it is not necessary
- Use -H for response type
Fix a title linking issue in one of the same files.
https://websitemain62807-dpriceupdateapiexamples.gatsbyjs.io/docs/reference/api-reference/
https://websitemain62807-dpriceupdateapiexamples.gatsbyjs.io/docs/manage/api-keys/
https://websitemain62807-dpriceupdateapiexamples.gatsbyjs.io/docs/manage/branches/#branching-with-the-neon-api
=> Update cURL examples

src/styles/fonts.css, tailwind.config.js
This pull request brings the font optimization to avoid layout shift using [fontpie](https://github.com/pixel-point/fontpie)
=> feat: optimize fonts with fontpie

content/docs/get-started-with-neon/setting-up-a-project.md, content/docs/introduction/technical-preview-free-tier.md, content/docs/manage/api-keys.md, content/docs/manage/branches.md, content/docs/manage/databases.md, content/docs/manage/endpoints.md, content/docs/manage/overview.md, content/docs/manage/projects.md, content/docs/manage/users.md, content/docs/reference/api-reference.md
Revise/expand the page titles in the **Manage** section.
https://websitemain62807-dpriceupdatemanagesectiontitle.gatsbyjs.io/docs/manage/overview/
=> Revise page titles

content/docs/guides/java.md, content/docs/manage/branches.md
https://websitemain62807-dpriceupdatelinks.gatsbyjs.io/docs/guides/java/#connect-with-jdbc
https://websitemain62807-dpriceupdatelinks.gatsbyjs.io/docs/manage/branches/#list-branches-with-the-api
=> Fix links to address linter errors

content/docs/manage/api-keys.md
=> Update URL to link to API reference v2

content/release-notes/2022-12-14.md
Hi @tychoish 
I expanded the RNs content. If it looks OK to you, please feel free merge. Thank you!
https://websitemain62807-tychoishreleasenotes20221214.gatsbyjs.io/docs/release-notes/
=> release-notes: 2022-12-14

content/docs/get-started-with-neon/signing-up.md
Mention the free tier in the sign up section.
https://websitemain62807-dpricesignuptopicrevisions.gatsbyjs.io/docs/get-started-with-neon/signing-up/
=> Update sign-up topic

content/docs/manage/projects.md
- Mention web_access user
- Revise information about connection details
- Add steps for editing a project
https://websitemain62807-dpricemanageprojectupdates.gatsbyjs.io/docs/manage/projects/
=> Update Manage project topic

content/docs/guides/django.md, content/docs/guides/go.md, content/docs/guides/hasura.md, content/docs/guides/java.md, content/docs/guides/laravel.md, content/docs/guides/node.md, content/docs/guides/prisma.md, content/docs/guides/rust.md, content/docs/guides/sqlalchemy.md, content/docs/guides/symfony.md, content/docs/guides/vercel.md
- Revise steps for setting up a project. Most users will have done this already since it is tightly integrated with signing up for Neon.
- Simplify connection detail content and make it more consistent.
- Add "Need help?" section to the bottom of each topic.
https://websitemain62807-dpriceguidesrevisions.gatsbyjs.io/docs/guides/django/
=> Dprice guides revisions

content/docs/manage/operations.md
Remove stop_compute operation. It's not used anymore.
=> Remove stop_compute operation

content/docs/manage/users.md
Mention role name length limit
=> Mention role name length limit

content/docs/manage/api-keys.md, content/docs/manage/branches.md
Remove old "logical_size_limit" attribute from branch API response examples & update create project response example to include "branch_logical_size_limit" attribute
https://websitemain62807-dpriceupdatebranchingapirespon.gatsbyjs.io/docs/manage/branches/#create-a-branch-with-the-api
https://websitemain62807-dpriceupdatebranchingapirespon.gatsbyjs.io/docs/manage/api-keys/
=> Remove old branch API response attribute

content/docs/get-started-with-neon/query-with-neon-sql-editor.md
Add information about Explain and Analyze features in the Neon SQL Editor.
https://websitemain62807-dpriceadddetailsaboutexplainan.gatsbyjs.io/docs/get-started-with-neon/query-with-neon-sql-editor/#explain-and-analyze
Note: Information about the Explain and Analyze features should be expanded in the future with a tutorial.
=> Add information about Explain and Analyze features

content/docs/manage/api-keys.md
Add content showing how to create, list, and delete API keys using the Neon API.
https://websitemain62807-dpriceaddapiexamplestomanageap.gatsbyjs.io/docs/manage/api-keys/#manage-api-keys-with-the-neon-api
=> Add api examples

src/pages/api-reference/v2.jsx
=> feat: add link to download the spec

content/docs/guides/aws-lambda.md, content/docs/sidebar.yaml
Deploy preview:
https://websitemain62807-dpriceawslambda2.gatsbyjs.io/docs/guides/aws-lambda/
=> Add lambda content

content/docs/manage/endpoints.md
Add endpoint API examples
https://websitemain62807-dpriceaddendpointapiexamples.gatsbyjs.io/docs/manage/endpoints/#manage-endpoints-with-the-neon-api
- create
- list
- update
- delete
=> Dprice add endpoint api examples

content/docs/guides/prisma-tutorial.md, content/docs/guides/prisma.md
- Update examples repo link
- Indent connection string example
=> Prisma content edits

next/src/app/blog/[slug]/head.jsx, next/src/components/shared/seo/seo.jsx, next/src/utils/api-posts.js
This PR updates posts head and seo component
=> fix: update post head and seo component

next/public/images/pages/developer-days/background-lg.svg, next/public/images/pages/developer-days/background-md.svg, next/public/images/pages/developer-days/background-xl.svg, next/public/images/pages/developer-days/background.svg, next/public/images/pages/developer-days/straight-line.inline.svg, next/src/app/layout.jsx, next/src/components/pages/branching/cta/cta.jsx, next/src/components/shared/seo/seo.jsx
This PR fixes issue with /branching horizontal scroll, theme-color etc.
=> Fix next issues with horizontal scroll, theme-color etc.

content/docs/connect/connectivity-issues.md, next/content/docs/connect/connectivity-issues.md
I just tested it. See:
https://community.neon.tech/t/postgresnio-swift-sni-support/419/4
=> docs: update list of drivers, PostgresNIO supports SNI

src/components/shared/topbar/topbar.jsx
https://neon-next-a30jzwfos-neondatabase.vercel.app/
=> update banner to: Neon 🤝 Vercel: Create a branch for every Preview Deployment

content/release-notes/2023-02-08.md, content/release-notes/2023-02-10.md
https://neon-next-git-console-2023-02-10-neondatabase.vercel.app/docs/release-notes/2023-02-08
https://neon-next-git-console-2023-02-10-neondatabase.vercel.app/docs/release-notes/2023-02-10
=> 2023-02-10 and 2023-02-08 releases

content/docs/guides/koyeb.md, content/docs/sidebar.yaml
https://neon-next-git-dprice-add-koyeb-guide2-neondatabase.vercel.app/docs/guides/koyeb
=> Add koyeb content

vercel.json
This PR updates /developer-days proxy redirect
=> Dev days redirect

content/docs/manage/integrations.md
- Add note about the page being empty if there are no integrations
- Add Supported integrations section
https://neon-next-git-dprice-integrations-content-updates-neondatabase.vercel.app/docs/manage/integrations
=> Update Integrations docs

content/release-notes/2023-03-06.md
Add Release notes for 03-06 Console release
https://neon-next-git-dprice-03-06-console-rel-notes-neondatabase.vercel.app/docs/release-notes
=> Release notes for 03-06 Console release

content/docs/introduction/billing.md
right now it looks like we divide by the amount of hours
https://neon-next-git-stepashka-patch-4-neondatabase.vercel.app/docs/introduction/billing#billing-rates
=> docs: update the units to make the unit dimensions right

content/docs/README.md, src/components/pages/doc/post/post.jsx, src/utils/api-docs.js
This PR adds support for subtitle field to the docs frontmatter.
=> Add subtitle field to the docs

content/release-notes/2023-03-03.md, content/release-notes/2023-03-08.md, content/release-notes/2023-03-15.md
=> Update Release Notes tags

content/docs/introduction/billing.md
Preview:
See the notes section below the plans table:
https://neon-next-git-dprice-update-plan-detais-neondatabase.vercel.app/docs/introduction/billing#neon-plans
=> Update billing notes

content/docs/guides/aws-lambda.md, content/docs/guides/django.md, content/docs/guides/go.md, content/docs/guides/hasura.md, content/docs/guides/java.md, content/docs/guides/koyeb.md, content/docs/guides/laravel.md, content/docs/guides/nextjs.md, content/docs/guides/node.md, content/docs/guides/prisma-guide.md, content/docs/guides/prisma.md, content/docs/guides/rust.md, content/docs/guides/sqlalchemy.md, content/docs/guides/stepzen.md, content/docs/guides/symfony.md, content/docs/guides/vercel-manual.md, content/docs/guides/vercel.md
We recently added support for subtitles to the docs.
Add subtitles to all of our guide documentation to improve UX and SEO.
https://neon-next-git-dprice-add-subtitles-neondatabase.vercel.app/docs/guides/aws-lambda
=> Add subtitles to guides

src/components/pages/pricing/estimates/estimates.jsx
This pull request replaces the react-tooltip with a custom tooltip due to the issue of Next.js last versions https://github.com/vercel/next.js/issues/47005
=> feat: develop custom tooltip

src/components/shared/content/content.jsx
This PR fixes mdx client-side navigation
=> Fix mdx client-side navigation

src/constants/blog.js
This PR increases the number of posts per page
=> Chore: increase posts per page

content/release-notes/2023-03-27.md
Add Docs release notes:
https://neon-next-git-dprice-03-27-docs-release-notes-neondatabase.vercel.app/docs/release-notes/2023-03-27
=> Create 2023-03-27.md Docs Release notes

content/release-notes/2023-03-28.md
https://neon-next-git-vk-release2023-03-28-neondatabase.vercel.app/docs/release-notes/2023-03-28
=> fix: storage release 2023-03-28

content/release-notes/2023-03-29.md
https://neon-next-git-release-2023-03-29-neondatabase.vercel.app/docs/release-notes/2023-03-29
=> Release 2023-03-29

content/docs/introduction/roadmap.md, content/docs/introduction/technical-preview-free-tier.md
- We link to the Free Tier topic from the console for more information about the Technical Preview. Add back info about the Technical preview.
- Minor edit to roadmap topic
=> Mention Technical Preview

content/docs/connect/connectivity-issues.md
see https://github.com/porsager/postgres/commit/498f2aec9fa2abe7da548865abffb148ba438946
=> postgres.js supported

content/release-notes/2023-04-11-storage.md
Preview:
https://neon-next-git-dprice-04-11-storage-relnotes-neondatabase.vercel.app/docs/release-notes/2023-04-11-storage
=> Dprice 04-11 storage release notes

src/hooks/use-algolia-search.js
This PR disables Algolia empty searches
=> Feat: disable empty algolia search requests

src/components/pages/careers/hero/hero.jsx, src/components/pages/careers/jobs-list/jobs-list.jsx, src/components/pages/home/advantages/advantages.jsx, src/components/pages/home/community/community.jsx, src/components/pages/home/cta/cta.jsx, src/components/pages/home/data-branching/data-branching.jsx, src/components/pages/home/features/features.jsx, src/components/pages/home/hero/hero.jsx, src/components/pages/home/saas/saas-illustration/data/saas-illustration-lottie-data.json, src/components/pages/home/saas/saas.jsx, src/components/pages/home/scalability/scalability.jsx, src/components/pages/home/storage/storage.jsx, src/components/shared/header/header.jsx, src/components/shared/subscribe-minimalistic/subscribe-minimalistic.jsx, src/components/shared/subscribe/subscribe.jsx, src/constants/menus.js
Various minor website copy edits:
https://neon-next-git-dprice-minor-website-copy-updates-neondatabase.vercel.app/
=> Website copy revisions

content/docs/security/security-overview.md
security@neon.tech was invlid. Changed to support@neon.tech
=> Update email in security topic

package-lock.json, package.json, src/scripts/build-algolia-search.js
This PR adds chunked content to algolia index
=> feat: add chunked content to algolia index

src/components/pages/release-notes/hero/hero.jsx, src/components/pages/release-notes/hero/images/rss.inline.svg, src/scripts/rss.js, src/utils/get-release-notes-date-from-slug.js
This pull request brings RSS link to the release notes pages
**Additional changes**
- fixed the date in rss feed
=> feat: add rss link to release-notes

content/docs/guides/vercel-overview.md, content/docs/introduction.md, content/docs/sidebar.yaml
- Overview page revisions:
https://neon-next-git-dprice-vercel-content-edits-neondatabase.vercel.app/docs/guides/vercel-overview
- Update Vercel card link & text in Docs introduction page:
- https://neon-next-git-dprice-vercel-content-edits-neondatabase.vercel.app/docs/introduction
Minor TOC adjustments
=> Vercel content edits

content/docs/introduction/billing.md
Revise compute unit prices
https://neon-next-git-dprice-update-compute-cost-neondatabase.vercel.app/docs/introduction/billing#billing-rates
=> Update compute unit prices

content/release-notes/2023-05-05-storage.md
Preview:
https://neon-next-git-dprice-05-05-storage-release-notes-neondatabase.vercel.app/docs/release-notes
=> Dprice 05 05 storage release notes

src/components/pages/pricing/calculator/calculator.jsx, src/components/pages/pricing/hero/hero.jsx
This pull request brings content update according to https://github.com/neondatabase/website/issues/733 and https://github.com/neondatabase/website/issues/734
=> chore: minor content updates on pricing page

content/docs/introduction/billing.md
Revise cancel subscription content:
https://neon-next-git-dprice-billing-downgrade-inst-e01a6d-neondatabase.vercel.app/docs/introduction/billing#cancel-a-subscription
=> Revise cancel subscription content

content/release-notes/2023-05-16-console.md
Preview:
https://neon-next-git-dprice-console-release-notes-05-16-neondatabase.vercel.app/docs/release-notes
=> Dprice console release notes 05 16

content/docs/guides/node.md
Preview:
https://neon-next-git-dprice-update-nodejs-example-use-pg-neondatabase.vercel.app/docs/guides/node
=> Dprice update nodejs example to include pg and postgres client examples

content/docs/extensions/pgvector.md, content/release-notes/2022-12-28-console.md
=> Fix links for SEO Audit

content/docs/connect/connection-pooling.md, content/docs/introduction/billing.md, content/release-notes/2023-05-29-console.md
Preview:
https://neon-next-git-dprice-05-29-console-release-neondatabase.vercel.app/docs/release-notes
=> Console release notes 05-29-2023

content/docs/guides/django.md, content/docs/guides/vercel-postgres.md, content/docs/guides/wundergraph.md, src/components/pages/doc/youtube-iframe/index.js, src/components/pages/doc/youtube-iframe/youtube-iframe.jsx, src/components/shared/content/content.jsx
This pull request brings the custom component YoutubeIframe for docs posts
=> feat: custom component youtube iframe

content/docs/connect/connect-postgres-gui.md
Preview:
https://neon-next-git-dprice-add-forest-admin-as-te-455cf9-neondatabase.vercel.app/docs/connect/connect-postgres-gui#tested-gui-applications-and-ides
=> Add Forest Admin to list of tested clients

src/app/blog/(index)/category/[slug]/page.jsx, src/app/blog/(index)/layout.jsx, src/app/blog/(index)/page.jsx, src/components/pages/404/hero/hero.jsx, src/components/pages/blog/sidebar/sidebar.jsx, src/components/pages/pricing/calculator/calculator.jsx, src/utils/api-posts.js
This pull request brings the changes:
- remove the border in docs 404 page 
- remove https://neon.tech/blog/category/uncategorized page
- mobile style fixes for Pricing page (320-345px breakpoint)
=> feat: optimize page indexing

next.config.js, src/app/layout.jsx, src/components/pages/home/community/community.jsx, src/components/pages/home/data-branching/data-branching.jsx, src/components/shared/layout/layout.jsx, src/components/shared/subscribe/subscribe.jsx, src/components/shared/topbar/topbar.jsx, src/utils/get-metadata.js
This pull request brings the following updates:
- added theme color to set background color of tab bar in mobile safari
- set cache control for images 
- add missing aria-label text
- changed heading h4 to h3 to enhance the lighthouse score
<details>
src="https://github.com/neondatabase/website/assets/48465000/d79fba3a-ac4a-4e81-be64-b2cf371d57bc">
</details>
=> fix: update theme color

content/docs/security/security-overview.md
=> Add SOC2 section to security page

content/docs/manage/api-keys.md, content/docs/manage/roles.md, content/docs/reference/api-reference.md, content/docs/reference/glossary.md, content/release-notes/2022-07-11-console.md, content/release-notes/2022-08-15-console.md, content/release-notes/2022-11-04-console.md
Update or remove old links identified by the SEO Audit
=> Update / remove old links

.gitignore, next-sitemap.config.js, public/robots.txt, src/app/api/preview/route.js, src/app/blog/[slug]/page.jsx, src/app/blog/wp-draft-post-preview-page/page.jsx
This PR will hide draft pages for unpublished posts from web crawlers.
=> feat: improve draft mode for blog

src/components/shared/footer/footer.jsx, src/components/shared/footer/status-badge/status-badge.jsx, src/constants/menus.js
This PR brings more visibility to Contact Sales page by bringing the link to footer
=> feat: add contact sales link to footer

content/docs/connect/connection-errors.md, content/docs/introduction/status.md, content/docs/sidebar.yaml
- Add a "Status" page to the docs mentioning our new status page
- Reference the status page from our connection errors topic
https://neon-next-git-dprice-mention-neon-status-pa-47a895-neondatabase.vercel.app/docs/introduction/status
=> Add status page and reference link

next.config.js
This PR will fix bug, when SVG files placed in IMG tag not showing.
=> fix: non inline svg images

src/app/docs/release-notes/[...slug]/page.jsx, src/components/pages/release-notes/release-note-list/release-note-list.jsx, src/components/shared/content/content.jsx
This pull request removes anchors in Release notes index page to prevent duplicated anchors on one page
=> fix: remove anchors in release notes index

content/docs/manage/projects.md, content/release-notes/2023-06-20-console.md
I only saw a couple of items to mention in the release notes. 2023-06-20 release: https://github.com/neondatabase/cloud/pull/5491
The rest of the changes appear to be internal or related to a future items. Please let me know of I missed anything.
Preview:
https://neon-next-git-dprice-2023-06-20-console-rel-85026c-neondatabase.vercel.app/docs/release-notes/2023-06-20-console
=> 2023-06-20 Console Release Notes

src/components/pages/contact-sales/hero/contact-form/contact-form.jsx, src/components/pages/partners/apply/form/form.jsx, src/components/pages/partners/benefits/benefits.jsx, src/components/pages/partners/hero/hero.jsx, src/components/pages/partners/integration/integration.jsx
=> Copy revisions for Partners page

content/docs/extensions/pgvector.md
Add note regarding increasing memory:
https://neon-next-git-dprice-pgvetor-index-memory-neondatabase.vercel.app/docs/extensions/pgvector#indexing-vectors
=> Increase memory for index creation with pgvector

.env.example, src/app/blog/(index)/layout.jsx, src/components/pages/blog/sidebar/sidebar.jsx, src/components/pages/doc/sidebar/sidebar.jsx, src/components/shared/header/header.jsx, src/components/shared/layout/layout.jsx, src/components/shared/search/search.jsx, src/styles/search.css
This pull request brings the Docsearch for the Blog index page
**TODO**
Preview: https://neon-next-git-blog-search-neondatabase.vercel.app/blog
=> feat: add docsearch to blog

content/docs/introduction/read-replicas.md, content/docs/sidebar.yaml
Remove draft setting, add to TOC
=> Expose read replica docs

content/docs/extensions/pg_embedding.md
Clearly outline items to consider when creating an HNSW index:
https://neon-next-git-dprice-pgembedding-pro-con-updates-neondatabase.vercel.app/docs/extensions/pg_embedding#create-an-hnsw-index
=> Dprice pg embedding updates

content/docs/extensions/pg_embedding.md, content/docs/manage/roles.md, content/release-notes/2023-07-10-drivers.md, content/release-notes/2023-07-11-storage-and-compute.md, content/release-notes/2023-07-12-console.md, content/release-notes/2023-07-12-storage-and-compute.md, content/release-notes/2023-07-13-storage-and-compute.md, content/release-notes/2023-07-14-console.md
July 10, 11, 12, 13, 14 release notes:
https://neon-next-git-dprice-lauch-week-release-notes-neondatabase.vercel.app/docs/release-notes
=> Add launch week release notes

src/components/pages/doc/sidebar/sidebar.jsx
This pull request adjust styles for the doc sidebar
- add the dark gradient to the top and bottom of sidebar
- increase the bottom padding of sidebar
=> fix: sidebar height

content/docs/guides/exograph.md, content/docs/sidebar.yaml
Add the guide to integrate Neon with Exograph through a simple complete example.
=> docs: add the guide to work with Exograph

content/docs/introduction/manage-billing.md, content/docs/introduction/pro-plan.md, src/components/pages/pricing/faq/faq.jsx
Update downgrade / cancel subscription content to reflect UI changes
Downgrade your plan
https://neon-next-git-dprice-update-downgrade-content-neondatabase.vercel.app/docs/introduction/manage-billing#downgrade-your-plan
Pricing FAQ:
https://neon-next-git-dprice-update-downgrade-content-neondatabase.vercel.app/pricing
=> Update downgrade content

content/docs/reference/compatibility.md
Update Postgres compatibility content. We now support creating roles via SQL.
https://neon-next-git-dprice-update-compatibility-content-neondatabase.vercel.app/docs/reference/compatibility#postgresql-extensions
=> Update Postgres compatibility content

src/components/shared/topbar/topbar.jsx
https://neon-next-git-ai-page-banner-neondatabase.vercel.app/
=> add ai page banner

content/docs/ai/ai-concepts.md, content/docs/ai/ai-scale-with-neon.md
Remove draft tags from AI docs
=> Remove draft tags

content/docs/introduction/manage-billing.md
Move text from the UI into the Mange billing topic in the docs. 
https://neon-next-git-dprice-move-billing-content-from-ui-neondatabase.vercel.app/docs/introduction/manage-billing
=> Move billing content from the UI

content/docs/manage/backups.md, content/docs/sidebar.yaml
Backup topic:
https://neon-next-git-dprice-backup-content-neondatabase.vercel.app/docs/manage/backups
=> Add backup content

content/docs/introduction.md, src/components/pages/doc/community-banner/community-banner.jsx
=> Update the docs introduction page

content/docs/guides/branching-github-actions.md
Reference sample applications that use GitHub Actions from the GitHub Actions topic.
We'll update the repo READMEs as well.
https://neon-next-git-dprice-mention-github-action-ea2959-neondatabase.vercel.app/docs/guides/branching-github-actions#example-applications
=> Reference GitHub Action sample applications

content/release-notes/2023-08-14-console.md
Release note:
https://neon-next-git-dprice-console-release-notes-bac93e-neondatabase.vercel.app/docs/release-notes
=> 2023-08-14-console Release notes

content/docs/introduction/auto-suspend.md, content/docs/introduction/compute-lifecycle.md, content/docs/reference/compatibility.md, content/docs/sidebar.yaml, src/constants/links.js
=> Seo related updates

src/app/thank-you/page.jsx, src/components/pages/thank-you/hero/hero.jsx, src/constants/seo-data.js
This pull request brings some fixes for `/thank-you` page:
- used export metadata 
- removed redundant components in hero section
- removed social preview for the `/thank-you` page, set the default one 
Preview: https://neon-next-git-thank-you-page-fixes-neondatabase.vercel.app/thank-you
=> fix: thank you page fixes

content/docs/extensions/pg-extensions.md, content/release-notes/2023-09-05-storage-and-compute.md
Release note:
https://neon-next-git-dprice-custom-extension-support-neondatabase.vercel.app/docs/release-notes
Docs:
https://neon-next-git-dprice-custom-extension-support-neondatabase.vercel.app/docs/extensions/pg-extensions#custom-built-extensions
=> Custom extension docs

content/docs/reference/sdk.md
Preview:
https://neon-next-git-dprice-neon-sdk-doc-update-neondatabase.vercel.app/docs/reference/sdk
=> Add docs for @neondatabase/api-client

content/docs/guides/read-replica-data-analysis.md, content/docs/guides/read-replica-guide.md
Add CLI and API commands:
https://neon-next-git-dprice-add-cli-command-read-replicas-neondatabase.vercel.app/docs/guides/read-replica-guide#create-a-read-replica
https://neon-next-git-dprice-add-cli-command-read-replicas-neondatabase.vercel.app/docs/guides/read-replica-data-analysis#create-a-read-replica
=> Add CLI create read replica command

content/docs/extensions/pg-extensions.md, content/docs/guides/project-sharing-guide.md, content/docs/manage/api-keys.md, content/docs/manage/branches.md, content/docs/manage/databases.md, content/docs/manage/endpoints.md, content/docs/manage/operations.md, content/docs/manage/projects.md, content/docs/manage/roles.md, content/release-notes/2023-09-19-console.md
Preview:
https://neon-next-git-dprice-console-release-09-19-neondatabase.vercel.app/docs/release-notes/2023-09-19-console
- Includes some general edits and revisions.
- Addition of "protected names" content for databases and roles
=> Console release notes 09-19-2023

src/app/blog/(index)/category/[slug]/page.jsx, src/components/pages/blog/blog-post-card/blog-post-card.jsx, src/components/pages/blog/load-more-posts/index.js, src/components/pages/blog/load-more-posts/load-more-posts.jsx, src/components/pages/blog/sidebar/sidebar.jsx, src/components/shared/button/button.jsx, src/constants/blog.js, src/utils/api-posts.js
This pull request brings the all-posts page
=> feat: add all-posts page for blog

src/components/shared/footer/status-badge/status-badge.jsx
This PR brings an update to the footer status badge to seamlessly migrate to incident.io API
=> feat: migrate to incident.io api

src/app/ai/page.jsx, src/components/pages/ai/integration/integration.jsx
- Remove references to pg_embedding from the AI page on the website
- Removed Twitter quotes, which are all about pg_embedding
- https://neon-next-git-dprice-update-ai-page-remove-bc546d-neondatabase.vercel.app/ai
=> Remove references to pg_embedding

content/docs/manage/roles.md
Minor update to add missing word.
=> Missing word

next.config.js
This pull request adds a redirect `/developer-days` to `https://devdays.neon.tech`
=> feat: add redirect for devdays

src/app/[static]/page.jsx, src/styles/doc-content.css
This pull request brings the fixes for tables in the static pages
=> fix: adjust styles for table in static page

public/events/neon-developer-days-3.ics
this PR adds the iCal invite for Developer Days 
https://neon-next-agsvcr3pw-neondatabase.vercel.app/events/neon-developer-days-3.ics
=> add .ics file

next-sitemap.config.js, src/app/all-things-open-2023/page.jsx, src/app/last-week-in-aws/page.jsx, src/constants/seo-data.js
This PR brings a home page duplicate for All Things Open event and blocks this page from indexing.
=> chore: add all things open 2023 promo page and exclude it from indexing

content/docs/introduction/support.md
Related to https://github.com/neondatabase/company_projects/issues/154
=> disable support for free tier

content/docs/guides/guides-intro.md, content/docs/introduction.md
Add remix card to Guides section on intro page and guides landing page.
https://neon-next-git-dprice-add-remix-card-neondatabase.vercel.app/docs/introduction#guides
https://neon-next-git-dprice-add-remix-card-neondatabase.vercel.app/docs/guides/guides-intro
=> Add remix card

src/components/pages/home/hero/hero.jsx, src/components/pages/home/scalability/scalability.jsx
=> Minor website copy edit

content/release-notes/2023-10-27-console.md
New onboarding is for Free Tier users
=> Clarify onboarding release note

src/styles/doc-content.css
This pull request brings the custom list style: 1, 1.1, 1.1.1
=> fix: static list style

src/components/pages/pricing/faq/item/item.jsx
This pull request sends the pricing FAQ events to GA
=> feat: send pricing events to ga

content/docs/guides/guides-intro.md, content/docs/introduction.md
Add Quarkus cards to introduction page and guides intro page
https://neon-next-git-dprice-add-quarkus-cards-neondatabase.vercel.app/docs/introduction#guides
https://neon-next-git-dprice-add-quarkus-cards-neondatabase.vercel.app/docs/guides/guides-intro
=> Add Quarkus cards

content/docs/guides/vercel.md
Clarify that there is a 1:1 relationship between Vercel and Neon Projects
https://neon-next-git-dprice-update-vercel-integrat-3166b4-neondatabase.vercel.app/docs/guides/vercel#make-the-integration-available-to-other-vercel-projects
=> Update Neon Vercel Integration docs

content/docs/extensions/neon-utils.md
Fix typo in neon_utils docs + edits
https://neon-next-git-dprice-fix-neon-utils-typo-neondatabase.vercel.app/docs/extensions/neon-utils#use-the-numcpus-function
=> Fix typo in neon_utils docs + edits

.github/workflows/update-frontmatter.yml, content/docs/README.md, content/docs/guides/read-replica-prisma.md, src/components/pages/doc/code-tabs/code-tabs.jsx
This pull request brings the ability to add text content and code block in CodeTabs component in docs
**TODO**
=> feat: text content and code block in code tabs

package-lock.json, package.json, src/components/pages/doc/table-of-contents/item/index.js, src/components/pages/doc/table-of-contents/item/item.jsx, src/components/pages/doc/table-of-contents/table-of-contents.jsx, src/components/shared/anchor-heading/anchor-heading.jsx, src/utils/api-docs.js
This pull request introduces a dynamic table of contents for docs
**Additional changes**
- removed h4 from ToC
Preview: https://neon-next-git-toc-updates-neondatabase.vercel.app/docs/guides/nextjs
=> ToC updates for docs

content/release-notes/2023-11-08-console.md, src/app/docs/(neon)/release-notes/rss.xml/route.js, src/utils/get-excerpt.js
This pull request updates the RSS description of release notes
=> fix: update the rss description for release notes

src/components/shared/search/search.jsx
This pull request sends search events to GA.
=> feat: send gtag search event to

content/docs/guides/branching-intro.md, src/components/pages/home/data-branching/data-branching-illustration/data/data-branching-illustration-lottie-data.json, src/components/pages/home/data-branching/data-branching.jsx, src/components/pages/home/storage/storage.jsx
Avoid term "data branching". It's under copyright.
=> Fix branching terminology

content/docs/security/soc2-compliance.md, content/release-notes/2023-12-05-docs.md
Update our SOC 2 documentation to mention SOC 2 Type 2 compliance:
https://neon-next-git-dprice-soc2-type2-doc-update-neondatabase.vercel.app/docs/security/soc2-compliance
Release note:
https://neon-next-git-dprice-soc2-type2-doc-update-neondatabase.vercel.app/docs/release-notes
=> Update SOC 2 documentation

content/docs/guides/flyway-multiple-environments.md, content/docs/guides/guides-intro.md, content/docs/security/security-overview.md, content/release-notes/2023-10-09-storage-and-compute.md
Minor SEO updates
- redirects
- duplicate meta description
=> Minor SEO updates

src/components/pages/pricing/calculator/calculator.jsx
This pull request fixes the project storage price per hour on pricing page
=> fix: project storage price on pricing page

content/docs/manage/roles.md
Add instructions for resetting a password with your own password value. This came from a question in the Discord community.
https://neon-next-git-dprice-reset-password-update-neondatabase.vercel.app/docs/manage/roles#reset-a-password
=> Update reset password instructions

content/docs/manage/integrations.md
Updated to match changes in https://github.com/neondatabase/cloud/issues/7812 when it goes into prod
=> Update integrations instructions

src/app/blog/(index)/layout.jsx, src/components/pages/blog/sidebar/sidebar.jsx, src/constants/blog.js
This pull request gets blog categories for the sidebar on blog index page.
=> fix: update blog categories

src/components/pages/pricing/hero/hero.jsx
This pull request brings updates to Pricing page
Preview: https://neon-next-git-pricing-minor-updates-neondatabase.vercel.app/pricing
=> fix: update pricing value

src/components/pages/blog-post/aside/aside.jsx
This pull request brings the minor styles updates for blog post author
=> fix: minor updates for blog post author

src/app/careers/page.jsx, src/components/pages/careers/hero/hero.jsx, src/components/pages/careers/offsite/index.js, src/components/pages/careers/offsite/offsite.jsx, src/components/pages/doc/youtube-iframe/youtube-iframe.jsx, src/components/shared/footer/footer.jsx, src/components/shared/subscribe-minimalistic/subscribe-minimalistic.jsx
This pull request brings the new section team offsite for Careers page
=> feat: develop team offsite section

src/components/pages/pricing/estimates/metrics/metrics.jsx, src/components/pages/pricing/estimates/select/select.jsx
This pull request brings a minor fix of scroll offset for mobile version
=> fix: set scroll offset for mobile version

content/docs/shared-content/need-help.md
Add Discord to the "Need help?" footer in the docs
=> Add Discord to Need help? footer

.github/workflows/reindex-algolia.yml
This pull request brings the algolia docsearch reindexing github action workflow when adding new doc file
=> Reindex algolia on new doc file

src/components/shared/footer/footer.jsx
This pull request updates the copyright text in the footer `Neon 2024 Ⓒ All rights reserved` => `Copyright Ⓒ 2022 – 2024 Neon, Inc.`
=> fix: footer update

content/docs/serverless/serverless-driver.md
- Reorganized content
- Added more information and examples from the GitHub repo
- Added reference links
- Added "Need help?" section
- https://neon-next-git-dprice-serverless-driver-update-neondatabase.vercel.app/docs/serverless/serverless-driver
=> Serverless driver content revisions

content/docs/reference/cli-auth.md, content/docs/reference/cli-branches.md, content/docs/reference/cli-connection-string.md, content/docs/reference/cli-databases.md, content/docs/reference/cli-install.md, content/docs/reference/cli-me.md, content/docs/reference/cli-operations.md, content/docs/reference/cli-projects.md, content/docs/reference/cli-roles.md, content/docs/reference/cli-set-context.md, content/docs/reference/neon-cli.md
Added proper upgrade instructions:
https://neon-next-git-dprice-cli-docs-updates-neondatabase.vercel.app/docs/reference/cli-install#upgrade
Mention --context_file option throughout. For example:
https://neon-next-git-dprice-cli-docs-updates-neondatabase.vercel.app/docs/reference/cli-auth#options
Added branch reset options:
https://neon-next-git-dprice-cli-docs-updates-neondatabase.vercel.app/docs/reference/cli-branches#reset
Added IP Allow options and examples:
https://neon-next-git-dprice-cli-docs-updates-neondatabase.vercel.app/docs/reference/cli-projects#update
=> Neon CLI updates

content/docs/functions/json_build_object.md
Add postgres documentation for `json_build_object` function
https://neon-next-git-fork-yirenlu92-add-function-neondatabase.vercel.app/docs/functions/json_build_object
=> Add json_build_object

content/changelog/2023-02-24-console.md, content/docs/community/community-intro.md, content/docs/community/contribution-guide.md, content/docs/connect/connect-securely.md, content/docs/connect/connection-errors.md, content/docs/extensions/pg-extensions.md, content/docs/guides/GUIDE_TEMPLATE.md, content/docs/guides/vercel.md, content/docs/introduction.md, content/docs/introduction/pro-plan.md, content/docs/introduction/regions.md, content/docs/introduction/support.md, content/docs/reference/compatibility.md, content/docs/shared-content/need-help.md
Prioritize Discord in the docs instead of both Discourse and Discord
=> Prioritize Discord

content/docs/guides/astro.md
https://neon-next-git-guides-update-astro-neondatabase.vercel.app/docs/guides/astro#create-a-neon-project
=> chore: add postgres refs to astro guide 

content/docs/functions/json_array_elements.md, content/docs/sidebar.yaml
Add json_array_elements function documentation
=> Add json_array_elements function documentation

content/docs/guides/partner-billing.md, content/docs/introduction/plans.md, content/docs/introduction/pro-plan.md, content/docs/reference/glossary.md
Clarify that we are referring to logical data size
=> Logical data size updates

content/changelog/2024-01-19-console.md, content/docs/guides/logical-replication-neon.md, content/docs/sidebar.yaml
Preview:
https://neon-next-git-dprice-01-19-2024-changelog-neondatabase.vercel.app/docs/changelog/2024-01-19-console
=> Friday changelog 01-19-2024

src/components/pages/pricing/estimates/select/select.jsx
This pull request adds Segment analytics to Pricing page quiz
=> feat: send pricing events to segment

content/docs/guides/vercel.md
Neon Vercel Integration
https://neon-next-git-dprice-vercel-integration-git-ca61ac-neondatabase.vercel.app/docs/guides/vercel
=> Mention Vercel integration support for GitLab and BitBucket

content/docs/extensions/pg-extensions.md
Revise custom extension instructions:
https://neon-next-git-dprice-update-extension-request-info-neondatabase.vercel.app/docs/extensions/pg-extensions
=> Revise custom extension instructions

content/docs/introduction/support.md
Add deep link to Support page modal:
https://neon-next-git-dprice-support-modal-link-neondatabase.vercel.app/docs/introduction/support#open-a-support-ticket
=> Add support modal deep link

content/changelog/2023-03-02-docs.md, content/docs/manage/operations.md, content/docs/reference/api-reference.md
Add docs tabs for Operations to include CLI
=> Add docs tabs for Operations

src/app/blog-sitemap.xml/route.js
This pull request brings the blog sitemap with revalidation at runtime using Route handler
=> fix: rewrite the blog sitemap with revalidate

src/components/pages/pricing/hero/hero.jsx
This pull request brings the note about new plans on Pricing page
=> feat: Add Pricing page note about new plans

src/app/blog/(index)/layout.jsx, src/app/docs/(neon)/layout.jsx, src/app/docs/(postgres)/layout.jsx, src/app/docs/(postgres)/postgres/[slug]/page.jsx, src/components/pages/blog/sidebar/sidebar.jsx, src/components/pages/doc/post/post.jsx, src/components/pages/doc/sidebar/sidebar.jsx
This pull request makes header menu sticky on Blog and Docs pages
=> feat: make header sticky for blog and docs

content/docs/extensions/hstore.md, content/docs/sidebar.yaml
doc for extensions/hstore
https://neon-next-git-frindle-hstore-neondatabase.vercel.app/docs/extensions/hstore
=> doc for extensions/hstore

content/docs/extensions/citext.md, content/docs/sidebar.yaml
doc for extensions/citext
https://neon-next-git-frindle-citext-neondatabase.vercel.app/docs/extensions/citext
=> doc for extensions/citext

content/docs/extensions/pg_trgm.md, content/docs/sidebar.yaml
doc for extensions/pgtrgm
https://neon-next-git-frindle-pgtrgm-neondatabase.vercel.app/docs/extensions/pg_trgm
=> doc for extensions/pgtrgm

content/docs/introduction/billing-sample.md
=> Fix billing sample typo

src/components/shared/topbar/topbar.jsx
=> Update banner to link to changelog

content/docs/data-types/uuid.md, content/docs/sidebar.yaml
=> doc for datatype/uuid

content/docs/security/acceptable-use-policy.md, content/docs/sidebar.yaml
Add Acceptable Use Policy
https://neon-next-git-dprice-acceptable-use-policy-neondatabase.vercel.app/docs/security/acceptable-use-policy
=> Acceptable Use Policy

src/components/shared/topbar/topbar.jsx
Updates top bar to promote the BYO Extension post
=> Update topbar with byo extension

content/docs/guides/koyeb.md
guides/deployment/koyeb - fix cli deploy command
=> guides/deployment/koyeb - fix cli deploy command

content/docs/functions/jsonb_object.md, content/docs/sidebar.yaml
add doc for functions/jsonb object
=> add doc for functions/jsonb object

content/docs/functions/jsonb_extract_path_text.md, content/docs/sidebar.yaml
add doc for functions/jsonb_extract_path_text
=> add doc for functions/jsonb_extract_path_text

content/docs/functions/jsonb_populate_record.md, content/docs/sidebar.yaml
add doc for functions/jsonb populate record
=> add doc for functions/jsonb populate record

content/docs/functions/jsonb_to_record.md, content/docs/sidebar.yaml
add doc for functions/jsonb to record
=> add doc for functions/jsonb to record

content/docs/data-types/json.md, content/docs/sidebar.yaml
=> add doc for types/json

content/docs/data-types/date-and-time.md, content/docs/sidebar.yaml
=> add doc for types/datetime

content/docs/guides/deno.md, content/docs/sidebar.yaml
Add doc on using Neon with Deno Deploy
https://neon-next-git-frindle-guidesdeno-neondatabase.vercel.app/docs/guides/deno
=> Add doc on using Neon with Deno Deploy

content/docs/functions/json_extract_path.md, content/docs/functions/jsonb_extract_path.md, content/docs/guides/deno.md, content/docs/sidebar.yaml
add doc for functions/jsonb_extract_path
=> add doc for functions/jsonb_extract_path

content/docs/functions/jsonb_each.md, content/docs/functions/jsonb_extract_path_text.md, content/docs/functions/jsonb_object.md, content/docs/functions/jsonb_populate_record.md, content/docs/functions/jsonb_to_record.md
fix subheaders for function docs
=> fix subheaders for function docs

src/components/shared/content/content.jsx
This pull request brings the fixes for code block in doc posts, sets the correct language for code block
=> Code block fix

package-lock.json, package.json, src/utils/send-segment-event.js
This pull request brings the dependencies upgrade for  @segment/analytics-next
=> chore: update @segment/analytics-next

src/app/blog/rss.xml/route.js, src/utils/api-posts.js
This pull request brings `content`, `author` and `categories` to blog RSS feed
=> feat: add content to blog rss feed

content/docs/README.md, content/docs/introduction/architecture-overview.md, src/components/shared/content/content.jsx, src/styles/doc-content.css
This pull request brings the ability to add image without border
**TODO**
=> feat: image without border in docs

src/components/pages/doc/sidebar/item/item.jsx
This pull request brings small navigation fix.
- open [preview](https://neon-next-git-fix-doc-nav-neondatabase.vercel.app/docs/introduction)
- make sure that everything looks and works as expected
=> fix: doc navigation

src/components/pages/home/hero/hero.jsx
Swap the homepage talk to sales button for a Pricing button.
=> Switch Homepage Hero buttons

src/app/docs/(neon)/changelog/rss.xml/route.js
This pull request brings the update for the changelog RSS feed, adding date to title
=> feat: update the changelog rss feed

content/docs/get-started-with-neon/signing-up.md
Preview:
https://neon-next-git-bgrenon-email-signin-neondatabase.vercel.app/docs/get-started-with-neon/signing-up#changing-your-email
=> Bgrenon change email

content/docs/reference/compatibility.md
Mention that Postgres server logs are not currently accessible
=> Postgres server log access note

content/docs/guides/laravel.md
Laravel connection issue update
=> Add connection issues section to Laravel doc

src/components/pages/enterprise/benefits/workflow/workflow.jsx, src/components/pages/enterprise/hero/hero.jsx
=> fix: invalid sentence structure on enterprise page

src/components/pages/ai/examples/examples.jsx
Preview
https://neon-next-git-dprice-image-seaerch-app-link-neondatabase.vercel.app/ai
=> Add image search app link to AI page

src/components/pages/pricing/case-studies/case-studies.jsx, src/components/pages/pricing/hero/hero.jsx
=> Pricing page - Update banner compute list items

src/components/pages/pricing/case-studies/case-studies.jsx, src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/data/plans.json, src/components/pages/pricing/plans/table/table.jsx
=> Minor pricing page edits

content/docs/guides/autoscaling-guide.md, content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md, src/components/pages/enterprise/apply/apply.jsx, src/components/pages/partners/plans/data/plans.json, src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/data/plans.json
- Update 7 CU limit to 8
- Fix wording on security features
- Update calendly for enterprise trial
-
=> Pricing Hotfix

content/docs/guides/branch-restore.md, content/docs/reference/cli-branches.md, content/docs/reference/neon-cli.md
preview:
https://neon-next-git-bgrenon-restore-cli-reference-neondatabase.vercel.app/docs/reference/cli-branches#restore
=> Bgrenon restore cli reference

content/docs/guides/heroku.md, content/docs/sidebar.yaml
=> add guide for neon + heroku

content/docs/introduction/usage-metrics.md
Remove storage hours content. We no longer measure by the hour.
=> Update storage details

content/docs/introduction/regions.md
=> Revise text in region request text

content/docs/introduction/plans.md
Add redirect that was missing after the billing update. I removed a file with redirects without moving those redirects to a new file.
=> Add Free Tier redirect

content/docs/guides/guides-intro.md, content/docs/introduction.md
Add technology cards for new Frindle guides
=> Add new technology cards

src/app/blog/(index)/page.jsx, src/utils/api-posts.js
This pull request updates the blog index layout.
=> fix: update blog index layout

src/app/partners/page.jsx, src/components/pages/partners/apply/apply.jsx, src/components/pages/partners/integration/api/api.jsx, src/components/pages/partners/plans/data/plans.json, src/components/pages/partners/plans/table/table.jsx, src/components/pages/pricing/plans/data/plans.json, src/components/pages/pricing/plans/table/table.jsx, src/components/shared/tooltip/tooltip.jsx
This pull request brings some style updates for Partners and Pricing pages
**Changes**
- Partners page:
- Pricing page:
=> Partners & Pricing style updates

src/components/shared/github-star-counter/github-star-counter.jsx
This pull request brings the component GithubStarCounter with the updated logic to refresh the GitHub star count once per day.
=> fix: update github star counter

content/changelog/2024-02-16-console.md, content/docs/guides/autoscaling-guide.md, content/docs/guides/branching-pitr.md, content/docs/guides/logical-replication-airbyte.md, content/docs/guides/logical-replication-concepts.md, content/docs/guides/logical-replication-fivetran.md, content/docs/guides/logical-replication-kafka-confluent.md, content/docs/guides/logical-replication-materialize.md, content/docs/guides/logical-replication-neon.md, content/docs/guides/logical-replication-postgres.md
Unused replication slots topic:
https://neon-next-git-dprice-replication-slot-warnings-neondatabase.vercel.app/docs/guides/logical-replication-neon#unused-replication-slots
Added the note seen here to other replication topics:
https://neon-next-git-dprice-replication-slot-warnings-neondatabase.vercel.app/docs/guides/logical-replication-airbyte#create-a-replication-slot
=> Automatic slot removal docs

content/docs/introduction/how-billing-works.md, content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md
Various edits, tweaks, and a new pricing estimation guide
Landing:
https://neon-next-git-dprice-billing-content-improvements-neondatabase.vercel.app/docs/introduction/about-billing
Pricing estimation guide:
https://neon-next-git-dprice-billing-content-improvements-neondatabase.vercel.app/docs/introduction/how-billing-works#neon-pricing-estimation-guide
=> Billing content revisions

content/docs/guides/deno.md
update Deno guide with using Deno.serve
=> update Deno guide with using Deno.serve

content/docs/guides/logical-replication-airbyte.md, content/docs/guides/logical-replication-concepts.md, content/docs/guides/logical-replication-fivetran.md, content/docs/guides/logical-replication-guide.md, content/docs/guides/logical-replication-kafka-confluent.md, content/docs/guides/logical-replication-materialize.md, content/docs/guides/logical-replication-neon.md, content/docs/guides/logical-replication-postgres.md, content/docs/shared-content/index.js, content/docs/shared-content/lr-notice.md
Enrollment pause notice. This notice is added to all LR pages in the docs.
https://neon-next-git-dprice-logical-replication-notice-neondatabase.vercel.app/docs/guides/logical-replication-guide
=> Logical replication notice

content/docs/guides/prisma-migrations.md, content/docs/guides/prisma.md, content/docs/sidebar.yaml
add doc on running migrations against Neon with Prisma
https://neon-next-git-orms-prisma-neondatabase.vercel.app/docs/guides/prisma-migrations
=> add doc on running migrations against Neon with Prisma

content/docs/guides/drizzle-migrations.md, content/docs/guides/migrations-drizzle.md, content/docs/serverless/serverless-driver.md, content/docs/sidebar.yaml
using Neon with Drizzle
https://neon-next-git-orms-drizzle-neondatabase.vercel.app/docs/guides/drizzle-migrations
=> using Neon with Drizzle 

src/components/pages/blog/blog-post-card/blog-post-card.jsx, src/components/pages/blog/blog-post-card/index.js, src/components/pages/blog/video-list/video-list.jsx, src/components/pages/blog/video-list/video-preview/index.js, src/components/pages/blog/video-list/video-preview/video-preview.jsx
This PR makes video previews  on the blog page smaller. 
[Context](https://www.notion.so/pixelpoint/e2e6b10fc7f2454b870414df8ed482a4?v=02b6fd5cea7647548ee73f4bb3a10fef&p=12f61abbaaa44cf89786189ab19b7a23&pm=c)
[Preview](https://neon-next-git-blog-page-video-preview-neondatabase.vercel.app/blog)
=> style: blog video preview updates

content/docs/guides/project-sharing-guide.md, content/docs/manage/projects.md
Mention that the account you share a project with can also share the project with other accounts.
=> Project sharing content updates

.gitignore, package.json, src/scripts/copy-docs-md.js
This PR adds a public/md/docs folder, allowing clients to open Markdown files from the website. This functionality was added at the request of the client.
[Preview example](https://neon-next-bpe7iise3-neondatabase.vercel.app/md/ai/ai-concepts.md)
=> chore: copy docs md

content/docs/guides/django.md
- Add note about using a recent driver version
- Use the same connection snippet we provide in the Neon console
- Reference Evan's Django blog post and sample app
Preview:
https://neon-next-git-dprice-update-django-content-neondatabase.vercel.app/docs/guides/django
=> Update Django content

src/components/shared/topbar/topbar.jsx
=> Update website banner to vercel integration GA

content/docs/reference/compatibility.md
We do not currently support event triggers due to superuser requirement. Add it to the compatibility section until we add support.
=> Mention event triggers in compatibility section

content/docs/security/soc2-compliance.md
SOC 2 reports are a Scale plan feature. Updated SOC 2 docs to reflect this change.
=> SOC 2 reports are a Scale plan feature

content/docs/connect/connect-postgres-gui.md
Verified that we can connect from Tableau
=> Add Tableau to supported clients list

content/docs/sidebar.yaml
Hyper drive is a caching solution. Move it under Caching.
=> Move Hyperdrive doc

content/docs/introduction/manage-billing.md
Preview:
https://neon-next-git-dprice-account-deletion-neondatabase.vercel.app/docs/introduction/manage-billing#deactivate-your-account
Re: Request for account deletion information in the docs.
https://neondb.slack.com/archives/C03ETHV2KD1/p1711392853989909
Deactivate account
=> Add account deactivation instructions

content/docs/introduction/about-billing.md, content/docs/introduction/billing-aws-marketplace.md, content/docs/introduction/manage-billing.md, content/docs/sidebar.yaml
Preview:
https://neon-next-git-dprice-aws-marketplace-neondatabase.vercel.app/docs/introduction/billing-aws-marketplace
AWS Market place card:
https://neon-next-git-dprice-aws-marketplace-neondatabase.vercel.app/docs/introduction/about-billing#manage-billing
=> Add AWS Marketplace content

src/components/pages/case-studies/hero/hero.jsx, src/components/shared/gradient-card/gradient-card.jsx, src/utils/api-posts.js
This pull request introduces functionality to add external URLs to case studies cards.
- open [preview](https://github.com/neondatabase/website/pull/1565)
- make sure that everything looks and works as expected
=> chore: add check external url for case studies

content/docs/guides/drizzle-migrations.md, content/docs/guides/prisma-migrations.md, content/docs/guides/sequelize.md, content/docs/guides/sqlalchemy-migrations.md, content/docs/sidebar.yaml
add doc for schema migrations in a sqlalchemy+Neon project
https://neon-next-git-frindle-guidessqlalchemy-neondatabase.vercel.app/docs/guides/sqlalchemy-migrations
=> add doc for schema migrations in a sqlalchemy+Neon project

content/docs/guides/hasura.md
Add information about the max PG connections in Hasura.
https://neon-next-git-dprice-hasura-max-connections-neondatabase.vercel.app/docs/guides/hasura#maximum-connections-configuration
=> Hasura max connections

content/docs/guides/rails-migrations.md, content/docs/sidebar.yaml
add draft for schema migration in a Neon/Rails project
https://neon-next-git-frindle-guidesrails-neondatabase.vercel.app/docs/guides/rails-migrations
=> add draft for schema migration in a Neon/Rails project

content/docs/guides/django-migrations.md, content/docs/sidebar.yaml
Doc on how to run Postgres migrations using Django
https://neon-next-git-frindle-guidesdjango-neondatabase.vercel.app/docs/guides/django-migrations
=> Add draft for django migrations

content/docs/guides/polyscale-integration.md, content/docs/guides/polyscale.md
Add note about serverless driver support with PolyScale.
=> Add note about serverless driver support with PolyScale

content/docs/guides/laravel-migrations.md, content/docs/sidebar.yaml
add doc for schema migrations w neon + laravel
https://neon-next-git-frindle-migrationslaravel-neondatabase.vercel.app/docs/guides/laravel-migrations
=> add doc for schema migrations w neon + laravel

content/docs/import/migrate-mysql.md, content/docs/manage/operations.md
Mention Operation status values in the Operation docs
+ minor unrelated update to import docs to fix an error.
=> Mention possible operation status values

src/components/pages/pricing/hero/hero.jsx, src/constants/links.js
Relates to https://github.com/neondatabase/cloud/issues/11104
This PR is a second part of https://github.com/neondatabase/cloud/issues/11104 initiative.
In the first PR https://github.com/neondatabase/cloud/pull/11593 I updated Console UI side to handle https://console.neon.tech/?upgrade=launch and https://console.neon.tech/?upgrade=scale
=> feat: update upgrade links

content/docs/reference/glossary.md
Terms:
https://neon-next-git-dprice-branch-terms-neondatabase.vercel.app/docs/reference/glossary#branch
https://neon-next-git-dprice-branch-terms-neondatabase.vercel.app/docs/reference/glossary#primary-branch
https://neon-next-git-dprice-branch-terms-neondatabase.vercel.app/docs/reference/glossary#root-branch
https://neon-next-git-dprice-branch-terms-neondatabase.vercel.app/docs/reference/glossary#non-primary-branch
https://neon-next-git-dprice-branch-terms-neondatabase.vercel.app/docs/reference/glossary#copy-on-write
=> Update branch-related glossary terms

content/docs/guides/polyscale-integration.md, content/docs/guides/polyscale.md
=> PolyScale notice

content/docs/reference/cli-install.md
=> Update binary path

content/docs/introduction/roadmap.md
Reported in https://twitter.com/zhzhng/status/1777813587811045532
=> Nit: Winter of 2024 has yet to come

content/docs/guides/vercel.md
https://neon-next-git-dprice-vercel-delete-update-neondatabase.vercel.app/docs/guides/vercel#manage-branches-created-by-the-integration
=> Update branch deletion instructions for Vercel

src/components/shared/topbar/topbar.jsx
=> Update topbar with GA.jsx

content/docs/guides/guides-intro.md, content/docs/guides/logical-replication-clickhouse.md, content/docs/guides/logical-replication-guide.md, content/docs/sidebar.yaml, public/images/technology-logos/clickhouse-logo.svg
https://neon-next-git-fork-ivoninskii-docs-replicat-ced47b-neondatabase.vercel.app/docs/guides/logical-replication-clickhouse
=> add guide about logical replication to clickhouse

content/docs/guides/guides-intro.md, content/docs/introduction.md
Add auth technology cards (Auth0 and Clerk)
- Guides page
- Introduction page
=> Add auth technology cards (Auth0 and Clerk)

content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md
Added this in two places:
- https://neon-next-git-bgrenon-freetier-egress-limit-neondatabase.vercel.app/docs/introduction/plans#allowances
- https://neon-next-git-bgrenon-freetier-egress-limit-neondatabase.vercel.app/docs/introduction/usage-metrics#data-transfers
=> Add Free Tier egress limit of 5 GiB per month to docs

content/docs/manage/organizations.md
https://neon-next-git-bgrenon-reinforce-orgs-paid-only-neondatabase.vercel.app/docs/manage/organizations
=> docs: emphasize paid users only for org private preview

content/docs/introduction/billing-aws-marketplace.md
https://neon-next-git-bgrenon-remove-aws-scale-note-neondatabase.vercel.app/docs/introduction/billing-aws-marketplace
=> docs: remove note limiting support to Scale

content/docs/guides/guides-intro.md, content/docs/guides/polyscale.md, content/docs/sidebar.yaml
https://neon-next-git-dprice-add-back-polyscale-neondatabase.vercel.app/docs/guides/polyscale
=> Add back PolyScale guide

src/components/shared/footer/status-badge/status-badge.jsx
Update fetchStatus to handle new changes in NeonStatus [NeonStatus](https://neonstatus.com/) API.
=> fix: update fetchStatus to handle new changes in NeonStatus API

content/docs/guides/branching-github-actions.md
Our GitHub Actions have seen some updates. Update our docs to reflect those changes.
=> Update GitHub Actions content to the latest

content/docs/manage/backups.md
Nightly Postgres Backups via GitHub Action
=> Add reference to community post about GitHub Action for backups

content/flow/index.md
=> chore: Update content

src/components/shared/code-block-wrapper/code-block-wrapper.jsx
**Describe what changes this pull request brings**
This PR brings fix for code blocks copy button and resolving https://github.com/neondatabase/website/issues/1649
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
**References**
Issue https://github.com/neondatabase/website/issues/1649
[Preview](https://neon-next-git-fix-copy-code-button-neondatabase.vercel.app/blog/what-you-get-when-you-think-of-postgres-storage-as-a-transaction-journal)
=> fix: code blocks copy button creates extra spacings

src/constants/seo-data.js, src/styles/highlighted-code.css
1. Edit meta title to include serverless postgres
2. Edit line number styling on code block to even across single-digit and double-digit lines.
=> Homepage fast-follows. Title and line numbers

content/docs/guides/partner-billing.md
Update incorrect branch data size limits
=> Update branch size limits in Partner section

content/changelog/2024-04-19.md, content/docs/get-started-with-neon/frameworks.md, content/docs/get-started-with-neon/languages.md, content/docs/get-started-with-neon/signing-up.md, content/docs/get-started-with-neon/why-neon.md, content/docs/guides/branching-intro.md, content/docs/manage/endpoints.md, content/docs/unused/branching-pitr.md
Minor edits, fix a few link issues, add missing cards to landing pages.
Fix LFC size percentage. It's 80-0%, not 50%.
=> docs: update links

content/docs/reference/compatibility.md
Add FDW to the compatibility section.
=> docs: mention fdw support

content/docs/sidebar.yaml
=> docs: remove duplicate toc item

content/docs/guides/auto-suspend-guide.md, content/docs/manage/endpoints.md, content/docs/reference/glossary.md
Paid plans can disable autosuspend + other minor edits
https://neon-next-git-dprice-autosuspend-update-neondatabase.vercel.app/docs/guides/auto-suspend-guide#autosuspend-limits
=> docs: autosuspend update

content/docs/get-started-with-neon/signing-up.md, content/docs/introduction.md, content/docs/sidebar.yaml
Remove "Day". Go with numbered headings for now.
=> docs: update get started titles

src/components/pages/doc/inkeep-trigger/inkeep-trigger.jsx, src/components/pages/doc/mobile-nav/mobile-nav.jsx, src/components/pages/doc/sidebar/sidebar.jsx
This pull request brings update for ai-chat button styles for docs
**References**
[Preview](https://neon-next-git-ai-chat-button-neondatabase.vercel.app/docs/introduction)
=> feat: update ai-chat button styles for docs

src/components/pages/case-studies/hero/hero.jsx, src/constants/seo-data.js
This pull request updates case-studies page subtitle
**References**
[Preview](https://neon-next-git-case-studies-subtitle-neondatabase.vercel.app/case-studies)
=> chore: update case-studies page subtitle

content/guides/next-upload-aws-s3.md
https://neon-next-ksvxar4yz-neondatabase.vercel.app/guides/next-upload-aws-s3
=> docs: show steps in How to upload to S3 in Next.js and save references in Postgres

content/flow/index.md
https://neon-next-git-dprice-flows-minor-revisions-neondatabase.vercel.app/flow
=> Branch workflows minor edits

content/docs/guides/outerbase.md
add early access note for Outerbase
=> docs: add early access note

content/docs/introduction/manage-billing.md
the 2nd result says "deactivate" but that does not make sense as we do not offer to restore the account.
=> docs: use delete instead of deactivate

src/app/layout.jsx, src/components/pages/doc/code-tabs/CodeTabsContext.jsx, src/components/pages/doc/code-tabs/code-tabs.jsx
Preview
<video src="https://github.com/neondatabase/website/assets/46300090/41576c03-0b97-4cd3-8206-f0b42af57e08" />
=> docs: switch code tabs everywhere based on the labels

content/docs/extensions/pg-extensions.md, src/components/pages/pricing/plans/data/plans.json
Adjust docs and Pricing page. "Custom extensions" is now an Enterprise-only feature.
=> docs: custom extension support

content/docs/guides/python.md
As requested by @petuhovskiy, it's a good to have an async guide for connecting to Postgres. I'm using [asyncpg](https://github.com/MagicStack/asyncpg) for the same.
=> docs: add asynchronous python guide

content/docs/guides/node.md
Currently, there is a `l` at the end of the version() which needs to be removed.
=> docs: update node.js guide

content/docs/guides/express.md, content/docs/sidebar.yaml
Preview:
https://neon-next-git-express-guide-neondatabase.vercel.app/docs/guides/express
=> docs: express with neon guide

content/docs/guides/neosync-anonymize.md, content/docs/guides/neosync-generate.md, content/docs/sidebar.yaml
add "new" tags for neosync guides
=> docs: add new tags for neosync guides

content/docs/get-started-with-neon/signing-up.md
- add shouldwrap tag
- add semicolon to statement
- minor revisions
=> docs: minor get started updates

content/docs/reference/cli-branches.md
To my understanding, this is less confusing.
=> Clarify term

next.config.js
Adds rewrite URL for the instant-postgres demo
=> chore: add rewrite

content/docs/connect/connection-latency.md, content/docs/guides/auto-suspend-guide.md, content/docs/manage/endpoints.md, content/docs/reference/glossary.md
- Add notes about restarting your compute for the latest updates if autosuspend is disabled
- Improve compute restart instructions. Provide cURL example and information about where to find the required parameters
=> docs: restart compute for latest updates

content/guides/next-server-actions.md
following Andy's guidelines on community guides
=> docs: follow community guides rules in /guides

content/docs/functions/introduction.md, content/docs/functions/window-lead.md, content/docs/sidebar.yaml
add doc for window function - lead
=> add doc for window function - lead

content/docs/manage/projects.md
=> docs: mention pg.new in the docs

src/components/pages/case-studies/hero/hero.jsx
This PR updates case studies page subtitle
[Preview](https://neon-next-git-update-case-studies-subtitle-neondatabase.vercel.app/case-studies)
=> chore: update case studies page subtitle

content/docs/guides/drizzle-migrations.md
Update Hono.js version in Drizzle Guide
=> docs: update drizzle guide

content/docs/manage/organizations.md
https://neon-next-git-bgrenon-psql-auth-orgs-neondatabase.vercel.app/docs/manage/organizations#passwordless-authentication
=> Add passwordless auth to org private preview page

content/docs/guides/vercel.md
Fix broken link in Vercel guide
=> docs: fix link in vercel guide

content/docs/functions/introduction.md, content/docs/functions/window-rank.md, content/docs/sidebar.yaml
=> doc on window function - rank

content/docs/functions/introduction.md, content/docs/functions/lower.md, content/docs/sidebar.yaml
add doc on postgres lower function for strings
=> add doc on postgres lower function for strings

content/docs/functions/introduction.md, content/docs/functions/trim.md, content/docs/sidebar.yaml
doc - postgres trim function for string
=> doc - postgres trim function for string

content/changelog/2024-06-28.md
Needs at least one H3 or the feed breaks
=> docs: added header to fix RSS

content/docs/introduction/manage-billing.md, content/docs/introduction/support.md
It was not clear how support plans are mapped to pricing plans.
=> docs: map support plans to pricing plans

content/guides/laravel-crud-api.md, content/guides/laravel-events-and-listeners.md, content/guides/laravel-livewire-blog.md, content/guides/laravel-livewire-simple-search.md, content/guides/laravel-livewire-todo-app.md, content/guides/laravel-multi-tenant-app.md, content/guides/laravel-zero-cli-todo-app.md
Preview link:
https://neon-next-git-fork-bobbyiliev-laravel-guides-2-neondatabase.vercel.app/guides
=> Adding a set of Laravel how to guides

content/docs/connect/connect-intro.md
Add a section to our Connect page for connecting from frameworks and languages
=> docs: update connect page

content/docs/guides/react.md, content/docs/sidebar.yaml
Preview: https://neon-next-git-react-neon-neondatabase.vercel.app/docs/guides/react
=> guide: Using Neon Postgres with React

content/docs/get-started-with-neon/production-checklist.md, content/docs/guides/integrations.md
=> docs: fix broken links

content/docs/guides/typeorm.md, content/docs/sidebar.yaml
Preview: https://neon-next-git-typeorm-neon-neondatabase.vercel.app/docs/guides/typeorm
=> docs: connecting to neon from typeorm

content/docs/get-started-with-neon/frameworks.md, content/docs/guides/neosync-generate.md, content/docs/guides/solid-start.md, content/docs/sidebar.yaml, public/images/technology-logos/solid-logo.svg
Preview: https://neon-next-git-solid-start-neon-neondatabase.vercel.app/docs/guides/solid-start
=> docs: neon with solidstart

content/docs/guides/integrations.md, content/docs/sidebar.yaml
Add TypeORM card and new tags.
=> docs: add typeorm card

src/components/pages/partners/collaboration/collaboration.jsx
Fix the Vercel/Retool Case Study links
=> Fix Partner Page Link

content/docs/ai/ai-concepts.md
=> Update ai-concepts.md to Correct Word Capitalization

content/docs/guides/branching-github-actions.md, content/docs/guides/neon-github-integration.md
Reverts neondatabase/website#1946
=> Revert "docs: add cards for example gh workflow apps"

content/docs/guides/branching-github-actions.md, content/docs/guides/neon-github-integration.md
minor change / non-technical
Add cards
=> docs: Add GH action example app cards

content/docs/extensions/pg_stat_statements.md, content/docs/reference/compatibility.md
Add information to our pg_stat_statements docs about statitics retention
=> docs: add note about stats retention

content/docs/introduction/monitor-usage.md, content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md, content/docs/reference/glossary.md
Add data transfer error message, minor tweaks
=> docs: data transfer updates

content/docs/guides/auth-clerk.md
small edit to auth-with-clerk doc
=> small edit to auth-with-clerk doc

content/docs/introduction/usage-metrics.md
- Mention how to upgrade your plan if you hit the **Data transfer** limit on Free Tier
- Mention how you can monitor data transfer
https://neon-next-git-dprice-data-transfer-neondatabase.vercel.app/docs/introduction/usage-metrics#data-transfer
=> docs: update data transfer docs

content/docs/guides/bemi.md, content/docs/guides/logical-replication-airbyte.md, content/docs/guides/logical-replication-clickhouse.md, content/docs/guides/logical-replication-concepts.md, content/docs/guides/logical-replication-decodable.md, content/docs/guides/logical-replication-fivetran.md, content/docs/guides/logical-replication-guide.md, content/docs/guides/logical-replication-kafka-confluent.md, content/docs/guides/logical-replication-materialize.md, content/docs/guides/logical-replication-neon.md, content/docs/guides/logical-replication-postgres.md
remove LR notice. reopening beta.
=> docs: remove LR notice

content/docs/manage/email-signup.md
Add instructions for removing you email login
=> docs: remove email login

content/docs/introduction/monitor-usage.md
Re https://github.com/neondatabase/cloud/issues/15773
=> Update egress from GiB to GB

content/changelog/2024-07-05.md, content/changelog/2024-07-19.md, content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md, content/docs/reference/glossary.md
=> docs: update egress

content/docs/guides/logical-replication-clickhouse.md
Preview:
https://neon-next-git-fork-ivoninskii-docs-update-c-08c7b5-neondatabase.vercel.app/docs/guides/logical-replication-clickhouse
=> docs: update doc about data replication to clickhouse

content/docs/guides/neon-github-integration.md
It will be available to all users.
=> docs: remove GitHub app early access note

content/docs/introduction/support.md
preview (see note below table)
https://neon-next-git-dprice-add-discord-support-note-neondatabase.vercel.app/docs/introduction/support
=> docs: Add Discord Support note

content/docs/guides/neon-github-integration.md, content/docs/sidebar.yaml
Remove GH integration coming soon tags
=> docs: rm coming soon

content/docs/reference/cli-create-app.md
Add link to YT video about create-app
=> docs: add video link for create-app

content/docs/guides/protected-branches.md, content/docs/manage/branches.md, content/docs/reference/glossary.md, content/docs/security/security-overview.md
https://neon-next-git-dprice-update-prot-branch-password-neondatabase.vercel.app/docs/guides/protected-branches
=> docs: update protected branches docs

content/docs/guides/logical-replication-airbyte-snowflake.md, content/docs/guides/logical-replication-airbyte.md, content/docs/guides/logical-replication-clickhouse.md, content/docs/guides/logical-replication-decodable.md, content/docs/guides/logical-replication-fivetran.md, content/docs/guides/logical-replication-guide.md, content/docs/guides/logical-replication-kafka-confluent.md, content/docs/guides/logical-replication-materialize.md, content/docs/guides/logical-replication-neon.md, content/docs/guides/logical-replication-postgres.md
Outbound logical replication updates (Neon Postgres to Postgres) based on review feedback from James.
=> docs: logical replication updates

content/docs/guides/django.md
=> fix typo in django.md

content/docs/guides/logical-replication-airbyte-snowflake.md, content/docs/guides/logical-replication-airbyte.md, content/docs/guides/logical-replication-clickhouse.md, content/docs/guides/logical-replication-decodable.md, content/docs/guides/logical-replication-fivetran.md, content/docs/guides/logical-replication-kafka-confluent.md, content/docs/guides/logical-replication-materialize.md, content/docs/guides/logical-replication-postgres.md
Update create role instructions
=> docs: update create role instructions

src/components/pages/doc/menu/item/item.jsx, src/components/shared/header/header-wrapper/header-wrapper.jsx, src/components/shared/inkeep-trigger/inkeep-trigger.jsx
This PR brings new docs sidebar fixes
- add icon for docs sidebar external links
- fix sticky header glitch
- fix inkeep trigger chat fix body lock scroll in mobile docs nav #1953
[Preview](https://neon-next-git-docs-sidebar-fixes-neondatabase.vercel.app/docs/introduction)
=> feat: docs sidebar fixes

content/docs/connect/choose-connection.md, content/docs/guides/knex.md, content/docs/guides/neon-github-integration.md, content/docs/introduction/roadmap.md, content/docs/sidebar.yaml
Add card for Cloudflare Pages sample app
=> docs: add example workflows repo

content/docs/connect/choose-connection.md
For docs task [74619920](https://github.com/orgs/neondatabase/projects/25/views/1?pane=issue&itemId=74619920)
=> Clarify Neon-side pooling on connections page

content/docs/guides/logical-replication-prisma-pulse.md
Hey Daniel, just adding some tracking for our own links. Thanks!
=> Add UTM tracking to Prisma links

content/guides/fastapi-jwt.md, content/guides/fastapi-overview.md, content/guides/github-codespaces-neon-branching.md, content/guides/laravel-websockets.md
Preview:
https://neon-next-git-fork-bobbyiliev-laravel-guides-4-neondatabase.vercel.app/guides
=> Adding a set of Laravel and FastAPI how to guides 

content/docs/introduction/usage-metrics.md, content/docs/reference/glossary.md
https://neon-next-git-dprice-add-compute-faqs-neondatabase.vercel.app/docs/introduction/usage-metrics#compute-faqs
=> docs: add compute hour faqs

content/docs/manage/orgs-project-transfer.md
Related to #15179 - fix py and bash transfer scripts
=> Related to #15179 - fix py and bash transfer scripts

content/docs/guides/astro.md
Fix typo in Astro docs (stringiify -> stringify)
=> Fix typo in Astro docs (stringiify -> stringify)

content/docs/guides/branch-restore.md
Add note about managing backup branches
=> docs: Add backup branch note

content/docs/sidebar.yaml
preview:
- https://neon-next-git-bgrenon-remove-singlepage-nav-neondatabase.vercel.app/docs/introduction/regions
- https://neon-next-git-bgrenon-remove-singlepage-nav-neondatabase.vercel.app/docs/introduction/support
- https://neon-next-git-bgrenon-remove-singlepage-nav-neondatabase.vercel.app/docs/introduction/status
- https://neon-next-git-bgrenon-remove-singlepage-nav-neondatabase.vercel.app/docs/introduction/roadmap
=> Remove single page secondary navigation

src/components/pages/contact-sales/hero/contact-form/contact-form.jsx
This PR brings required field of company size in Contact Sales Form
Preview is [here](https://neon-next-git-add-required-field-to-the-form-neondatabase.vercel.app/contact-sales)
=> feat: add required field in Contact Sales Form

src/components/pages/doc/mobile-nav/mobile-nav.jsx, src/components/shared/inkeep-trigger/inkeep-trigger.jsx
This PR brings fix for "Ask Neon AI" button on mobile docs menu
Preview is [here](https://neon-next-git-fix-ask-ai-button-on-mobile-neondatabase.vercel.app/docs/introduction)
<details>
<summary>Design</summary>
</details>
=> feat: fix Ask Neon AI button on mobile

src/constants/menus.js
The PR brings the minor fix for typo in the header menu Features:
> Autoscaling
Automatic instance sizin -> Automatic instance sizing
=> chore: minor typo

content/docs/introduction/manage-billing.md, content/docs/manage/projects.md
New section:
https://neon-next-git-dprice-stop-monthly-charges-neondatabase.vercel.app/docs/introduction/manage-billing#how-to-prevent-further-monthly-charges-to-your-account
Delete a project note:
https://neon-next-git-dprice-stop-monthly-charges-neondatabase.vercel.app/docs/manage/projects#delete-a-project
=> docs: how to stop monthly charges

content/docs/guides/integrations.md, content/docs/guides/logical-replication-guide.md, content/docs/guides/sequin.md, content/docs/sidebar.yaml
This PR updates the Sequin (sequinstream.com) integration guide in the Neon docs.
=> docs: update sequin integration guide

content/guides/spring-boot-flyway.md, content/guides/spring-boot-hibernate.md
Preview:
https://neon-next-git-fork-bobbyiliev-guides-5-neondatabase.vercel.app/guides
=> Adding a set of Spring Boot how to guides

content/docs/import/import-from-azure-postgres.md, content/docs/import/import-intro.md, content/docs/sidebar.yaml
Add doc on migrating from Azure Postgres to Neon
=> Add doc on migrating from Azure Postgres to Neon

content/docs/connect/connection-pooling.md
- Update reserved superuser connection number
- General revisions
=> docs: connection pooling edits

content/docs/import/migrate-mssql.md, content/docs/sidebar.yaml
add doc on import from mssql to postgres
=> add doc on import from mssql to neon

content/docs/guides/sqlalchemy.md
=> docs: add sqlalchemy error info

content/docs/guides/logical-replication-alloydb.md, content/docs/guides/logical-replication-aurora-to-neon.md, content/docs/guides/logical-replication-cloud-sql.md, content/docs/guides/logical-replication-neon-to-neon.md, content/docs/guides/logical-replication-postgres-to-neon.md, content/docs/guides/logical-replication-postgres.md, content/docs/guides/logical-replication-rds-to-neon.md, content/docs/guides/logical-replication-tips.md, content/docs/guides/sequin.md, content/docs/import/import-from-azure-postgres.md
add note about FOR ALL TABLES in logical replication
=> docs: add note about FOR ALL TABLES

content/guides/flask-database-migrations.md, content/guides/flask-overview.md
Preview:
https://neon-next-git-fork-bobbyiliev-guides-6-neondatabase.vercel.app/guides
=> Adding a set of Flask how to guides

content/docs/import/import-from-azure-postgres.md, content/docs/import/import-from-digital-ocean.md, content/docs/import/import-from-firebase.md, content/docs/import/import-from-render.md, content/docs/import/import-from-supabase.md, content/docs/import/migrate-mssql.md, content/docs/sidebar.yaml
Add Postgres extensions to main sidebar
Add new tags for new import guides
=> docs: add extensions to sidebar, new tags

content/guides/authors/data.json, content/guides/full-text-search.md
Preview:
https://neon-next-git-fork-vkarpov15-vkarpov15-guid-55137c-neondatabase.vercel.app/guides/full-text-search
=> docs: add full text search guide

content/docs/guides/django-migrations.md, content/docs/guides/sqlalchemy-migrations.md
=> docs: add migration connection note

src/app/blog/(index)/page.jsx, src/constants/blog.js, src/utils/api-posts.js
This PR adds workflows as featured posts
Preview is [here](https://neon-next-git-add-workflows-as-featured-neondatabase.vercel.app/blog)
=> feat: add workflows as featured posts

content/docs/import/import-sample-data.md
=> docs: correct connection string for postgres_air

src/components/pages/blog-post/subscribe-form/subscribe-form.jsx
This PR adds id `#subscribe-form` to Subscribe form on Blog page
=> feat: add anchor to subscribe form

src/components/pages/blog-post/subscribe-form/subscribe-form.jsx
This PR passes className to tag `section` instead of `div`
=> fix: subscribe form className

content/docs/guides/logical-replication-alloydb.md, content/docs/import/migrate-schema-only.md
https://neon-next-git-dprice-replicate-data-updates-neondatabase.vercel.app/docs/guides/logical-replication-alloydb#prepare-your-database-schema
=> docs: update alloydb, schema only instructions

src/components/pages/pricing/faq/faq.jsx, src/components/pages/pricing/features/row/row.jsx, src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/data/plans.json, src/components/shared/container/container.jsx
This pull request brings the updates for Pricing page:
- updated container size for hero
- added extra links to Business Plan
- removed AWS icons
- added `id` for Q in FAQ
[Preview](https://neon-next-git-minor-pricing-updates-neondatabase.vercel.app/pricing)
=> feat: minor pricing updates

content/docs/introduction/regions.md
Azure is only available for EA & waitlist users
=> docs: mention ea program for azure

content/docs/guides/datadog.md, content/docs/reference/terraform.md, content/docs/sidebar.yaml
Add a Terraform provider page
https://neon-next-git-dprice-add-terraform-page-neondatabase.vercel.app/docs/reference/terraform
=> docs: add terraform page

content/docs/extensions/pg-extensions.md
Add note about PG17 extension support
=> docs: add note about pg17 extension support

content/docs/connect/connection-errors.md, content/docs/manage/email-signup.md
- Add docs for the `Remaining connection slots are reserved` error
- Add note about logging out/in if you can't change your email address because it's greyed-out
=> docs: remaining connection slots are reserved

src/components/shared/topbar/topbar.jsx
Reverts neondatabase/website#2262
=> Topbar banner: promote Neon Deploy

src/styles/ticket.css
This PR fixes the ticket's mobile version
https://neon-next-git-deploy-mobile-fix-neondatabase.vercel.app/tickets/vannyle
=> fix: ticket mobile version

content/use-cases/dev-test.md
This PR brings the CTA block to the use case `dev-test`
=> feat: add cta to dev-for-rds

content/docs/get-started-with-neon/production-readiness.md, content/docs/get-started-with-neon/why-neon.md, content/docs/introduction/roadmap.md
- fix link
- add fdw to raodmap
- tidy terminology
=> docs: misc doc updates

content/docs/introduction/manage-billing.md, content/docs/reference/terraform.md
- add a card at the top
- updates for recent UI changes
=> docs: update manage billing docs

src/app/tickets/[handle]/edit/page.jsx, src/app/tickets/[handle]/page.jsx, src/pages/api/og.jsx
1. Too much information was being included in the URL to request the og image
2. The base64 encoded image2 in og-images.jsx is corrupted, breaking image previews when user selects that background style. I temporarily switched it to use image4 in the image instead
=> Deploy: Minor bug fixes

src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/data/plans.json
This PR brings chore update for pricing plans tooltips
[Preview](https://neon-next-git-pricing-page-text-neondatabase.vercel.app/pricing)
=> chore: update pricing plans tooltips

content/docs/README.md, content/docs/manage/platform.md, content/docs/sidebar.yaml
preview:
https://neon-next-git-bgrenon-platform-index-neondatabase.vercel.app/docs/manage/platform
=> Add platform landing/index page to docs

content/docs/guides/integrations.md
Add Datadog integrations card to the Integrations page
=> docs: add datadog integrations cards

src/components/pages/pricing/hero/hero.jsx
=> docs: 10 project update for free

content/docs/guides/project-collaboration-guide.md, content/docs/introduction/plans.md, content/docs/manage/projects.md, src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/data/plans.json
- more pricing page updates
- related doc updates
=> docs: free plan limit updates

content/docs/guides/auth-authjs.md, content/docs/guides/datadog.md, content/docs/guides/logical-replication-alloydb.md, content/docs/guides/logical-replication-cloud-sql.md, content/docs/guides/logical-replication-estuary-flow.md, content/docs/guides/logical-replication-neon-to-neon.md, content/docs/guides/logical-replication-prisma-pulse.md, content/docs/guides/logical-replication-rds-to-neon.md, content/docs/import/migrate-from-azure-postgres.md, content/docs/import/migrate-from-digital-ocean.md, content/docs/import/migrate-from-firebase.md, content/docs/import/migrate-from-render.md, content/docs/import/migrate-from-supabase.md, content/docs/import/migrate-mssql.md, content/docs/introduction/roadmap.md, content/docs/reference/feeds.md, content/docs/sidebar.yaml
Clear new tags, add one new tag
=> Clear new tags

content/docs/introduction/billing-aws-marketplace.md, content/docs/introduction/manage-billing.md
=> docs: revise emandates info

content/docs/get-started-with-neon/signing-up.md
https://neon-next-git-bgrenon-playingwithneon-library-card-neondatabase.vercel.app/docs/get-started-with-neon/signing-up
=> Add infoblock to playing with neon page

content/docs/postgresql/postgres-upgrade.md
preview:
https://neon-next-git-bgrenon-psql-pg17-neondatabase.vercel.app/docs/postgresql/postgres-upgrade
=> Adding note about upgrading psql client when upgrading to PG17

content/docs/get-started-with-neon/query-with-neon-sql-editor.md
SQL Editor AI features open to all users. Remove EA label.
=> docs: sql editor ai features open

src/components/pages/about/investors/investors.jsx
This pull request brings a minor update on About us page
> CEO at GitHub >>  Former CEO at GitHub
=> chore: minor update for about us page

content/postgresql/postgresql-tutorial/postgresql-grouping-sets.md
=> Grammar fix

content/docs/reference/terraform.md
Changed "please contact the the project maintainers" -> "please contact the project maintainers"
=> fix(docs): correct typo in terraform.md

content/docs/guides/trigger-serverless-functions.md, content/docs/sidebar.yaml
=> docs: minor revisions

content/docs/guides/datadog.md
- Datadog Beta for Business plan users
- Free of charge for the Beta period
=> docs: datadog beta notice

src/app/actions.js
This PR returns the initial getReferrer function, which being used for home page
=> fix: return initial getReferrer function

content/docs/guides/project-collaboration-guide.md, content/docs/manage/branches.md, content/docs/manage/endpoints.md, content/docs/manage/orgs-manage.md, content/docs/manage/platform.md
**Invite emails being sent to spam updates:**
https://neon.tech/docs/manage/orgs-manage#invite-members
https://neon.tech/docs/manage/orgs-manage#invite-collaborators
https://neon.tech/docs/guides/project-collaboration-guide#invite-collaborators
**Branch passwords not reset at creation:**
https://neon.tech/docs/manage/branches#create-a-branch
**No space left on device:**
https://neon.tech/docs/manage/endpoints#no-space-left-on-device
**Compute not suspending:**
https://neon.tech/docs/manage/endpoints#compute-is-not-suspending
=> Doc support updates 2024 10 26

content/docs/guides/auth-clerk.md
A few small updates to the Neon / Clerk integration guide.
=> docs(guide): Update Clerk integration guide

src/components/pages/doc/menu/icon/icon.jsx, src/icons/docs/sidebar/workflows.inline.svg
This PR brings workflows icon for docs sidebar
=> chore: add workflows icon for docs sidebar

src/app/(home-page)/page.jsx
Reference: https://developers.google.com/search/docs/appearance/site-names#website
Why:  _Fixing _
=> SEO: Add WebSite json+ld to homepage

src/constants/menus.js
=> Add Trust Center Footer Link

src/utils/api-posts.js
Increase the number of fetched case studies to 40
=> Fix: more case studies

content/docs/guides/nuxt.md
Add missing step in Nuxt guide
=> docs: update nuxt guide for missing step

content/guides/vercel-sdk-migration.md, src/components/pages/doc/detail-icon-cards/detail-icon-cards.jsx, src/components/pages/doc/detail-icon-cards/images/drizzle.inline.svg
Preview: https://neon-next-ojmti29k4-neondatabase.vercel.app/guides/vercel-sdk-migration
=> docs: add vercel postgres sdk migration

content/docs/guides/neon-private-access.md
For the beta we added us-west-2, ap-southeast-1, and ap-southeast-2.
=> Add remaining prod regions to Neon Private Access documentation.

content/use-cases/database-per-tenant.md
This PR bring chore fix for Database Per User page last update https://github.com/neondatabase/website/pull/2419
[Preview](https://neon-next-git-database-per-tenant-page-neondatabase.vercel.app/use-cases/database-per-tenant)
=> chore: update database-per-tenant

content/docs/functions/introduction.md, content/docs/functions/json_table.md, content/docs/sidebar.yaml
- Add [JSON_TABLE()](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-TABLE) guide to Postgres functions
=> docs: add json_table

content/docs/guides/neon-authorize.md, content/postgresql/postgresql-administration/postgresql-row-level-security.md, src/components/pages/doc/sidebar/sidebar.jsx, src/components/shared/content/content.jsx, src/components/shared/header/header.jsx, src/components/shared/logo/logo.jsx
https://neon-next-git-bgrenon-cta-postgres-tutorial-neondatabase.vercel.app/postgresql/postgresql-administration/postgresql-row-level-security
=> docs: added cta

content/docs/security/security-overview.md
Currently the security documentation only shows AWS related setup, I've added Azure to it as well.
=> Update security docs with azure details

content/postgresql/postgresql-getting-started/install-postgresql-linux.md, content/postgresql/postgresql-getting-started/install-postgresql-macos.md, content/postgresql/postgresql-getting-started/install-postgresql.md
This pull request includes updates to the PostgreSQL installation guides for Linux, macOS, and general installation. The changes primarily focus on adding a call-to-action (CTA) for running PostgreSQL in the cloud.
Updates to PostgreSQL installation guides:
* [`content/postgresql/postgresql-getting-started/install-postgresql-linux.md`](diffhunk://#diff-4e5f6faac54c16c71b31ecd27be13d2298a9a983f581282cb0077d0b86c4d2a0R19-R20): Added a CTA for running PostgreSQL in the cloud with a free plan from Neon.
* [`content/postgresql/postgresql-getting-started/install-postgresql-macos.md`](diffhunk://#diff-446c0eb6118cba552978ed646e81857adbe5043d17455ca213689882c6fbfed2R19-R20): Included a CTA for cloud PostgreSQL with a free plan from Neon.
* …
=> PGT Content Updates

content/docs/security/security-reporting.md, package-lock.json, package.json
Since we launched a bb program, we should mention this in the docs.
=> Update security-reporting.md - mention the bugbounty program

content/docs/guides/prisma.md, package-lock.json, package.json
Preview: https://neon-next-git-prisma-fetch-neondatabase.vercel.app/docs/guides/prisma#use-the-neon-serverless-driver-with-prisma
=> docs: document use of query over fetch on edge with Prisma

content/docs/get-started-with-neon/frameworks.md, content/docs/get-started-with-neon/orms.md, content/docs/guides/drizzle.md, content/docs/introduction.md, content/docs/sidebar.yaml, package-lock.json, package.json
Preview: https://neon-next-git-drizzle-edge-neondatabase.vercel.app/docs/guides/drizzle
=> docs: document use of query over fetch on edge with Drizzle

content/docs/get-started-with-neon/connect-neon.md
Add .NET connection example to Getting started
=> docs: add net connect example

src/middleware.js
This PR refactors logic in middleware:
- define the protected routes
- check authenticated users in protected routes
=> fix: middleware logic

src/components/pages/pricing/hero/data/plans.json, src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/data/plans.json, src/components/pages/pricing/plans/table/table.jsx
Relates to https://linear.app/neondb/issue/GRW-290/experiment-build
Small events refactoring in order to setup experiment more properly.
=> refactor: restruct posthog events

content/docs/connect/connect-securely.md, content/docs/connect/connection-latency.md, content/docs/functions/math-random.md
Updated guides with latest postgres 17 features
- [`random()`](https://neon-next-git-fork-dhanushreddy291-update-d-a25598-neondatabase.vercel.app/docs/functions/math-random) function
-  [connect-securely](https://neon-next-git-fork-dhanushreddy291-update-d-a25598-neondatabase.vercel.app/docs/connect/connect-securely#optimizing-connection-latency-with-sslnegotiation)
=> docs: update existing docs with postgres 17 features

content/docs/functions/introduction.md, content/docs/functions/json.md, content/docs/functions/json_exists.md, content/docs/functions/json_query.md, content/docs/functions/json_scalar.md, content/docs/functions/json_serialize.md, content/docs/functions/json_value.md, content/docs/sidebar.yaml, content/guides/neon-github-actions-authomated-branching.md, content/postgresql/postgresql-tutorial/postgresql-merge.md, content/postgresql/sidebar.yaml
- Add new Postgres functions: 
- [JSON()](https://neon-next-git-fork-dhanushreddy291-add-docs-697bc0-neondatabase.vercel.app/docs/functions/json)
- [JSON_SCALAR()](https://neon-next-git-fork-dhanushreddy291-add-docs-697bc0-neondatabase.vercel.app/docs/functions/json_scalar)
- [JSON_SERIALIZE()](https://neon-next-git-fork-dhanushreddy291-add-docs-697bc0-neondatabase.vercel.app/docs/functions/json_serialize)
- [JSON_EXISTS()](https://neon-next-git-fork-dhanushreddy291-add-docs-697bc0-neondatabase.vercel.app/docs/functions/json_exists)
- [JSON_QUERY()](https://neon-next-git-fork-dhanushreddy291-add-docs-697bc0-neondatabase.vercel.app/docs/functions/json_query)
- [JSON_VALUE()](https://neon-next-git-fork-dhanushreddy291-add-docs-697bc0-neondatabase.vercel.app/docs/functions/json_value)
- …
=> docs: add new postgres functions

content/postgresql/postgresql-getting-started/install-postgresql-linux.md
Added missing 'sixth' and also changed the following words
=> docs: fixed typo (missing sixth)

src/constants/menus.js
This PR updates Variable page text in header menu
[Preview](https://neon-next-git-variable-page-menu-neondatabase.vercel.app/variable-load)
=> chore: update Variable page text in header menu

content/docs/ai/ai-intro.md
Revise AI section to include the ai agent use case for Neon and supported interfaces
=> docs: update ai docs for agents

content/docs/guides/autoscaling-guide.md, content/docs/guides/branch-promote.md, content/docs/guides/branching-neon-api.md, content/docs/guides/logical-replication-concepts.md, content/docs/guides/logical-replication-estuary-flow.md, content/docs/guides/neon-authorize-firebase-gcp.md, content/docs/guides/protected-branches.md, content/docs/guides/scale-to-zero-guide.md, content/docs/guides/schema-diff-tutorial.md, content/docs/guides/stepzen.md, content/docs/introduction/autoscaling.md, content/docs/introduction/point-in-time-restore.md, content/docs/introduction/regions.md, content/docs/manage/branches.md, content/docs/manage/endpoints.md, content/docs/manage/projects.md, content/docs/postgresql/postgres-upgrade.md, content/docs/reference/cli-projects.md, content/docs/unused/branch-refresh.md
more compute size updates
other UI changes
=> docs: more compute size updates

content/docs/use-cases/saas-apps.md, content/use-cases/postgres-for-saas.md, src/components/pages/pricing/hero/data/plans.json, src/components/pages/pricing/plans/data/plans.json
- compute size updates for the pricing page
- new use case content
=> docs: website compute size updates

content/docs/connect/connection-errors.md
Query wait timeout
-  https://neon.zendesk.com/agent/tickets/4515
And request not authorized error
- https://neon.zendesk.com/agent/tickets/4513
=> docs: query wait timeout error

content/guides/drizzle-local-vercel.md
Preview - https://neon-next-git-local-drizzle-vercel-neondatabase.vercel.app/guides/drizzle-local-vercel
=> guide: Drizzle with Local and Serverless Postgres

content/guides/document-store.md
Document Store using JSONB in Postgres: A step-by-step guide describing how to use Postgres as a document store using JSONB
=> docs: add document store guide

content/guides/local-development-with-neon.md
- add prisma and drizzle to local development guide
https://neon-next-git-fork-dhanushreddy291-add-docs-99c3c4-neondatabase.vercel.app/guides/local-development-with-neon
=> docs: add prisma and drizzle to local dev guide

src/app/variable-load/page.jsx, src/components/pages/variable/efficiency/efficiency.jsx, src/components/pages/variable/hero/hero.jsx, src/components/pages/variable/load/load.jsx, src/components/pages/variable/section/section.jsx
Testing more focused messaging for the variable traffic page 
[Preview](https://neon-next-git-carlotas19-patch-3-neondatabase.vercel.app/variable-load)
=> chore: update Variable Load page

content/use-cases/dev-test.md, src/components/shared/anchor-heading/anchor-heading.jsx, src/components/shared/cta-block/cta-block.jsx
Adds link to dev/test guide in docs
Retouches messaging
[Preview](https://neon-next-git-carlotas19-patch-2-neondatabase.vercel.app/use-cases/dev-test)
=> chore: update Dev/Test guide

content/docs/introduction/billing-azure-marketplace.md, content/docs/manage/orgs-project-transfer.md
Preview:
https://neon-next-git-dprice-project-transfer-azure-neondatabase.vercel.app/docs/introduction/billing-azure-marketplace#transfer-existing-neon-projects-to-an-azure-created-neon-organization
=> docs: project transfer azure

content/changelog/2024-12-20.md, content/docs/reference/cli-install.md
https://neon-next-git-docs-changelog-2024-12-20-neondatabase.vercel.app/docs/changelog/2024-12-20
=> docs: changelog 2024-12-20

content/guides/local-development-with-neon.md
https://neon-next-git-fork-dhanushreddy291-add-docs-99c3c4-neondatabase.vercel.app/guides/local-development-with-neon
#2690
=> docs: add note on adding hosts file

src/components/pages/contact-sales/hero/case-studies/case-studies.jsx, src/components/pages/contact-sales/hero/case-studies/index.js, src/components/pages/contact-sales/hero/case-studies/slider.css, src/components/pages/contact-sales/hero/case-studies/style.css, src/components/pages/contact-sales/hero/contact-form/contact-form.jsx, src/components/pages/contact-sales/hero/hero.jsx, tailwind.config.js
This PR updates Contact Sales page layout
[Preview](https://neon-next-git-contact-sales-page-neondatabase.vercel.app/contact-sales)
=> feat: update Contact Sales page layout

content/docs/guides/branching-intro.md, content/docs/guides/neon-features.md, content/docs/sidebar.yaml
this can be done via the ui now using branch reset, branch restore, and set as default
=> docs: drop branch promote guide

content/docs/manage/orgs-project-transfer.md, content/postgresql/postgresql-triggers/postgresql-event-trigger.md
- org to org transfer limitation
- add note to PostgreSQL Tutorial event trigger page
=> docs: add note about org to org transfer

src/constants/menus.js
This PR brings the header copy updates under `Use cases` tab
> **SaaS Apps**
Build faster with Neon
> 
> **Variable Traffic**
Scale up/down automatically
> 
> **Database per Tenant**
Grow to thousands of tenants
> 
> **Dev/Test**
For ephemeral environments
> 
> **Agents**
A database backend for agents
>
=> chore: update header dropdown copy

content/docs/manage/api-keys.md, content/docs/manage/orgs-api.md, src/components/pages/careers/jobs-list/jobs-list.jsx
Revised key types to a table view to make it easier to scan. Previews:
https://neon-next-git-bgrenon-project-scoped-api-cl-d2cc2c-neondatabase.vercel.app/docs/manage/api-keys
https://neon-next-git-bgrenon-project-scoped-api-cl-d2cc2c-neondatabase.vercel.app/docs/manage/orgs-api#create-api-keys
=> Clarify API key types (who can create, and how validity works)

content/docs/manage/accounts.md
@michrome see revised wording here:
https://neon-next-git-bgrenon-remove-180-neondatabase.vercel.app/docs/manage/accounts#deleting-your-account
=> Remove specific timeframe from account suspend period after delete

content/docs/introduction/billing-aws-marketplace.md
=> docs: update aws billing

content/docs/guides/partner-consumption-limits.md, content/docs/guides/partner-consumption-metrics.md, content/docs/introduction/monitor-usage.md
https://github.com/neondatabase/cloud/issues/22510
=> docs: remove get projects for consumption

content/postgresql/postgresql-tutorial/postgresql-any.md
=> PGT: Fix `any` example query

content/docs/guides/neon-private-networking.md
Update production endpoints that support shared DNS 
Ref: https://github.com/neondatabase/cloud/issues/22809
=> Update production endpoints which support shared dns

content/changelog/2025-01-17.md
=> docs: remove pooled connection item

src/app/(docs)/ai-chat/page.jsx, src/app/postgresql/layout.jsx, src/components/pages/doc/sidebar/sidebar.jsx, src/components/shared/header/header.jsx, src/components/shared/inkeep-trigger/inkeep-trigger.jsx, src/components/shared/layout/layout.jsx, src/components/shared/mobile-menu/mobile-menu.jsx, src/lib/inkeep-settings.js
This PR adds `Changelog` filter to inkeep Docs search
[Preview](https://neon-next-git-inkeep-changelog-filter-neondatabase.vercel.app/docs/changelog)
=> feat: add Changelog filter to inkeep Docs search

content/docs/guides/aws-lambda.md
Update aws-lambda guide (https://neon-next-git-fork-dhanushreddy291-update-d-a81e61-neondatabase.vercel.app/docs/guides/aws-lambda)
Uses existing connection now (For warm invocations), verified on Cloudwatch Logs
=> docs: update code in aws-lamda guide to use existing connection

content/docs/guides/partner-consumption-metrics.md
preview:
https://neon-next-git-dprice-mention-token-bucket-neondatabase.vercel.app/docs/guides/partner-consumption-metrics#what-is-the-the-rate-limit-for-neons-consumption-apis
=> docs: mention token bucket

content/docs/introduction/support.md
- update Support channel mapping
- added new Enterprise Support plan
=> Update Support page

content/docs/guides/neon-auth.md, content/docs/guides/neon-identity.md, content/docs/introduction/roadmap.md, content/docs/sidebar.yaml
https://neon-next-git-bgrenon-rename-identity-neondatabase.vercel.app/docs/guides/neon-auth
=> Rename Neon Identity to Neon Auth + best practice around foreign keys

content/docs/guides/branch-archiving.md, content/docs/introduction/plans.md
Preview:
Plans updated to 5000 per project:
https://neon-next-git-docs-unarchived-branch-limits-neondatabase.vercel.app/docs/introduction/plans#launch
https://neon-next-git-docs-unarchived-branch-limits-neondatabase.vercel.app/docs/introduction/plans#scale-plan-allowances
Unarchived branch limit added, archive criteria updated:
https://neon-next-git-docs-unarchived-branch-limits-neondatabase.vercel.app/docs/guides/branch-archiving
https://neon-next-git-docs-unarchived-branch-limits-neondatabase.vercel.app/docs/guides/branch-archiving#unarchiving-a-branch
=> docs: unarchived branch limits

content/docs/manage/azure.md
Added other existing Azure examples for Neon on Azure page.
=> docs: Update Azure examples

src/app/blog/(index)/category/[slug]/page.jsx, src/components/pages/blog/blog-nav-link/blog-nav-link.jsx, src/components/pages/blog/blog-post-card/blog-post-card.jsx
This PR brings hotfixes for Blog index page, updated with https://github.com/neondatabase/website/pull/2817
[Preview](https://neon-next-git-blog-index-page-fixes-neondatabase.vercel.app/blog)
=> fix: hotfixes for Blog index pages styles

content/docs/reference/glossary.md
Request: [#20914](https://github.com/neondatabase/cloud/issues/20914)
=> Add Neon Org term to glossary

src/app/use-cases/[slug]/page.jsx
Hotfix for broken use-cases pages 
Preview
=> fix: broken import for use-cases

content/docs/sidebar.yaml
move under development. we'll be adding more under workflows, development related.
=> docs: move workflows up in sidebar

content/docs/introduction/regions.md, content/docs/introduction/roadmap.md
=> docs: add new region

src/components/shared/latency-calculator/latency-calculator.jsx
https://github.com/user-attachments/assets/a4b252d9-13b3-48b9-9fa9-b08ea2f555d0
=> fix(styles): latency calculator reflow

content/docs/extensions/pg_cron.md, content/guides/convex-neon.md
Add the restart instructions inline for pg_cron docs. a couple of users have hit this issue.
=> docs: pg cron restart instructions

src/components/pages/demos/demo-list/demo-list.jsx
Deployed RAG example on Azure with the link to demo to try it out.
=> docs: add Neon on Azure demo project

content/guides/geospatial-search.md
One question: what is the best way to add an image to this post? Right now I have an image that's stored on my AWS bucket in this guide.
=> docs: add geospatial search guide

content/docs/manage/backups.md
=> docs: update backup links

src/app/enterprise/page.jsx
This PR aligns the hero logo carousel with the pricing page.
=> chore: upd enterprise logo carousel

content/docs/introduction/support.md
=> docs: add sla note

src/components/pages/pricing/plans/data/plans.json, src/components/pages/pricing/plans/table/table.jsx
This PR updates Pricing Page
- adds new link and text to Schema-only branches row
- updates links style
[Preview](https://neon-next-git-pricing-page-update-neondatabase.vercel.app/pricing)
=> chore: pricing page update

content/docs/introduction/monitoring-page.md
Preview:
Added note about TRUNCATE TABLE
https://neon-next-git-dprice-update-row-graph-docs-neondatabase.vercel.app/docs/introduction/monitoring-page#rows
=> docs: update row graph docs

content/docs/guides/neon-twin-full-pg-dump-restore.md, content/docs/guides/neon-twin-partial-pg-dump-restore.md, content/docs/use-cases/database-per-user.md, content/guides/reliable-testing-dataset-with-pg-dump-and-pg-restore.md
It's just a tiny change to a comment in some code examples.
=> docs: update comment for cron schedule timezone

src/app/tickets/[handle]/edit/page.jsx, src/app/tickets/[handle]/page.jsx
This PR  temporary removes tickets pages from build
Preview
=> feat: temporary remove tickets pages from build

content/docs/extensions/pg-extensions.md
=> docs: extension request update

content/docs/reference/typescript-sdk.md
https://neon-next-git-fork-dhanushreddy291-add-docs-088faf-neondatabase.vercel.app/docs/reference/typescript-sdk
=> docs: add typescript-sdk methods

content/postgresql/postgresql-plpgsql/pl-pgsql-row-types.md, content/postgresql/postgresql-plpgsql/plpgsql-block-structure.md, content/postgresql/postgresql-plpgsql/plpgsql-if-else-statements.md, content/postgresql/postgresql-plpgsql/plpgsql-record-types.md, content/postgresql/postgresql-plpgsql/postgresql-create-function.md, content/postgresql/postgresql-plpgsql/postgresql-exception.md, content/postgresql/postgresql-tutorial/postgresql-select-into.md
Update the broken links of the SELECT INTO statement of the PL/pgSQL in postgres tutorial
=> Update broken links 

content/postgresql/postgresql-tutorial/postgresql-any.md
Fix the output of the query:
```sql
SELECT * FROM employees;
```
=> Fix: postgresql-any.md SELECT query output.

content/docs/guides/branching-schema-only.md
Add note about schema-only branches
=> docs: schema-only-note

src/app/blog/(index)/category/[slug]/page.jsx, src/app/blog/(index)/layout.jsx, src/app/blog/(index)/page.jsx, src/app/guides/(index)/layout.jsx, src/app/guides/(index)/page.jsx, src/components/pages/blog/blog-header/blog-header.jsx, src/components/shared/algolia-search/algolia-search.jsx, src/components/shared/algolia-search/search-input/search-input.jsx, src/components/shared/algolia-search/search-results/search-results.jsx
This PR brings optimization for the Blog and Guides pages loading
- continues https://github.com/neondatabase/website/pull/3075
- merges all search components in one (`AlgoliaSearch`)
- conditional render for `AlgoliaSearch` on mount
[Preview Blog](https://neon-next-git-optimize-blog-loading-neondatabase.vercel.app/blog)
[Preview Guides](https://neon-next-git-optimize-blog-loading-neondatabase.vercel.app/guides)
=> refactor: optimize blog loading

content/docs/security/security-reporting.md
context: https://neon.tech/blog/neons-bug-bounty-program-with-hackerone-goes-public
=> Update security-reporting.md - update private to public for bb program

content/docs/guides/neon-auth.md
https://neon-next-git-fork-dhanushreddy291-add-docs-13cbd9-neondatabase.vercel.app/docs/guides/neon-auth#before-neon-auth
=> docs: improve neon auth about page

content/docs/ai/semantic-kernel.md, content/docs/sidebar.yaml
Add Semantic Kernel code example for RAG operations.
=> docs: add semantic kernel integration

src/constants/links.js, src/constants/menus.js
This PR replaces footer link:
Business Associate Agreement -> Sensitive Data Terms
[Preview](https://neon-next-git-replace-footer-compliance-link-neondatabase.vercel.app/)
=> chore: replace footer compliance link

content/docs/reference/cli-auth.md, content/docs/reference/neon-cli.md
Update Neon CLI's documentation to accurately represent the CLI's authentication flow.
=> docs: update cli authentication flow info

src/app/api/topbar/route.js
This PR brings new api route for fetching data for topbar from WordPress
[Preview](https://neon-next-git-wp-topbar-api-neondatabase.vercel.app/api/topbar)
=> feat: add new api route for fetching topbar from wp

content/docs/guides/neon-auth.md, content/docs/manage/organizations.md
Preview:
- [Org permissions](https://neon-next-git-bgrenon-update-org-matrix-neondatabase.vercel.app/docs/manage/organizations#user-roles-and-permissions)
- [Neon Auth permissions](https://neon-next-git-bgrenon-update-org-matrix-neondatabase.vercel.app/docs/guides/neon-auth#permissions)
=> Clarifying permissions matrix for orgs + neon auth

content/guides/cline-mcp-neon.md, content/guides/cursor-mcp-neon.md, content/guides/windsurf-mcp-neon.md
https://neon-next-git-fork-dhanushreddy291-add-docs-d4ef41-neondatabase.vercel.app/guides/cursor-mcp-neon
https://neon-next-git-fork-dhanushreddy291-add-docs-d4ef41-neondatabase.vercel.app/guides/windsurf-mcp-neon
https://neon-next-git-fork-dhanushreddy291-add-docs-d4ef41-neondatabase.vercel.app/guides/cline-mcp-neon
=> docs: add windows specific instructions

content/docs/ai/connect-mcp-clients-to-neon.md, content/guides/neon-mcp-server.md
https://neon-next-git-fork-dhanushreddy291-add-docs-d4ef41-neondatabase.vercel.app/docs/ai/neon-mcp-server
https://neon-next-git-fork-dhanushreddy291-add-docs-d4ef41-neondatabase.vercel.app/docs/ai/connect-mcp-clients-to-neon
=> docs: update mcp for windows

content/guides/migrate-faunadb-to-neon.md
https://neon-next-git-fork-dhanushreddy291-add-docs-fauna-neondatabase.vercel.app/guides/migrate-faunadb-to-neon
=> docs: fauna migration guide

content/docs/use-cases/database-per-user.md
Fixes minor typos/wording in `database-per-user.md`
=> Fix minor documentation typos/wording

content/docs/manage/slack-app.md
https://neon-next-git-bgrenon-slack-app-requested-changes-neondatabase.vercel.app/docs/manage/slack-app
=> Add requested changes to Neon App for Slack + clearer CTA

content/docs/security/hipaa.md
Preview:
https://neon-next-git-docs-hipaa-updates-neondatabase.vercel.app/docs/security/hipaa#enabling-hipaa-for-a-neon-project
=> Docs hipaa updates

content/docs/guides/neon-private-networking.md
=> docs: update private networking

content/docs/guides/autoscaling-guide.md, content/docs/guides/scale-to-zero-guide.md, content/docs/guides/vercel-previews-integration.md, content/docs/manage/projects.md
Closes: [20159](https://github.com/neondatabase/cloud/issues/20159)
=> Clarify default compute settings

content/docs/manage/slack-app.md
- Make explicit that you need an account to use the app
- Summarize data policy with email for requesting data removal
Preview: https://neon-next-git-bgrenon-slack-app-delete-data-neondatabase.vercel.app/docs/manage/slack-app#data-deletion
=> Content changes from 2nd round slack review

content/postgresql/postgresql-tutorial/postgresql-merge.md, package-lock.json, package.json
https://neon-next-git-merge-faq-neondatabase.vercel.app/postgresql/postgresql-tutorial/postgresql-merge#frequently-asked-questions-faq
=> adding the FAQ section to the merge page

content/postgresql/postgresql-tutorial/postgresql-real-data-type.md
Fix real value range  typo
Was tricked...
=> Fix real values range typo

src/components/shared/header/mobile-menu/mobile-menu.jsx, src/components/shared/header/navigation/navigation.jsx, src/components/shared/link/link.jsx
This PR brings analytics tags to header navigation
[Preview](https://neon-next-git-header-nav-analytics-neondatabase.vercel.app/)
=> feat: add analytics to header navigation

content/docs/introduction/support.md
Fixed a simple typo, a commit to test my email address
=> docs: typo

src/app/pricing/page.jsx, src/components/pages/pricing/faq/faq.jsx, src/components/pages/pricing/startup-pricing/index.js, src/components/pages/pricing/startups/index.js, src/components/pages/pricing/startups/startups.jsx, src/constants/links.js
This PR brings code refactor for the Pricing page
- Startups section fixes after https://github.com/neondatabase/website/pull/3403 update
- FAQ section links
[Preview](https://neon-next-git-startup-pricing-section-neondatabase.vercel.app/pricing)
=> refactor: pricing page

content/docs/sidebar.yaml, content/docs/workflows/data-anonymization.md
Preview:
https://neon-next-git-docs-anonymized-branches-neondatabase.vercel.app/docs/workflows/data-anonymization
=> docs: add data anonymization workflow topic

content/docs/azure/azure-develop.md
Added link to the online course Neon on Azure hosted on Udemy: https://www.udemy.com/course/aspnet-core-development-with-neon-postgresql-azure
=> docs: add online course link

src/components/pages/blog-post/aside/aside.jsx, src/components/shared/changelog-form/changelog-form.jsx
This PR fixes the sidebar blog post form.
[example post](https://neon-next-git-blog-form-fix-neondatabase.vercel.app/blog/postgres-18-beta-is-out)
=> fix: blog post sidebar form fix

content/docs/get-started-with-neon/frameworks.md, content/docs/sidebar.yaml
=> docs: sync framework list and tiles

src/lib/graphQLClient.js
This PR brings enhancement for GraphQL client configuration with GET and POST methods
Reference: https://wpengine.com/builders/moving-get-post-requests-faust-js-1-0-wpgraphql/
[Preview Blog](https://neon-next-git-graphql-get-cache-neondatabase.vercel.app/blog)
=> feat: enhance graphql congif

content/docs/azure/azure-deploy.md, content/docs/azure/azure-develop.md, content/docs/azure/azure-manage.md, content/docs/introduction/billing-azure-marketplace.md, content/docs/manage/azure.md
This feature is GA as per https://neon.com/docs/changelog/2025-05-09 
Issue discovered by Monica, thanks!
=> docs: remove azure public preview tag

content/docs/workflows/data-anonymization.md
Updated docs as per review, and other miscellaneous changes
=> docs: improved docs as per colin review

src/components/pages/doc/mode-toggler/mode-toggler.jsx
This PR updates styles for Docs mode toggler
[Preview](https://neon-next-git-docs-ai-toggler-update-neondatabase.vercel.app/docs/introduction)
=> feat: update docs mode toggler styles

content/docs/import/import-sample-data.md, content/docs/import/migrate-sqlite.md
https://neon-next-git-fork-dhanushreddy291-add-docs-981e05-neondatabase.vercel.app/docs/import/migrate-sqlite
=> docs: add sqlite to neon migration

next.config.js
Rewrite all static assets to fix regional latency demo
=> Fix latency dashboard

content/docs/guides/python.md
Before: https://neon.com/docs/guides/python
After PR:
https://neon-next-git-fork-dhanushreddy291-update-d-b9c5cb-neondatabase.vercel.app/docs/guides/python
Also merge: https://github.com/neondatabase/examples/pull/111
=> docs: update python quickstart

content/docs/guides/vercel-managed-integration.md
This solves [#31201](https://github.com/neondatabase/cloud/issues/31201)
=> docs: add FAQ

content/docs/guides/backup-restore.md
Related to https://github.com/neondatabase/website/pull/3784
=> docs: remove snapshot scheduling

content/docs/introduction/regions.md
Include the new cell's IP to the region's documentation.
=> feat(regions): update nat gateway ips

content/docs/guides/neon-private-networking.md
Otherwise, projects from some cells are not working together with VPC Endpoint ID from different cell.
#LKB-3269
=> Specify that all VPC Endpoint IDs must be restricted

content/docs/introduction/legacy-plans.md, content/docs/introduction/plans.md
Update v3 Free plan project limit.
=> docs: project limit increase

content/docs/guides/neon-private-networking.md
https://databricks.atlassian.net/browse/LKB-2609
=> docs: Add VPC Endpoint Service name for "prod-aws-eu-central-1-cell-2"

content/guides/neon-auth-nextjs.md
https://neon-next-git-fork-dhanushreddy291-add-docs-13cbd9-neondatabase.vercel.app/guides/neon-auth-nextjs
=> docs: use neon auth helper function in drizzle-orm/neon

content/docs/introduction/manage-billing.md
Update e-mandates information for Indian customers.
Preview:
https://neon-next-git-docs-emandates-updates-neondatabase.vercel.app/docs/introduction/manage-billing#failing-payments-for-indian-customers
=> docs: emandates update

src/constants/menus.js
This PR updates Agents header menu item text:
=> chore: update agents menu item

content/docs/import/complete-supabase-migration.md, content/guides/complete-supabase-migration.md
https://neon-next-git-fork-dhanushreddy291-add-docs-bfb1e2-neondatabase.vercel.app/guides/complete-supabase-migration
=> docs: add complete supabase to neon migration guide

content/docs/guides/backup-restore.md
Added details about snapshot limits and support contact.
=> Enhance backup-restore guide with snapshot info

content/docs/guides/opentelemetry.md
Note added:
https://neon-next-git-docs-update-otel-docs-neondatabase.vercel.app/docs/guides/opentelemetry#configure-the-connection
Troubleshooting item added:
https://neon-next-git-docs-update-otel-docs-neondatabase.vercel.app/docs/guides/opentelemetry#troubleshooting
=> docs: update otel docs

content/docs/guides/dotnet-npgsql.md, content/docs/guides/elixir.md, content/docs/guides/go.md, content/docs/guides/java.md, content/docs/guides/javascript.md, content/docs/guides/python.md, content/docs/guides/rust.md, public/prompts/dotnet-prompt.md, public/prompts/elixir-prompt.md, public/prompts/golang-prompt.md, public/prompts/java-prompt.md, public/prompts/javascript-prompt.md, public/prompts/python-prompt.md, public/prompts/rust-prompt.md
- [Dotnet](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guides/dotnet-npgsql)  
- [Elixir](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guides/elixir)  
- [Go](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guides/go)  
- [Java](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guides/java)  
- [JavaScript](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guides/javascript)  
- [Python](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guides/python)  
- [Rust](https://neon-next-git-fork-dhanushreddy291-add-docs-997db1-neondatabase.vercel.app/docs/guid …
=> docs: add language prompts

content/docs/data-api/sql-to-rest.md, content/docs/navigation.yaml, next.config.js, package-lock.json, package.json, src/components/shared/content/content.jsx, src/components/shared/sql-to-rest-converter/index.js, src/components/shared/sql-to-rest-converter/sql-to-rest-converter.jsx
https://github.com/user-attachments/assets/bda1f9d9-089d-4aeb-9a1c-f5a713f5d4e5
@bgrenon feel free to take over the PR and adjust copy. We might also want to have a different query by default
There is an annoying flicker that seems to be a bug in the CodeBlock component when the content changes
=> docs: adds new page with sql to postgrest translator

content/docs/manage/projects.md
Updated text for clarity regarding restore window limits.
=> Clarify information about restore window limits

content/docs/introduction/plans.md
Reworded sentences for clarity regarding restore window configuration.
=> Clarify restore window configuration details

src/components/pages/doc/definition-list/definition-list.jsx
This PR adds a unique ID to each definition list item:
[Example post](https://neon-next-git-upd-definition-list-neondatabase.vercel.app/docs/introduction/plans#what-is-a-cu)
=> feat: generate id at DefinitionList

src/components/pages/pricing/hero/hero.jsx
This PR updates the [pricing](https://neon-next-git-upd-pricing-style-neondatabase.vercel.app/pricing) Contact us link style
=> feat: update pricing Contact us link style
