neondatabase/website

content/docs/sidebar.yaml
Hey guys @hlinnaka @kelvich @stepashka @nikitashamgunov!
Bumped on a typo today that caused a redirect to the homepage when you try to open [/docs/quickstart/symphony/](https://neon.tech/docs/quickstart/symphony/)
Also, page seems like a draft, in order to hide it in production, you can use `isDraft` flag:
```mdx
---
title: Run a Symfony app
isDraft: true
---
```
=> docs: symphony => symfony

content/docs/cloud/about.md, content/docs/get-started-with-neon/signing-up.md
This PR is a small fix to a broken link in the docs. It adds a redirect in case the broken link has been shared anywhere and updates the documentation page to an existing link.
=> docs: fixes broken link to getting started

content/docs/conceptual-guides/architecture-overview.md
This fixes a redirect for the architecture overview page
=> docs: missing redirect for architecture overview

content/docs/integrations/integrations-list.md, content/docs/sidebar.yaml
Small change, this updates the name of "cloud integrations" to "cloud deployments"
=> docs: updated cloud integrations to deployments

content/docs/conceptual-guides/branching.md, content/docs/reference/glossary.md, content/docs/sidebar.yaml
This updates the glossary from `Branches` to `Branch` and renames the concept guide to `Branching`
=> docs: updates branches and branching 

src/components/pages/home/advantages/advantages.jsx
I think there should be the 'cold' word here. Moreover, we already have 'cold' here in a similar context: https://github.com/neondatabase/website/blob/897b3bda15dc96b0a90858e9354a6516a3eea042/src/components/pages/home/storage/storage.jsx#L29
=> nit: fix doc

content/docs/how-to-guides/connectivity-issues.md
Be more strict with project id/name difference. In passing fix awkward
wording and update status for golang drivers.
=> fix: update SNI doc

gatsby/create-redirects.js
This pull request introduces the `redirectFrom` validation for docs. The redirect should start with a slash, otherwise, the build will fail.
=> feat: add redirect validation

content/docs/reference/compatibility.md
this fuxes the typo in the extensions table
=> docs: remove the extra bracket

content/docs/get-started-with-neon/query-with-neon-sql-editor.md
This pull request prevents line breaks on the docs page.
=> fix: remove empty lines in docs

content/docs/how-to-guides/using-branches.md
This copies the existing branching guide into the repo, the only additions are the title in the frontmatter and draft has been set to true. It will be changed in a later PR into website content by removing the email template variable and adding website-specific content.
=> docs: copied the branching guide into repo

src/components/pages/doc/previous-and-next-links/previous-and-next-links.jsx, src/styles/content.css
This pull request adds padding-left to an ordered list for content block.
Preview: https://websitemain62807-contentstyles.gtsb.io/docs/get-started-with-neon/query-with-neon-sql-editor/
=> fix: add padding left for ol in content

src/components/pages/blog-post/cta/cta.jsx, src/components/pages/blog-post/cta/images/background.svg, src/components/pages/blog-post/cta/index.js, src/templates/blog-post.jsx
This pull request brings the CTA lazy block for blog posts, this block was integrated with WP.
Preview: https://websitemain62807-ctacomponent.gtsb.io/blog/neon-at-percona-live-2022/
=> feat: add CTA component for blog posts

content/changelog/2022-07-19-storage-release/index.md, content/changelog/2022-08-02-storage-release/index.md, content/changelog/2022-08-31-console-release/index.md, content/changelog/2022-09-01-storage-release/index.md, content/changelog/2022-09-02-console-release/index.md, content/docs/conceptual-guides/branching.md, content/docs/get-started-with-neon/using-api-keys.md, content/docs/how-to-guides/connectivity-issues.md, content/docs/integrations/go.md, content/docs/integrations/postgres.md, content/docs/integrations/sqlalchemy.md, content/docs/integrations/vercel.md, content/docs/reference/glossary.md
- Postgres > PostgreSQL (Heikki and Stas have agreed to use the official name "PostgreSQL" in the docs)
- Control plane > Control Plane (Release notes)
- A few other minor edits
=> Fix naming inconsistencies

content/docs/cloud/getting-started.md, content/docs/integrations/integrations-list.md, content/docs/storage-engine/control-plane.md, content/docs/storage-engine/read-path.md, content/docs/storage-engine/write-path.md
This pull request converts the doc posts, which wasn't included in the sidebar to draft. 
- cloud/getting-started
- integrations/integrations-list
- storage-engine/control-plane
- storage-engine/read-path
- storage-engine/write-path
=> fix: turn doc posts to draft

gatsby/create-pages.js, src/components/pages/blog-post/hero/hero.jsx, src/components/pages/blog/posts-list/posts-list.jsx, src/components/pages/home/data-branching/data-branching.jsx, src/components/pages/jobs/jobs-list/jobs-list.jsx, src/components/pages/team/cta/cta.jsx, src/components/shared/footer/footer.jsx, src/constants/links.js, src/constants/menus.js, src/constants/seo-data.js, src/pages/about-us.jsx, src/pages/careers.jsx, src/templates/blog-post.jsx, src/templates/blog.jsx
**This PR brings the following changes**
- Add the author link to the blog post layout if it is passed
- Rename Jobs → Careers, Team → About Us in the menu
- Change links in the bottom menu: 
- Company: Blog, About Us, Careers
- Resources: Docs, Release Notes, Security
- Move social links from the menu to the icon format (left corner of the bottom menu), add discourse link 
- Add the “read more” link next to the “Data Branching” point leading to [this](https://neon.tech/docs/conceptual-guides/branching/) page in the docs 
**How to test**
- Check the items listed above
- Check redirects for [team/about us](https://neon.tech/team/) and [jobs/careers](https://neon.tech/jobs/)
- Check the post author link for posts written by Bojan Serafimov (test link leads to https://neon.tech/): …
=> Minor website changes

content/docs/conceptual-guides/architecture-overview.md, content/docs/how-to-guides/import-an-existing-database.md, content/docs/integrations/symfony.md, content/docs/reference/compatibility.md
Use "regular PostgreSQL" instead of "vanilla PostgreSQL". We currently use both. We need to settle on one. I think "regular" is less ambiguous than "vanilla" for users who are not familiar with PostgreSQL lingo.
I will add a glossary definition for "regular PostgreSQL" in a separate PR for the glossary.
=> Terminology fixes

src/components/pages/team/team/team.jsx
This pull request brings a minor fix to the About us page
- update the team member role
=> chore: update team member position

content/docs/how-to-guides/import-an-existing-database.md, content/docs/how-to-guides/import-from-heroku.md, content/docs/integrations/hasura.md, content/docs/sidebar.yaml
The previous file name included "hasura". The guide is no longer specific to Hasura. Update naming in our data import section to use "Import" instead of "Migrate".
https://websitemain62807-dpricerenamebranchingtopicredo.gtsb.io/docs/how-to-guides/import-from-heroku/
Previously, headings were:
Import data
Importing a database
Migrating from Heroku
Now:
Import data
Import data from PostgreSQL
Import data from Heroku
=> Rename heroku topic & related changes

content/docs/get-started-with-neon/connection-pooling.md, content/docs/get-started-with-neon/query-with-neon-sql-editor.md, content/docs/how-to-guides/connectivity-issues.md, content/docs/integrations/django.md, content/docs/integrations/go.md, content/docs/integrations/hasura.md, content/docs/integrations/java.md, content/docs/integrations/node.md, content/docs/integrations/prisma.md, content/docs/integrations/rust.md, content/docs/integrations/sqlalchemy.md, content/docs/integrations/symfony.md, content/docs/integrations/vercel.md, content/docs/sidebar.yaml
https://websitemain62807-dpricecreateguidesheadingintoc.gtsb.io/docs/cloud/about/
- Dropped "Integrations" and "Develop" headings from TOC. Replaced with "Guides".
- Adjusted topic titles.
- Enabled TOC for a few other files
=> Revise TOC headings and topic titles

src/components/shared/subscribe/subscribe.jsx
This PR adds `id` attribute for `Subscribe` section so that we can generate proper QR link to be used in Subscribe CTA conference flyers
=> chore: added id to subscribe section

src/components/pages/early-access/hero/hero.jsx
This PR adds an appearance-none class to an input on the Get Early Access page to disable default safari styles.
[Preview](https://websitemain62807-inputfix.gtsb.io/early-access/)
=> Minor style fix for an input

content/docs/cloud/about.md, content/docs/reference/compatibility.md
Extensions table can be improved, because some extensions' versions differ in v14 and v15.
We could change table from `Extension | Version | Note` to `Extension | Version (pg 14) | Version (pg 15) | Note`
=> Support pg15

content/docs/README.md, gatsby-node.js, gatsby/create-schema-customization.js, src/templates/doc.jsx
This pull request brings the ability to add a social preview for the docs page by adding `ogImage` in the md `frontmatter`.
Example:  
```md
---
title: Neon architecture
ogImage: ./images/neon_architecture_2.png
redirectFrom:
- /docs/storage-engine/architecture-overview
---
```
=> feat: add social preview flag to docs

gatsby-config.js, gatsby/constants.js, src/components/shared/layout/layout.jsx
This pull enables Google Tag Manager only on production.
**Additional changes**
- fixed prop types of footer
- updated condition of the draft filter using env variable `IS_PRODUCTION`
=> feat: enable GTM only on production

src/components/shared/blog-post-author/blog-post-author.jsx
This pull request brings the target `_blank` for the blog post author Link.
=> feat: add target blank for blog post author url

content/docs/cloud/about.md, content/docs/get-started-with-neon/connection-pooling.md, content/docs/get-started-with-neon/query-with-psql-editor.md, content/docs/get-started-with-neon/setting-up-a-project.md, content/docs/reference/compatibility.md
To be published when PG15 is made the default on prod.
- Mention that PG15 is the default.
- Update content that implies PG 14 is the default.
- Change links to point to PG 15 docs.
=> Update docs to reflect that PG15 is the default

src/components/shared/topbar/topbar.jsx
This pull request adds Tailwind class `truncate` to truncate the overflowing text with an ellipsis (…) in case of text in the topbar is longer than 1 line.
=> fix: prevent topbar height increase

content/docs/manage/endpoints.md
The content was developed before the endpoint page was available in the console. It included information about items that are not yet available. The content has been revised accordingly.
=> Revise endpoint content.

content/docs/connect/connect-from-any-app.md, content/docs/connect/query-with-psql-editor.md
Added information about clients without SNI support (search on SNI)
https://websitemain62807-dpriceaddnoteoldclientsniissue.gatsbyjs.io/docs/connect/query-with-psql-editor/
https://websitemain62807-dpriceaddnoteoldclientsniissue.gatsbyjs.io/docs/connect/connect-from-any-app/
Addresses https://github.com/neondatabase/website/issues/333
=> Add note about old client connection issue

content/docs/connect/passwordless-connect.md
- Passwordless connect no longer requires selecting an endpoint for projects with a single endpoint.
- Mentioned that the connection is to the first database created in the branch
- Mentioned that switching databases restarts the passwordless auth process
https://websitemain62807-dpricepasswordlessconnectupdat.gatsbyjs.io/docs/connect/passwordless-connect/
=> Dprice passwordless connect update

content/docs/introduction/branching.md
This PR updates the [Branch endpoints](https://neon.tech/docs/introduction/branching/#branch-endpoints) section. The section starts by saying:
> Each branch is created with an endpoint
This is inaccurate since one can create a branch without an endpoint and add one later. I updated the content but feel free to make changes if you find better wording 😄
=> Update branch endpoints section

content/docs/connect/connectivity-issues.md
Clarified that Postgrex supports SNI, and also added a link to the official documentation which shows how it can be done.
=> Update SNI info for Elixir Postgrex client

src/utils/get-release-notes-date-from-slug.js
This PR brings sets the time zone UTC for release notes date.
=> fix: set time zone for release notes date

next/content/docs/release-notes.md, next/src/constants/links.js
So far, the vercel-bot has fallen
=> Fix: return next docs/release-notes page

next/content/docs/reference/pg-extensions.md, next/content/release-notes/2023-01-31.md
Preview:
https://neon-next-git-vk-storagerelease20230131-neondatabase.vercel.app/docs/release-notes
=> docs: release notes for storage release 2023-01-31

src/utils/get-release-notes-date-from-slug.js
**Describe the changes**
This PR brings the fix for release notes dates, that sometimes do jump. Presumably, it has been happening to due `toLocaleDateString`, whose output is relative to user agent.
=> fix: jumping releaes notes date relative to user agent

content/docs/guides/prisma.md
This PR fixes `connection pooling` link:
=> prisma: fix connection pooling link

next.config.js
Adds a redirect from https://neon.tech/driver to https://neon.tech/docs/serverless/serverless-driver to make it easier to share
=> add redirect for serverless driver docs

src/scripts/build-algolia-search.js
This PR updates Algolia release-notes title from `Storage release - 2023-03-21-storage` to `Storage release - 2023-03-28`
=> Fix: update release-notes Algolia title

content/docs/introduction/billing.md, content/docs/introduction/technical-preview-free-tier.md, content/docs/manage/branches.md, content/docs/reference/glossary.md
Update free tier content and related information to clarify limits.
- Bold the statement about Active time on the primary branch compute
- Explain that compute time on the primary branch compute is counted toward the 100 hours Active time limit per month
Preview:
https://neon-next-git-dprice-free-tier-content-updates-neondatabase.vercel.app/docs/introduction/technical-preview-free-tier
https://neon-next-git-dprice-free-tier-content-updates-neondatabase.vercel.app/docs/introduction/billing
=> Free Tier content updates

content/docs/introduction/billing.md, content/docs/reference/glossary.md
Add "Active time" description to billing page, as requested here:
https://github.com/neondatabase/cloud/issues/4624
Preview:
https://neon-next-git-dprice-add-active-time-descri-fac965-neondatabase.vercel.app/docs/introduction/billing#billing-and-usage-metrics
https://neon-next-git-dprice-add-active-time-descri-fac965-neondatabase.vercel.app/docs/introduction/billing#active-time
=> Add Active time description to the billing page

content/docs/guides/prisma.md
Update Prisma docs to emphasize adjusting your connection string to avoid timeout issues.
- Add link to connection timeout issues from the intro.
- Add a warning that mentions adjusting the connection string to avoid connection timeout issues.
Preview:
https://neon-next-git-dprice-prisma-connections-update-neondatabase.vercel.app/docs/guides/prisma
=> Highlight Prisma connection timeout instructions

content/docs/guides/go.md
Hopefully this is not too pedantic of a change, but here it is. I updated the sample Go code for connecting to and querying the database to reflect idiomatic code:
- it does not use `log.Fatal` in conjunction with `defer`: `log.Fatal` calls `os.Exit`, which abruptly ends the program without calling any deferred functions
- it uses `QueryRow` instead of `Query`, which should in general be used for querying a single value; the resulting code is much shorter
By having the example shorter, readers can focus better and mainly on the connection part.
BTW, great product and great service! Thank you for creating this.
=> Improve and shorten Go connect example code

content/docs/introduction/architecture-overview.md, content/docs/reference/glossary.md
- Add Data-at-rest encryption glossary entry, explaining that Neon encrypts data at rest.
https://neon-next-git-dprice-data-at-rest-doc-neondatabase.vercel.app/docs/reference/glossary#data-at-rest-encryption
- Reference the glossary entry from our Architecture page (just a "encrypted at rest" link).
https://neon-next-git-dprice-data-at-rest-doc-neondatabase.vercel.app/docs/introduction/architecture-overview
=> Add data-at-rest content

content/docs/guides/vercel.md, content/docs/introduction/branching.md, content/release-notes/2023-02-24-console.md, content/release-notes/2023-02-27-docs.md
- Added note: "The Neon Vercel Integration is currently only supported with the GitHub source code repository."
https://neon-next-git-dprice-mention-github-explcitly-neondatabase.vercel.app/docs/guides/vercel#add-the-neon-vercel-integration
- Also updated the Neon Vercel Integration page on the Vercel site to mention GitHub instead just git
- Adjusted capitalization for "The Neon Vercel Integration"
=> Neon Vercel Integration: mention GitHub support explicitly

src/styles/blog-content.css, src/styles/doc-content.css
This PR enables code block wrapping instead of scroll
for example:
[doc page](https://neon-next-git-code-block-wrap-neondatabase.vercel.app/docs/manage/databases)
[blog post](https://neon-next-git-code-block-wrap-neondatabase.vercel.app/blog/sql-template-tags)
=> feat: enable code block wrapping

content/docs/README.md, src/components/pages/doc/code-tabs/code-tabs.jsx, src/components/shared/code-block/code-block.jsx, src/components/shared/content/content.jsx, src/styles/blog-content.css, src/styles/doc-content.css
This PR enables code wrapping in the `mdx` custom components `CodeBlock` and `CodeTabs` instead of the default code wrapping
=> feat: enable code wrapping via flag

content/docs/connect/connectivity-issues.md, content/docs/guides/node.md, content/release-notes/2023-05-16-storage-and-compute.md
Release notes:
https://neon-next-git-dprice-05-16-storage-release-neondatabase.vercel.app/docs/release-notes
Related connection doc updates:
https://neon-next-git-dprice-05-16-storage-release-neondatabase.vercel.app/docs/connect/connectivity-issues#a-pass-the-endpoint-id-as-an-option
=> Storage release notes 05-16

content/docs/import/import-from-postgres.md, content/release-notes/2023-05-11-console.md, content/release-notes/2023-05-16-console.md, content/release-notes/2023-05-16-storage-and-compute.md, content/release-notes/2023-05-19-console.md
*Describe the changes*
This PR fixes internal links on the following pages:
- content/docs/import/import-from-postgres.md
- content/release-notes/2023-05-11-console.md
- content/release-notes/2023-05-16-console.md
- content/release-notes/2023-05-16-storage-and-compute.md
- content/release-notes/2023-05-19-console.md
Closes #748 
cc @danieltprice
=> fix: broken links on release notes

content/docs/connect/connection-pooling.md, content/docs/manage/endpoints.md
Previews:
https://neon-next-git-dprice-autoscaling-connection-limit-neondatabase.vercel.app/docs/connect/connection-pooling
https://neon-next-git-dprice-autoscaling-connection-limit-neondatabase.vercel.app/docs/manage/endpoints#compute-size-and-autoscaling-configuration
=> Add connection pooling limitation for Autoscaling

content/docs/reference/compatibility.md
Mention changing database encoding as a current limitation
https://neon-next-git-dprice-database-encoding-support-neondatabase.vercel.app/docs/reference/compatibility#database-encoding
=> Dprice database encoding support

content/docs/connect/connect-from-any-app.md, content/docs/connect/connection-pooling.md, content/docs/connect/connectivity-issues.md, content/docs/connect/query-with-psql-editor.md, content/docs/guides/grafbase.md, content/docs/guides/prisma.md, content/docs/guides/stepzen.md, content/docs/import/import-from-heroku.md, content/docs/manage/branches.md, content/docs/reference/glossary.md, content/docs/unused/integrations-deprecated, content/docs/unused/prisma-guide.md, content/release-notes/2023-02-06-console.md
Add `<CodeBlock shouldWrap>` tags to wrap long connection strings so you do not have to scroll.
=> Wrap connection string codeblocks

content/docs/connect/connection-pooling.md, content/docs/manage/endpoints.md
Remove notes about connection pooling support with Autoscaling
https://neon-next-git-dprice-autoscaling-supports-c-70a9d8-neondatabase.vercel.app/docs/connect/connection-pooling
=> Autoscaling is now supported with connection pooling

content/docs/introduction/roadmap.md
We need to change this "Read more" link on the console, which currently points to the Free Tier page.
The Technical Preview applies to Neon in general (all plans), not just to the Free Tier. A user asked why they are still in the "Technical Preview Free Tier" after upgrading to Pro.
To address this issue, I have added a "Technical Preview" section to our Roadmap page. Once we agree on the text, I will update the Read more link. Please review.
An alternative option is to just drop the "Read more" link. 
https://neon-next-git-dprice-add-technical-preview-6c1e12-neondatabase.vercel.app/docs/introduction/roadmap
=> Add Technical Preview info to roadmap page

content/docs/introduction.md, src/components/pages/doc/mobile-nav/mobile-nav.jsx, src/components/pages/doc/sidebar/item/item.jsx, src/components/pages/doc/sidebar/sidebar.jsx, src/components/pages/doc/technology-navigation/technology-navigation.jsx
This pull request adds the images' explicit size for `TechnologyNavigation` component on `/docs/introduction` page.
<details>
<summary>Lighthouse</summary>
**Before**
**After**
There is no more error "Image elements do not have explicit width and height"
</details>
=> fix: set explicit image size on introduction page

src/components/pages/doc/chat-widget/chat-widget.jsx
This pull request adds chat widget events to gtag to track:
- Number of clicks on docs AI
- Clicks on the example questions
- Which questions are asked
- Stop generating button clicks
=> fix: send chat widget gtag event

content/docs/extensions/pg_tiktoken.md, src/components/pages/doc/table-of-contents/table-of-contents.jsx, src/components/shared/anchor-heading/anchor-heading.jsx, src/utils/api-docs.js
This pull request brings the support of inline code and special characters in Table of Contents
<details>
<summary>Screenshots</summary>
Before:
After:
</details>
**Preview**: https://neon-next-git-special-symbols-neondatabase.vercel.app/docs/extensions/pg_tiktoken
=> feat: add support of special symbols in ToC

src/app/blog/[slug]/page.jsx, src/components/pages/blog-post/code-tabs/code-tabs.jsx, src/components/pages/blog-post/code-tabs/index.js, src/components/shared/code-block/code-block.jsx, src/styles/blog-content.css, src/styles/doc-content.css
This pull request brings the code tabs for the blog posts
**Additional changes**
- add code line highlight support
**TODO**
**Preview**: https://neon-next-git-blog-code-tabs-neondatabase.vercel.app/blog/hello-world
=> feat: implement blog code tabs

content/docs/reference/cli-auth.md, content/docs/reference/cli-branches.md, content/docs/reference/cli-completion.md, content/docs/reference/cli-connection-string.md, content/docs/reference/cli-databases.md, content/docs/reference/cli-me.md, content/docs/reference/cli-operations.md, content/docs/reference/cli-projects.md, content/docs/reference/cli-roles.md, content/docs/reference/neon-cli.md
Remove the draft setting so that CLI docs show up on the docs site
=> Remove draft setting for CLI docs

src/constants/links.js, src/constants/menus.js, src/icons/console.inline.svg
This pull request adds a CLI Reference link to the Docs sidebar
=> feat: add sidebar item

src/components/pages/partners/apply/form/form.jsx
This PR brings the renaming of message key in partners' form
- rename from `message` to `TICKET.content`
=> fix: rename message key in partners form

content/docs/connect/connection-latency.md, content/docs/introduction/compute-lifecycle.md
Revise content about compute startup times to reflect recent improvements
- Compute Lifecycle:
https://neon-next-git-dprice-update-connection-time-7aa9b1-neondatabase.vercel.app/docs/introduction/compute-lifecycle
- Connection latencies and timeouts
https://neon-next-git-dprice-update-connection-time-7aa9b1-neondatabase.vercel.app/docs/connect/connection-latency
=> Revise content about compute startup times

content/docs/manage/roles.md, content/docs/reference/cli-auth.md, content/docs/reference/cli-branches.md, content/docs/reference/cli-completion.md, content/docs/reference/cli-connection-string.md, content/docs/reference/cli-databases.md, content/docs/reference/cli-me.md, content/docs/reference/cli-operations.md, content/docs/reference/cli-projects.md, content/docs/reference/cli-roles.md
This fix is to avoid duplicate meta description issues reported by the Semrush SEO Audit
=> Revise CLI intro content for SEO

content/docs/reference/neon-cli.md, content/release-notes/2023-07-13-console.md
Console release notes for 7-13 release (Please pardon the delay. I am playing catch-up after launch week.)
https://neon-next-git-dprice-07-13-console-release-notes-neondatabase.vercel.app/docs/release-notes/2023-07-13-console
- Just a couple of items. Mostly internal changes and fixes.
- Minor addition to CLI content (for Homebrew install support)
Note: Dark theme was covered in 07-14 release notes that coincided with launch week announcement date, so it's not included here.
=> 07-13 Console release notes

src/components/pages/blog/blog-post-card/blog-post-card.jsx, src/components/pages/blog/release-notes-list/release-notes-list.jsx
This pull request makes the featured blog post cover size equal on blog index and blog category pages.
<details>
<summary>Details</summary>
**Before**
https://github.com/neondatabase/website/assets/48465000/9b08f346-4f0a-4217-8028-69ab220ed316
**After**
https://github.com/neondatabase/website/assets/48465000/e275f7e5-b41d-4378-afcd-3f05b26acaa5
</details>
=> fix: featured blog post cover

content/docs/reference/cli-auth.md, content/docs/reference/cli-branches.md, content/docs/reference/cli-completion.md, content/docs/reference/cli-connection-string.md, content/docs/reference/cli-databases.md, content/docs/reference/cli-install.md, content/docs/reference/cli-me.md, content/docs/reference/cli-operations.md, content/docs/reference/cli-projects.md, content/docs/reference/cli-roles.md, content/docs/reference/neon-cli.md, content/docs/sidebar.yaml
Add the command synopsis back. It gives users a quick view of what the CLI includes before they've installed it.
Move installation instructions to a separate section.
https://neon-next-git-dprice-cli-updates-neondatabase.vercel.app/docs/reference/neon-cli
=> Reorganize CLI content

content/docs/guides/branching-neon-cli.md, content/docs/reference/cli-branches.md, content/docs/reference/cli-projects.md
Added the following tip to:
https://neon-next-git-dprice-cli-mention-connection-a5cd9d-neondatabase.vercel.app/docs/guides/branching-neon-cli
https://neon-next-git-dprice-cli-mention-connection-a5cd9d-neondatabase.vercel.app/docs/reference/cli-branches#create
https://neon-next-git-dprice-cli-mention-connection-a5cd9d-neondatabase.vercel.app/docs/reference/cli-projects#create
=> Highlight the connection-string CLI command

content/docs/introduction/plans.md, content/docs/introduction/pro-plan.md
Mention active compute limit and related error in the Pro plan topic
https://neon-next-git-dprice-mention-active-compute-limit-neondatabase.vercel.app/docs/introduction/pro-plan
=> Mention active compute limit

src/components/pages/release-notes/aside/aside.jsx, src/components/pages/release-notes/hero/hero.jsx, src/components/pages/release-notes/release-note-list/release-note-list.jsx
This pull request aligns the release notes date and label
Before:
After:
=> fix: align the release notes label

content/docs/guides/branching-pitr.md, content/docs/manage/endpoints.md, content/docs/reference/cli-branches.md
- Include steps for moving the compute endpoint from the old primary branch to the new branch in case you do not want to change application connection details.
https://neon-next-git-dprice-add-replace-endpoint-i-4f58f2-neondatabase.vercel.app/docs/guides/branching-pitr#reassign-the-compute-endpoint
- Add examples section and links to GitHub repos.
https://neon-next-git-dprice-add-replace-endpoint-i-4f58f2-neondatabase.vercel.app/docs/guides/branching-pitr#examples
- Other very minor related updates & a couple of unrelated minor content fixes
=> Update PITR content

content/docs/introduction/billing.md, src/components/pages/pricing/metrics/metrics.jsx
Pricing page:
- Change "/Compute-hour" to "/hour", since the price is .25 compute-hours, not a full compute-hour
- Change "Compute time is the amount of computing capacity used per hour." to "Compute time is the amount of compute resources used per hour."
- Note: We wanted to change PRICE to START PRICE, but this would require PP involvement, and as designed might apply to all metrics
Billing docs:
https://neon-next-git-dprice-align-compute-cost-content-neondatabase.vercel.app/docs/introduction/billing#billing-rates
- Change Compute time prices from $0.0255 to $0.102 to reflect the price for a full compute hour instead of .25 compute hours.
- Use "compute size" rather than "computing capacity"
- Update the compute time cost estimation formula
- Update information referenced by the …
=> Align billing content on pricing page and in the billing docs

content/docs/connect/connect-from-any-app.md
Neon currently supports ipv4. Mention this in the docs.
https://neon-next-git-dprice-ipv4-support-neondatabase.vercel.app/docs/connect/connect-from-any-app#network-protocol-support
=> Note ipv4 support

src/components/pages/blog/release-notes-list/release-notes-list.jsx, src/pages/api/release-notes.js
This pull request updates the release notes title on the Blog page
=> fix: update title for release notes on blog page

package-lock.json, package.json, src/app/docs/layout.jsx, src/components/pages/404/hero/hero.jsx, src/components/pages/ai/hero/hero.jsx, src/components/pages/blog/sidebar/sidebar.jsx, src/components/pages/doc/sidebar/sidebar.jsx, src/components/pages/partners/apply/form/form.jsx, src/components/shared/footer/theme-select/theme-select.jsx, src/components/shared/header/header.jsx, src/components/shared/search/search.jsx
This pull request brings some updates, that enhance the pages' performance
- dynamically import spline 
- dynamically search and chat widget in docs layout
- uninstalled unused plugin `@splinetool/runtime`
<details>
<summary>Home page</summary>
[Before](https://pagespeed.web.dev/analysis/https-neon-tech/tg8nfzsew4?form_factor=desktop):
[After](https://pagespeed.web.dev/analysis/https-neon-next-git-pagespeed-neondatabase-vercel-app/mbx75747ji?form_factor=desktop):
</details>
<details>
<summary>Docs page</summary>
[Before](https://pagespeed.web.dev/analysis/https-neon-tech-docs-introduction/7tqqp4nlex?form_factor=desktop):
[After](https://pagespeed.web.dev/analysis/https-neon-next-git-pagespeed-neondatabase-vercel-app-docs-introduction/7l1wx0xg6o?form_factor=desktop): …
=> chore: remove unused dep

content/docs/ai/ai-concepts.md, content/docs/ai/ai-intro.md, content/docs/extensions/pg_embedding.md, content/release-notes/2023-08-03-storage-and-compute.md, src/app/ai/page.jsx, src/components/pages/ai/integration/integration.jsx
- Remove vector extension migration instructions
https://neon-next-git-dprice-drop-extension-migrati-d9c87b-neondatabase.vercel.app/docs/extensions/pg_embedding
- Start Deemphasizing
- Drop the "Compatible vector types" tab from AI page and adjust text a little to deemphasize
- https://neon-next-git-dprice-drop-extension-migrati-d9c87b-neondatabase.vercel.app/ai
=> Drop vector extension migration instructions

next-sitemap.config.js, src/app/last-week-in-aws/page.jsx, src/constants/seo-data.js
This PR brings a home page duplicate for Last Week in AWS newsletter and blocks this page from indexing
=> feat: add last week in aws page and block it from indexing

src/styles/doc-content.css
This PR brings a subtle border for the docs illustrations to enhance readability.
[Preview](https://neon-next-git-docs-image-border-neondatabase.vercel.app/docs/guides/vercel)
=> feat: add image border to the docs articles

content/docs/ai/ai-intro.md
Add a link to our AI docs page for a GitHub repo that contains a Jupyter Notebook for Vector Search with Neon, pgvector, and OpenAI
https://neon-next-git-dprice-add-link-ipynb-pgvecto-7d3177-neondatabase.vercel.app/docs/ai/ai-intro#example-applications
=> Add example repo link for Jupyter Notebook for Vector Search with Neon

content/docs/guides/read-replica-guide.md, content/docs/guides/read-replica-prisma.md, content/docs/sidebar.yaml
Based on on Mahmoud's post:
https://neon-next-git-dprice-read-replica-prisma-neondatabase.vercel.app/docs/guides/read-replica-prisma
Note: I'll deal with read replica / read-only replica renaming all at once in the docs and the UI as a next step. In the meantime, let's get this out.
=> Add read replica Prisma guide

content/docs/introduction/billing.md, content/docs/security/soc2-compliance.md
Preview:
https://neon-next-git-dprice-minor-billing-page-update-neondatabase.vercel.app/docs/introduction/billing
The requested changed was to use "Compute size" instead of "Compute Units" in this formula:
"Compute time cost = Compute size * Active time * Compute-time price"
Other miscellaneous, unrelated edits.
=> Minor billing page updates & edits

content/docs/guides/branching-pitr.md, content/docs/introduction/billing.md, content/docs/introduction/point-in-time-restore.md, content/docs/manage/backups.md, content/docs/reference/glossary.md
Various minor edits to align language around point-in-time restore and "history retention". 
- The label in the UI is "History retention", so use that term instead of just "history". 
- Other minor edits.
=> Point-in-time restore edits

content/docs/introduction/pro-plan.md
Add a note about restarting a compute endpoint after upgrading to Pro.
https://neon-next-git-dprice-upgrade-to-pro-error-neondatabase.vercel.app/docs/introduction/pro-plan#how-do-i-upgrade-to-pro
=> Restart a compute endpoint after upgrading to Pro

next.config.js, src/constants/links.js, src/constants/menus.js
This PR brings a Trust page link to the footer menu for Security & Compliance purposes and adds a redirect to https://trust.neon.tech/. 
The Pr also moves the Blog link from Company submenu to Resources submenu in the Footer where it belongs.
=> feat: add trust page link to footer and configure redirect

content/docs/guides/project-sharing-guide.md, content/docs/manage/projects.md
Added note to address user feedback: https://neondb.slack.com/archives/C04BT3XH8PL/p1695398603131709
https://neon-next-git-dprice-update-project-sharing-neondatabase.vercel.app/docs/manage/projects#share-a-project
https://neon-next-git-dprice-update-project-sharing-neondatabase.vercel.app/docs/guides/project-sharing-guide
=> Add note about sharing a project with users that do not have a Neon account

next.config.js
This pull request brings additional headers for blog post /blog/parsing-json-from-postgres-in-js
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
=> fix: additional headers for blog post with custom embed iframe

.github/workflows/update-frontmatter.yml, .lintstagedrc, src/scripts/update-frontmatter.js
This pull request adds the GitHub actions workflow that updates the last updated date in docs markdown files.
Whenever you make a change to a Markdown file inside content/docs, the GitHub Action will trigger, running the script and updating the `updatedOn` date in the frontmatter. 
If you make changes via the GitHub interface, the action will still trigger and make the necessary updates.
**TODO**
=> feat: last updated date in docs

content/docs/serverless/serverless-driver.md
Add a link to the Ping Thing app from serverless driver topic.
https://neon-next-git-dprice-add-ping-thing-link-to-docs-neondatabase.vercel.app/docs/serverless/serverless-driver#ping-thing
=> Add Ping Thing and Hyperdrive example apps to serverless driver topic

content/docs/import/import-intro.md, content/docs/sidebar.yaml
Add an intro topic to link to from the new docs banner we're adding to the console. Use this intro page instead of the Postgres import topic.
https://neon-next-git-docs-import-intro-neondatabase.vercel.app/docs/import/import-intro
=> Add import intro

content/docs/guides/guides-intro.md, content/docs/import/import-intro.md
Improve landing pages for onboarding docs links:
Guides intro page with cards:
https://neon-next-git-docs-update-guides-intro-neondatabase.vercel.app/docs/guides/guides-intro
Import intro page with cards:
https://neon-next-git-docs-update-guides-intro-neondatabase.vercel.app/docs/import/import-intro
=> Add cards to guides and import landing pages

src/components/shared/anchor-heading/anchor-heading.jsx, src/utils/get-react-content-with-lazy-blocks.jsx
This pull request brings the anchor headings for blog posts
=> feat: add anchor headings for blog posts

src/components/pages/doc/sidebar/item/item.jsx
This pull request makes the docs sidebar collapsed by default
Preview: https://neon-next-git-sidebar-update-neondatabase.vercel.app/docs/introduction
=> feat: set sidebar collapsed by default

next-sitemap.config.js, src/app/stackoverflow/page.jsx
This PR brings a home page duplicate [/stackoverflow](https://neon-next-git-stackoverflow-page-neondatabase.vercel.app/stackoverflow) and blocks from page indexing, excludes from sitemap.
=> chore: add stackoverflow page & exclude it from indexing

content/docs/community/community-intro.md, content/docs/community/contribution-guide.md
Pages were not showing up due to isDraft: true frontmatter items.
=> Remove draft tags from community and contribution pages

content/docs/reference/cli-install.md
The CLI now requires Node 18 
https://github.com/neondatabase/neonctl/blob/0d13e7454a1d51b52b9de2a336285cddd377d5af/package.json#L15
=> cli-install.md: Update node dep version

src/app/all-things-open-2023/page.jsx, src/app/last-week-in-aws/page.jsx, src/app/stackoverflow/page.jsx
This pull request updates the canonical urls for pages:
- /all-things-open-2023
- /last-week-in-aws
- /stackoverflow
=> fix: update canonical urls for duplicated pages

src/app/layout.jsx
This pull request brings the preconnect links to project layout:
```html
<link rel="preconnect" href="https://console.neon.tech" />
<link rel="preconnect" href="https://auth.neon.tech" />
```
https://pagespeed.web.dev/analysis/https-neon-tech/mcnjt2wqxz?form_factor=desktop
<details>
<summary>Before</summary>
</details>
https://pagespeed.web.dev/analysis/https-neon-next-git-preconnect-links-neondatabase-vercel-app/v2nzogzpde?form_factor=desktop
<details>
<summary>After</summary>
</details>
=> feat: add preconnect links

content/docs/extensions/neon.md, content/docs/manage/roles.md, content/docs/sidebar.yaml, content/release-notes/2023-11-27-storage-and-compute.md
Release notes preview:
https://neon-next-git-dprice-storage-11-27-2023-neondatabase.vercel.app/docs/release-notes/2023-11-27-storage-and-compute
Accompanying doc update for neon_superuser:
https://neon-next-git-dprice-storage-11-27-2023-neondatabase.vercel.app/docs/manage/roles#the-neonsuperuser-role
neon extension doc (we should mention it in the docs if we're mentioning it in the release notes)
https://neon-next-git-dprice-storage-11-27-2023-neondatabase.vercel.app/docs/extensions/neon
=> Storage release 11-27-2023

next.config.js
This pull request sets the cache control `public, max-age=0, must-revalidate` for docs images, this kind of cache control is used for resources that need to be revalidated frequently to ensure they are up-to-date. It's useful for dynamic content or content that changes regularly as in the docs.
=> feat: reset cache control for docs images

.gitignore, next-sitemap-postgres.config.js, next-sitemap.config.js, package.json
**Description:**
This pull request adds additional sitemap generation for `Postgres` documentation pages
**What problems does it solve?**
at the moment the main sitemap contains all `Postgres` documentation pages, due to which these pages get to the `Google Search Console` level - this is not necessary as these pages are closed from indexing which leads to additional errors and spoils interaction with `GSC`, but as these pages in the sitemap are important for `Algolia Crawler` we solve this problem by generating an additional sitemap for Postgres pages which we can explicitly specify only for `Algolia`.
[Main Sitemap](https://neon-next-git-fix-sitemaps-neondatabase.vercel.app/sitemap-0.xml) without Postgres pages
[Postgres Sitemap](https://neon-next-git-fix-sitemaps-neondatabase.vercel.app …
=> feat: add sitemap generation for Postgres

src/app/blog/(index)/page.jsx, src/utils/api-posts.js
This pull request brings the AI section to the blog index page
**TODO**
=> feat: add AI section to blog index

content/docs/introduction/billing.md, src/components/shared/content/content.jsx
This pull request removes unnecessary Postgres props for paragraphs from Neon docs.
=> fix: remove postgres docs class from neon docs

src/components/shared/anchor-heading/anchor-heading.jsx, src/styles/blog-content.css, src/utils/get-react-content-with-lazy-blocks.jsx
This pull request removes the custom styles of the ordered lists for Blog post pages  
Preview: https://neon-next-git-native-ol-neondatabase.vercel.app/blog/title-a-deep-dive-into-polyscales-architecture
=> fix: remove custom style of ol list

content/docs/connect/connection-pooling.md
Document Neon's PgBouncer configuration. 
https://neon-next-git-dprice-pgbouncer-settings-neondatabase.vercel.app/docs/connect/connection-pooling#neon-pgbouncer-configuration-settings
Questions: 
- Need to explain why the sslmode settings are disabled. Is this because pgBouncer sits behind the Neon proxy?
- default_pool_size=64 (is it different based on provisioner? e.g., 16)
=> Add PgBouncer config content

content/docs/connect/connection-errors.md
Preview:
https://neon-next-git-fix-unsupported-startup-param-4208fb-neondatabase.vercel.app/docs/connect/connection-errors#unsupported-startup-parameter
=> Fix unsupported startup parameter description

content/docs/import/import-from-postgres.md, content/docs/manage/backups.md, content/postgresql/app-pgdump.md, src/app/docs/(postgres)/postgres/[slug]/page.jsx
Backups:
https://neon-next-git-dprice-pg-dump-pooled-connections-neondatabase.vercel.app/docs/manage/backups
Import from Postgres:
https://neon-next-git-dprice-pg-dump-pooled-connections-neondatabase.vercel.app/docs/import/import-from-postgres
Added a "NEON POSTGRES NOTE" to the PostgreSQL mirrored docs:
https://neon-next-git-dprice-pg-dump-pooled-connections-neondatabase.vercel.app/docs/postgres/app-pgdump
Updated the Neon compatibility note in the PostgreSQL docs mirror to indicate that "not all information" is applicable to Neon, and changed the link to one that addresses this specifically.
=> Add pg_dump note about pooled connections

content/docs/connect/connection-latency.md, content/docs/extensions/pg-extensions.md, content/docs/introduction/billing-calculators.md, content/docs/introduction/billing.md, content/docs/introduction/pro-plan.md, content/docs/sidebar.yaml
- Move Compatibilty page under Postgres in TOC
- Make Extensions page selectable in the TOC for visibility (change to "Supported extensions")
- Moved Neon extensions (neon, neon_utils) under Extensions (previously located in the Guides section)
- Note: I changed "Postgres guides" to just "Postgres" since we already have a Guides section (wdyt?)
https://neon-next-git-dprice-postgres-toc-change-neondatabase.vercel.app/docs/introduction
- Unrelated: Fixed some pricing calculator links that were broken
=> Postgres toc update

content/docs/extensions/pg_embedding.md, content/docs/extensions/pg_stat_statements.md, content/docs/guides/exograph.md, content/docs/import/import-from-postgres.md, content/docs/manage/roles.md
I noticed that our anchor link creation algo removes underscores, but some of our anchor links were including them. This change ensures that internal anchor links on headings with underscores take a user to the right position in page.
=> Docs: Remove underscores from anchors

content/docs/guides/vercel.md
Vercel has fixed the issue that prevented using the Neon Vercel integration with a second Vercel project. Remove the warning.
=> Remove Vercel integration warning

content/docs/guides/node.md
The examples given in the file were not consistent with the output gotten from the Neon console: For nodes.js the console is not giving a connection string but individual variables. The example program for postgres.js in the console is using those variables. Now both examples in this document are using them as well to be consistent with the console.
In addition removed the usage of the endpoint id from the example. It is no longer needed for pg and postgres.js. We should also remove them from the example in the console, I think.
Also made the two examples a bit more consistent.
=> Update node.md to make it consistent with the Neon console

content/docs/introduction/regions.md
`ap-southeast-2` -> `aws-ap-southeast-2`
https://neon-next-git-bayandin-patch-1-neondatabase.vercel.app/docs/introduction/regions
=> Fix Sydney region name

content/docs/functions/json_build_object.md, content/docs/functions/json_extract_path.md, content/docs/functions/json_extract_path_text.md, content/docs/functions/json_object.md, content/docs/functions/json_populate_record.md, content/docs/functions/jsonb_each.md, content/docs/functions/jsonb_extract_path_text.md, content/docs/functions/jsonb_object.md, content/docs/functions/jsonb_populate_record.md
When listing alternative functions for a postgres function, we link to neon docs when present.
=> docs(pages): link to neon docs when present

src/components/pages/blog-post/social-share/social-share.jsx
Adds the `via` attribute in SocialShare for Twitter.
=> chore: add twitter handle in via

content/changelog/2024-01-19-console.md, content/docs/extensions/pg-extensions.md, content/docs/introduction/plans.md, content/docs/introduction/support.md
This makes a couple updates to align docs and pricing page:
- Only Scale and Enterprise plans can load custom extensions. So we need to update a few places, including changelog, billing/plans, and pg-extensions
- `s/Expert/Standard/` Support - All support is expert support, based on Slack discussion, renaming "Expert" to "Standard" and aligning it with pricing page.
=> Docs: tweak to extensions and support in docs

content/docs/README.md, content/docs/guides/nextjs.md, package-lock.json, package.json, src/components/pages/blog-post/code-block/code-block.jsx, src/components/pages/blog-post/code-tabs/code-tabs-navigation.jsx, src/components/pages/blog-post/code-tabs/code-tabs.jsx, src/components/shared/admonition/admonition.jsx, src/components/shared/code-block-wrapper/code-block-wrapper.jsx, src/components/shared/code-block/code-block.jsx, src/lib/shiki.js, src/styles/blog-content.css, src/styles/highlighted-code.css
This pull request brings the highlight word for code snippets. It supports 4 types of transformers for now: 
- [transformerMetaHighlight](https://shiki.matsu.io/packages/transformers#transformermetahighlight),
- [transformerNotationHighlight](https://shiki.matsu.io/packages/transformers#transformernotationhighlight),
- [transformerNotationWordHighlight](https://shiki.matsu.io/packages/transformers#transformernotationwordhighlight)
**Changes**
- updated shiki dependency
**TODO**
**Steps**
1. Open [preview](https://neon-next-git-shiki-transformers-neondatabase.vercel.app/docs/guides/nextjs)
2. Check the highlighted word
=> feat: add highlight word for code snippets

content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md, content/docs/manage/endpoints.md, content/docs/reference/glossary.md
Add compute size soft limit of 7vCPU. Contact support if you want to use 8 vCPU.
Some adjustments to content where we mentioned/implied only supporting up to 7 vCPU.
We mention 8 on the Pricing page now.
=> Adjust compute sizes

content/docs/guides/rust.md
Just wanted to run the code under the Rust guide but having the command to install the dependencies readily available for copy-pasting would be more convenient.
=> Add Rust deps under guides

content/docs/import/import-from-postgres.md, content/docs/reference/glossary.md
This was a user request. We advise using an unpooled connection when performing a dump and restore. It was unclear to the user what pooled and unpooled connections are. This PR adds links to newly added glossary terms for pooled and unpooled connection strings.
Preview:
https://neon-next-git-dprice-clarify-pooled-unpooled-neondatabase.vercel.app/docs/import/import-from-postgres
=> Clarify pooled and unpooled connections for Postgres import docs

content/docs/connect/connect-postgres-gui.md
Remove PopSQL from the list of supported clients.
I sent an email to PopSQL. Hopefully, they will look into it.
=> SNI workaround for PopSQL no longer works

src/components/pages/blog-post/social-share/social-share.jsx
This PR brings GA events to track the Social Share buttons clicks on blog posts
=> chore: add gtag events for social share buttons

content/docs/serverless/serverless-driver.md
The not-null assertion operator is syntax specific to typescript, not native javascript or nodejs syntax
=> Update serverless-driver.md (fix not-null assertion operator `!`)

content/docs/introduction/billing-sample.md, content/docs/introduction/how-billing-works.md, content/docs/introduction/plans.md, content/docs/introduction/usage-metrics.md
We now allow extra storage to be purchased on the Launch plan @ $3.5 per 2 GiB
- Extra storage:
https://neon-next-git-dprice-launch-plan-update-neondatabase.vercel.app/docs/introduction/how-billing-works#extra-usage
- Revisions throughout billing content for this change
=> Update billing docs for "extra storage" on Launch plan

content/docs/import/import-intro.md
Fix the title of the MySQL migration card. Copy-paste error.
=> Fix MySQL migration docs card title

src/components/pages/pricing/plans/data/plans.json
This adds an overage rate of $3.5 per 10 GiB for the launch tier in the pricing details table.
=> Add Launch storage pricing

content/docs/guides/branch-restore.md
There was a typo in the existing redirect
=> Fix PITR guide 404

src/constants/blog.js
This PR adds pink color for the category "case studies" on Blog page and remove old not-usable constant. 
[preview 1](https://neon-next-git-color-neondatabase.vercel.app/blog/category/all-posts)
[preview 2](https://neon-next-git-color-neondatabase.vercel.app/blog/how-recrowd-uses-neon-autoscaling-to-meet-fluctuating-demand)
=> style: new color for blog category

content/docs/introduction/how-billing-works.md, content/docs/introduction/usage-metrics.md, content/docs/reference/glossary.md
- Change compute hours costs. $0.04 was for .25 vCPU. It's $0.16 for 1 vCPU.
- Link glossary terms for compute hours and active hours
=> Billing updates

src/components/pages/pricing/plans/data/plans.json
Update the link to Postgres extensions on the Pricing page.
This link provides a nicer categorized view of supported extensions:
[/docs/extensions/extensions-intro](https://neon.tech/docs/extensions/extensions-intro)
=> Better link for supported extensions

src/styles/blog-content.css
Adjust the text size of H3 headings for a mobile view in a blog article.
[Preview](https://neon-next-git-heading-size-neondatabase.vercel.app/blog/easily-anonymize-production-data-in-postgres)
=> style: mobile text size for h3 for blog article

src/components/pages/pricing/cta/cta.jsx
This PR fixes the [pricing](https://neon-next-git-pricing-cta-fix-neondatabase.vercel.app/pricing) cta heading render
=> fix: pricing cta heading

content/docs/serverless/serverless-driver.md
We currently have this callout in Serverless Driver docs: 
But it was confusing... Where is neonConfig coming from? Other examples in the page and GitHub led me to the answer but I think it's clearer to explicitly demonstrate how everything works together
=> Docs: Clarify where neonConfig comes from in serverless driver docs

src/components/pages/pricing/hero/hero.jsx, src/styles/doc-content.css
This pull request brings small updates:
- spacing for admonition paragraphs
- adds aws label to launch card on pricing page
- open previews ([docs](https://neon-next-git-fix-admonition-add-pricing-label-neondatabase.vercel.app/docs/guides/polyscale-integration), [pricing](https://neon-next-git-fix-admonition-add-pricing-label-neondatabase.vercel.app/pricing))
- make sure that everything looks and works as expected
=> chore: admonition spacing, add aws label

content/docs/get-started-with-neon/query-with-neon-sql-editor.md, content/docs/guides/schema-diff-tutorial.md, content/docs/guides/schema-diff.md, content/docs/guides/time-travel-assist.md, content/docs/guides/time-travel-tutorial.md
The FF is now open for all users for schema diff, time travel, and /d commands. Removing the <ComingSoon/> admonition from relevant locations.
=> Removing the ComingSoon admonition from GA features

content/docs/guides/branching-neon-cli.md, content/docs/reference/cli-branches.md
Adjust CLI examples, as suggested:
Reset branch example:
https://neon-next-git-dprice-update-cli-reset-resto-b97477-neondatabase.vercel.app/docs/reference/cli-branches#example
Restore branch example:
https://neon-next-git-dprice-update-cli-reset-resto-b97477-neondatabase.vercel.app/docs/reference/cli-branches#restoring-a-branch-to-an-earlier-point-in-its-own-history-with-backup
=> Adjust CLI reset and restore examples

content/docs/introduction/plans.md
Differentiate titles so you can have direct links to plan subsections
https://neon-next-git-dprice-update-plan-links-neondatabase.vercel.app/docs/introduction/plans
=> docs: Fix plan links

content/docs/sidebar.yaml, content/postgresql/data-types-intro.md, content/postgresql/functions-intro.md, content/postgresql/postgres-intro.md, content/postgresql/query-performance.md, content/postgresql/query-reference.md
This pull request partially resolves the issue of a 404 error by moving the PostgreSQL files from content/docs/postgres to content/postgresql.
- open [preview](https://neon-next-git-mv-postgres-files-neondatabase.vercel.app/docs/postgres/postgres-intro)
- make sure that page is working
=> chore: mv postgres files

src/app/(home-page)/home/page.jsx
Instead of deploying the console redirect in a single step, let's first add the `neon.tech/home` page so that console can add a link back to it here https://github.com/neondatabase/cloud/pull/13441
=> Add /home clone in preparation for console redirect

package-lock.json, package.json, src/lib/graphQLClient.js, src/utils/api-auth.js, src/utils/api-pages.js, src/utils/api-posts.js
This pull request adds a wrapper for GraphQL requests to include retry logic. The wrapper ensures that requests are automatically retried in case of failure, enhancing the reliability of our GraphQL operations.
**Steps to check:**
- open the preview environment (including [blog](https://neon-next-git-retry-gql-neondatabase.vercel.app/blog) and other pages with WordPress functionality);
- ensure that all pages and functionalities are working correctly.
=> feat: add retry graphql

content/docs/get-started-with-neon/frameworks.md, content/docs/get-started-with-neon/languages.md, content/docs/guides/integrations.md, src/components/pages/doc/technology-navigation/technology-navigation.jsx
Helps get rid of the extra step required **always** to browse through the list of guides with neon: https://neon.tech/docs/get-started-with-neon/frameworks.
=> docs: do not hide all the framework guides behind a toggle

content/docs/sidebar.yaml
The "Integrations > Tools" section was duplicated in the TOC.
=> docs: remove duplicate tools section from toc

src/components/shared/footer/footer.jsx
This pull request adds target blank for footer external links.
**References**
[Preview](https://neon-next-git-fix-footer-external-links-neondatabase.vercel.app/)
=> fix: add target blank for footer external links

src/components/pages/home/instant-provisioning/code-tabs/navigation/navigation.jsx, src/components/pages/partners/integration/api/code-tabs/code-tabs-navigation.jsx, src/components/shared/code-block-wrapper/code-block-wrapper.jsx
This pull request brings fixes for code blocks scrollbars and copy buttons.
<details>
<summary>Code blocks scrollbars</summary>
[Partners](https://neon-next-git-fix-code-blocks-neondatabase.vercel.app/partners) - "Full automation with the Neon API" section - "Node" tab
Before
After
</details>
<details>
<summary>Copy buttons</summary>
[Homepage](https://neon-next-git-fix-code-blocks-neondatabase.vercel.app/) - "Works with your stack" section - "Go" tab
Before
After
</details>
**References**
[Preview](https://neon-next-git-fix-code-blocks-neondatabase.vercel.app/)
=> fix: code blocks scrollbars and copy buttons

CODEOWNERS
This pull request introduces a minor change to the CODEOWNERS file, replacing @k8isdead with @americano98 as the code owner.
=> chore: update owners

content/docs/introduction/roadmap.md
Taking in a suggestion by a customer, this PR fixes isreal typo on the brief history of Neon section.
=> docs: fix typo on brief history of neon section

src/components/pages/landing/hero/form/form.jsx, src/components/shared/lines-illustration/lines-illustration.jsx
This PR brings fix for line illustrations for forms
**Previews**
[Preview Blog](https://neon-next-git-fix-line-illustrations-neondatabase.vercel.app/blog)
[Preview Landing 1](https://neon-next-git-fix-line-illustrations-neondatabase.vercel.app/early-access-program)
[Preview Landing 2](https://neon-next-git-fix-line-illustrations-neondatabase.vercel.app/scale-trial)
=> fix: line illustrations for forms

content/docs/get-started-with-neon/frameworks.md, content/docs/get-started-with-neon/languages.md, content/docs/guides/integrations.md, src/components/pages/doc/technology-navigation/technology-navigation.jsx
This PR brings fix for docs technology navigation toggler https://github.com/neondatabase/website/pull/1719
**Steps to test**
**Previews**
[Preview](https://neon-next-git-fix-docs-tech-toggler-neondatabase.vercel.app/docs/introduction) (default state)
[Preview](https://neon-next-git-fix-docs-tech-toggler-neondatabase.vercel.app/docs/get-started-with-neon/frameworks) (no toggler state)
=> fix: docs technology navigation toggler

content/docs/manage/endpoints.md
If you are using Autoscaling, it is important to remember that your max_connections setting is based on the minimum compute size in your autoscaling configuration. The max_connections setting does not scale with your compute.
=> docs: highlight minimum compute size

src/styles/highlighted-code.css
This PR brings slight color updates for the new shiki code transformers
**Screenshot**
[Preview](https://neon-next-git-fix-code-transformers-styles-neondatabase.vercel.app/guides/feature-flags-sveltekit#optional-adding-tailwind-css-to-the-application)
=> fix: code transformers colors

content/docs/connect/connection-pooling.md
If you are using Autoscaling, it is important to remember that your max_connections setting is based on the minimum compute size in your autoscaling configuration. The max_connections setting does not scale with your compute.
=> docs: mark compute size as minimum

next.config.js, vercel.json
This PR makes /regional-latency a path on neon.tech. It points to: https://latencies-ui.vercel.app/
=> feat: add rewrite for latency dashboard

content/docs/extensions/neon.md
you cannot query the postgres database for LFC stats
=> docs: remove incorrect information from neon extension doc

content/docs/guides/django.md, content/docs/guides/integrations.md, content/docs/guides/laravel.md, content/docs/guides/rails-migrations.md, content/docs/guides/ruby-on-rails.md, content/docs/guides/sqlalchemy.md, content/docs/sidebar.yaml
- drop polyscale guide
- reorganize integrations section to align with revised Integrations page categories 
- Add references to schema migration guides from framework guides (e.g. Django guide -> Django migration guide)
=> docs: guides updates

next-sitemap.config.js, src/components/shared/header/header.jsx
This pull request fixed the issue causing `sitemap-0.xml` to break.
Removed the cookie check in the header component temporarily as it was triggering issues with `sitemap-0.xml`. This is a temporary measure until a more permanent solution is implemented.
- open [sitemap](https://neon-next-git-rm-check-from-header-neondatabase.vercel.app/sitemap.xml), [sitemap-0.xml](https://neon-next-git-rm-check-from-header-neondatabase.vercel.app/sitemap-0.xml) preview
- make sure that everything work as expected
=> fix: restore functionality of sitemap-0.xml

src/app/fonts.js
This PR brings global fixes for font weights in Safari and Firefox
<details><summary>Safari</summary>
</details>
<details><summary>Firefox</summary>
</details> 
[Preview](https://neon-next-git-fonts-fix-firefox-safari-neondatabase.vercel.app/docs/introduction)
=> fix: add missing font weights

src/app/[slug]/page.jsx
This PR brings fix for broken metadata for landing pages after plugins update
[Preview](https://neon-next-git-fix-landing-metadata-neondatabase.vercel.app/scale-trial)
=> fix: broken landing metadata after plugins update

src/components/shared/header/header.jsx
This PR brings lost property for sticky header at #1738
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
[Preview](https://neon-next-git-fix-sticky-header-neondatabase.vercel.app/)
=> fix: lost header sticky property

.github/workflows/format-markdown.yml, .github/workflows/update-frontmatter.yml, content/README.md, content/docs/community/contribution-guide.md
This PR brings fix for workflow actions by adding the `pull` script
[Test trigger](https://github.com/neondatabase/website/actions/runs/9513632933/job/26224146845) with no significant changes to commit
=> fix: add pull script to workflow actions

content/changelog/2024-06-14.md, content/docs/reference/cli-auth.md, content/docs/reference/cli-branches.md, content/docs/reference/cli-install.md, content/docs/reference/neon-cli.md
- mention new --no-color option in reference and changelog
- order install commands by platform (macOS, Windows, Linux) to be consistent with the website CLI page
- Add schema-diff command options table
- mention npx, bunx no-install usage options
=> Neon cli updates

src/components/pages/cli/hero/code-tabs/code-tabs-navigation.jsx, src/components/pages/cli/hero/code-tabs/code-tabs.jsx
We'd like to show only the CLI installation command, which was suggested by @m-abdelwahab (mockup shown below)
The change in the PR fails to shrink the height of the tabbed codeblock.
=> docs: modify cli page to show install command only

src/styles/search.css
This PR brings fix for docs search cursor.
Before we had a bug with the Docs Search modal, it was whole with cursor-pointer. Now it's fixed. 
[Preview](https://neon-next-git-fix-docs-search-cursor-neondatabase.vercel.app/docs/introduction)
=> fix: docs search cursor

content/docs/guides/laravel.md
A developer on Discord pointed out that `DB_SSLMODE` is not needed. Removing it.
=> docs: Fix Laravel .env guidance for latest version

content/docs/introduction/support.md
Fix broken links on the support page
=> docs: fix pricing plan links on support page

content/docs/guides/cloudflare-pages.md, content/docs/guides/cloudflare-workers.md, content/docs/guides/deno.md, content/docs/guides/heroku.md, content/docs/guides/netlify-functions.md, content/docs/guides/railway.md, content/docs/guides/render.md
Add source code cards to deploy topics so that users can access the source code for our deployment platform examples.
=> docs: add source code cards to deploy topics

next.config.js
Renamed the slug of this blog post: https://neon.tech/blog/the-non-obviousness-of-postgres-roles to https://neon.tech/blog/postgres-roles
and need to manually add a redirect
=> Add Blog post redirect

content/docs/reference/cli-create-app.md
create-app now supports Prisma
create-app now generates 2 separate branches for apps (dev branch and deployment branch)
=> docs: update cli docs for create-app updates

content/docs/guides/typeorm.md, content/docs/shared-content/index.js, content/docs/shared-content/pg-hint.md
I'm looking to add a hint for all the users (**it's not a 100% verified claim**) using pg-wrapped libraries to use this environment variable, such as in TypeORM (already existing doc) and Knex (an upcoming PR).
=> docs: hint switch to pg-native for performance improvement with pg-wrapped libraries

src/components/pages/blog/sidebar/sidebar.jsx
This pull request implements a fix that resolves the redundant vertical scrolling for blog categories on mobile devices.
- open the [preview](https://neon-next-git-fix-blog-category-scroll-neondatabase.vercel.app/blog) on a mobile device
- ensure that the categories can only be scrolled horizontally (X-axis)
=> fix: redudant scroll

src/app/cost-fleets/page.jsx, src/app/guides/(index)/page.jsx, src/app/guides/og/route.jsx, src/components/pages/guides/guide-card/guide-card.jsx
This pull request introduces several small updates, including:
- Updated button source in the CTA section of the costs fleets page (to sign up)
- Improved OG image generation for guides
- Aligned links on the guides cards
- open preview ([guides](https://neon-next-git-small-fixes-070824-neondatabase.vercel.app/guides), [og](https://neon-next-git-small-fixes-070824-neondatabase.vercel.app/guides/og?title=SW1wbGVtZW50aW5nIFNvZnQgRGVsZXRlcyBpbiBMYXJhdmVsIGFuZCBQb3N0Z3Jlcw==), [costs fleets](https://neon-next-git-small-fixes-070824-neondatabase.vercel.app/cost-fleets))
- make sure that everything looks and works as expected
=> Small fixes for guides and costs fleets

src/components/shared/header/header.jsx
This PR brings fix for header styles support for dark header on light mode pages
[Preview](https://neon-next-git-fix-header-styles-neondatabase.vercel.app/careers)
=> fix: header styles support for dark header on light mode pages

src/components/pages/pricing/plans/table/table.jsx
This PR brings feature for Pricing Page by auto-opening pricing table if we have #plans anchor in url
[Preview](https://neon-next-git-pricing-page-anchor-link-neondatabase.vercel.app/pricing#plans)
=> feat: open pricing table by #plans anchor in url

src/constants/links.js
This PR changes Trust constant link to external to resolve CORS issue
[Preview](https://neon-next-git-trust-link-fix-neondatabase.vercel.app/)
=> chore: trust link fix

src/components/pages/about/leadership/leadership.jsx
This PR brings typo fixing. Redundant period removed from About Us Page.
Preview is [here](https://neon-next-git-fix-about-us-page-bug-neondatabase.vercel.app/about-us)
=> fix: remove redundant period

content/docs/guides/logical-replication-guide.md, content/docs/introduction/logical-replication.md
I've noticed a typо while reading a guide on logical replication https://neon.tech/docs/guides/logical-replication-guide
=> Fix a typo in logical replication guide

src/app/docs/(neon)/changelog/[...slug]/page.jsx
This PR brings fix for Changelog single page layout on updated docs
[Preview](https://neon-next-git-fix-changelog-layout-neondatabase.vercel.app/docs/changelog/2024-08-16)
=> fix: changelog single page layout

src/app/docs/(neon)/changelog/[...slug]/page.jsx
This PR brings fix for Changelog single page layout on updated docs
[Preview](https://neon-next-git-fix-changelog-layout-neondatabase.vercel.app/docs/changelog/2024-08-16)
=> fix: changelog single page layout tablets

content/docs/get-started-with-neon/production-checklist.md
Connectin -> Connection
Trivial documentation edit with no functional changes.
Misspelling.
=> Fix typo in docs

content/docs/guides/vercel.md
I was using the Inkeep ask AI functionality on the neon docs and noticed this issue with the documentation.
Hopefully this docs fix will help others with their Neon-Vercel Integration understanding and setup.
=> Update vercel.md to show correct neon branch prefix for preview branches

src/app/docs/(neon)/layout.jsx, src/app/docs/(postgres)/layout.jsx, src/app/guides/(index)/page.jsx, src/app/guides/[slug]/page.jsx, src/app/provider.jsx, src/components/shared/footer/footer.jsx, src/components/shared/footer/status-badge/status-badge.jsx, src/components/shared/layout/layout.jsx
This PR brings refactor for themes support for docs and guides
- [Docs](https://neon-next-git-add-themes-for-guides-neondatabase.vercel.app/docs)
- [Guides](https://neon-next-git-add-themes-for-guides-neondatabase.vercel.app/guides)
[Preview](https://neon-next-git-add-themes-for-guides-neondatabase.vercel.app/)
=> refactor: themes support for docs and guides

src/utils/api-docs.js
This PR fixes #2081 where clicking the “Next Page” link on the “Why-Neon” & ”1 - Playing with Neon” pages incorrectly redirected the user back to the same page. The bug was caused by an issue in the `getNavigationLinks` function. In this function, the `posts` array has duplicated slug values in it, after constructed.
=> fix: remove duplicate slugs causing incorrect navigation links

src/app/(home-page)/layout.jsx, src/components/pages/doc/menu/menu.jsx, src/components/shared/header/header-wrapper/header-wrapper.jsx
This PR brings the following:
- New styles for Header bottom border
- Setting menu animation to zero
- Vanishing of menu headings icons
Preview is [here](https://neon-next-git-add-line-to-header-neondatabase.vercel.app/)
=> Add underline to header, fix side menu

src/components/pages/scalable-architecture/hero/hero.jsx
This PR fixes the typo on page `/scalable-architecture` 
> SAAS to SaaS
[Preview](https://neon-next-git-fix-typo-neondatabase.vercel.app/scalable-architecture)
=> chore: fix typo on scalable-architecture page

package-lock.json, package.json, src/app/layout.jsx, src/components/shared/region-request/region-request.jsx
This pull request brings the sitemap fix by getting rid of `next-client-cookies`, checking cookie using a function on client side. 
https://github.com/iamvishnusankar/next-sitemap/pull/812#issuecomment-2231707718
Preview: https://neon-next-git-sitemap-fix-neondatabase.vercel.app/sitemap-0.xml
=> fix: remove next-client-cookies to enable sitemap

content/docs/get-started-with-neon/production-checklist.md, content/docs/guides/logical-replication-tips.md, content/docs/introduction/point-in-time-restore.md, content/docs/manage/projects.md, content/docs/reference/glossary.md
Preview:
- [Configure history retention (production checklist page)](https://neon-next-git-bgrenon-history-retention-default-neondatabase.vercel.app/docs/get-started-with-neon/production-checklist#configure-your-history-retention-period)
- [Configure history retention (manage computes page)](https://neon-next-git-bgrenon-history-retention-default-neondatabase.vercel.app/docs/manage/projects#configure-history-retention)
- [Branch reset and restore](https://neon-next-git-bgrenon-history-retention-default-neondatabase.vercel.app/docs/introduction/point-in-time-restore)
- [Point-in-time-restore (glossary)](https://neon-next-git-bgrenon-history-retention-default-neondatabase.vercel.app/docs/reference/glossary#point-in-time-restore)
=> Add 1 day default for history retention configuration

src/lib/inkeep-settings.js
This PR replaces Inkeep search placeholder from "Search for anything" to "Search"
**Screenshot**
=> fix: replace inkeep search placeholder

src/components/pages/doc/menu/menu.jsx, src/components/pages/doc/mobile-nav/mobile-nav.jsx, src/components/pages/doc/sidebar/sidebar.jsx
This PR brings refactor for docs sidebar menu without animations
- fix issue with menu height change delay for nested menus
- optimize code, remove Framer Motion from menu
[Preview](https://neon-next-git-docs-sidebar-no-animations-neondatabase.vercel.app/docs/introduction)
=> refactor: docs sidebar menu without animations

content/docs/introduction.md, src/components/shared/doc-cta/doc-cta.jsx
This PR updates Docs home page CTA section styles
CTA blocks on other pages (for example [AI](https://neon-next-git-docs-home-cta-neondatabase.vercel.app/docs/ai/ai-intro) page) are not changed
[Preview](https://neon-next-git-docs-home-cta-neondatabase.vercel.app/docs/introduction)
=> feat: update docs home cta styles

content/docs/sidebar.yaml
Linking to content from a different section in the sidebar causes navigation issues. Revert changes.
=> docs: remove duplicate links

content/docs/get-started-with-neon/production-checklist.md, content/docs/introduction/roadmap.md
A candidate for the support role found these typos when reading through the docs.
=> docs: fix typos

next.config.js
Hi @k8isdead / team. We've changed the name of Twin Thing. It will now live on a different link. I've made changes to update the rewrite so the final URL will be: https://neon.tech/dev-for-rds
=> refactor: remove twin-thing add dev-for-rds rewrite

src/components/pages/doc/edit-on-github/edit-on-github.jsx
This PR updates "Edit this page on GitHub" link
[Preview](https://neon-next-git-update-github-link-neondatabase.vercel.app/docs)
=> chore: edit-on-github link

src/components/pages/doc/detail-icon-cards/detail-icon-cards.jsx
This PR brings style fixes for docs detail icon cards:
- `text-wrap: balance` for title and description
- monochrome icons support (only **github** so far)
[Preview](https://neon-next-git-docs-detail-icon-cards-neondatabase.vercel.app/docs/guides/nextjs)
=> fix: docs detail icon cards text wrap and monochrome icons

src/constants/menus.js
This PR updates the title and description of partners link in the header menu.
Before | After
-- | --
Neon for Platforms | Partners
Postgres for your users | Add Neon to your platform
=> chore: update partners subline in header menu

src/components/pages/doc/menu/menu.jsx, src/components/pages/doc/sidebar/sidebar.jsx
This PR brings fix for docs sidebar scrolling issue
**Steps to test:**
- open different sidebar menus and make sure they don't have an extra scrolling
- open mobile menu and make sure it scrolls as expected as well
[Preview](https://neon-next-git-docs-sidebar-scroll-fix-neondatabase.vercel.app/docs)
=> fix: docs sidebar scrolling issue

content/docs/guides/vercel.md
Add note to Vercel docs about obsolete branches not being deleted due to child branch
Support issue: https://neon.zendesk.com/agent/tickets/3601
Preview:
https://neon-next-git-dprice-avoid-child-branches-o-3513e5-neondatabase.vercel.app/docs/guides/vercel#automatic-deletion
=> docs: avoid child branches on preview branches

content/docs/connect/connection-errors.md, content/docs/connect/connection-pooling.md
Connection pooling section about transaction mode and SET:
https://neon-next-git-dprice-set-transaction-mode-neondatabase.vercel.app/docs/connect/connection-pooling#connection-pooling-in-transaction-mode
Relation not found error:
https://neon-next-git-dprice-set-transaction-mode-neondatabase.vercel.app/docs/connect/connection-errors#relation-not-found
=> docs: add info about using set in transaction mode

content/docs/extensions/pg-extensions.md
Mention that pg_search is not supported:
https://neon-next-git-dprice-pg-search-extension-note-neondatabase.vercel.app/docs/extensions/pg-extensions#extension-support-notes
=> docs: add pg_search to non-supported list

content/docs/guides/oauth-integration.md
Added scopes for Organizations plus a couple other suggested clarifications.
Preview:
https://neon-next-git-bgrenon-oauth-orgs-neondatabase.vercel.app/docs/guides/oauth-integration
=> Add orgs scopes to OAuth integration docs

src/components/pages/pricing/hero/hero.jsx
This PR updates links for plans on Pricing page to 
https://console.neon.tech/app/billing#plans
[Preview](https://neon-next-git-pricing-page-urls-neondatabase.vercel.app/pricing)
=> chore: update pricing page links for plans

src/app/actions.js
This PR brings optimizations to reduce "429 Too Many Requests" errors by:
- caching checkCookie results within the request lifecycle
- memoizing the getReferer to avoid multiple lookups
=> fix: optimize cookie and referer checks to prevent 429 errors

content/docs/get-started-with-neon/signing-up.md, content/docs/guides/auth-clerk.md, content/docs/guides/branch-restore.md, content/docs/guides/deno.md, content/docs/guides/netlify-functions.md, content/docs/guides/railway.md, content/docs/guides/render.md, content/docs/guides/schema-diff-tutorial.md, content/docs/guides/wundergraph.md, content/guides/fastapi-async.md, src/components/pages/about/investors/investors.jsx, src/components/pages/variable/efficiency/efficiency.jsx, src/scripts/update-frontmatter.js
This PR fixes the spelling for the word "GitHub" (it makes "h" capitalised).
I've split changes into 2 commits — changes in markdown files (I did it automatically) and changes in js(x) files (I did apply them manually)
=> Spelling: Github -> GitHub

content/docs/guides/deno.md
- Updated the doc to use [neon serverless driver](https://jsr.io/@neon/serverless) from [jsr](https://jsr.io/) package registry instead of [deno-postgres](https://deno.land/x/postgres@v0.19.3)
=> docs: use jsr package in deno docs

content/guides/react-fastapi-rag-portfolio.md, content/guides/timescale-fastapi.md
Weird issue where when the Prettier bot formats the md guides, it undoes the <CodeTabs> block triple backticks, and replaces them with oddly formatted single backticks. If I indent the CodeTabe block once more than it should be, Prettier leaves it as is, and it still renders the same on the website
=> docs: fixed guide formatting issues caused by prettier

content/docs/guides/nextjs.md
this PR fixes a minor grammer issue in [Next.js Guide](https://neon.tech/docs/guides/nextjs)
=> docs(guide): fix grammer

content/docs/guides/neon-private-access.md
Added name of the VPC endpoint service for us-east-2 to the documentation. The region was requested by a POC customer.
See https://github.com/neondatabase/cloud/issues/18304.
See [the POC definition](https://www.notion.so/neondatabase/Neon-Private-Access-POC-Proposal-8f707754e1ab4190ad5709da7832f020?d=887495c15e884aa4973f973a8a0a582a#7ac6ec249b524a74adbeddc4b84b8f5f) for details about the POC scope.
=> Added VPC endpoint service name for us-east-2 to documentation

content/docs/guides/liquibase.md, content/docs/guides/logical-replication-alloydb.md, content/docs/guides/logical-replication-kafka-confluent.md, content/docs/guides/neon-features.md, content/docs/import/import-sample-data.md, content/docs/import/migrate-aws-dms.md, content/docs/import/migrate-schema-only.md, content/docs/introduction/monitoring-page.md, content/docs/reference/feeds.md, content/docs/reference/sdk.md, content/guides/chatbot-astro-postgres-llamaindex.md, content/guides/next-server-actions.md, content/postgresql/postgresql-csharp/postgresql-csharp-import-csv-file.md, content/postgresql/postgresql-php/postgresql-blob.md, content/postgresql/postgresql-string-functions/postgresql-chr.md, content/postgresql/postgresql-tutorial/postgresql-cube.md, content/postgresql/postgresql-tutorial/postgresql-rename-table.md, content/postgresql/postgresql-tutorial/postgresql-union.md
Corrected instances of duplicated "the" across multiple files to improve readability.
=> fix(docs): remove duplicate the from sentences in documentation

content/docs/guides/neon-authorize-troubleshooting.md
Preference is to use error messages as heading equivalent on this page, which breaks the rightnav.
This is a workaround to give a list of errors a the top of the page; each error links to an anchor in the relevant section.
=> docs: add error list and links to top of page

content/docs/guides/neon-private-access.md
- It was not clear that the method for blocking internet access by using 0.0.0.0 as the IP allowlist is only temporary. Tried to make that clearer.
- Also clarified that manual acceptance of the VPC endpoint is only temporary as well.
=> Clarified that some steps are specific to the private preview of Private Access

src/components/pages/pricing/hero/data/plans.json
This PR brings fix for pricing page hero plans links
[Preview](https://neon-next-git-pricing-page-links-neondatabase.vercel.app/pricing)
=> fix: pricing page hero plans links

src/app/signup/page.jsx
This is a little page that we can use like https://neon.tech/signup?ref=psql.sh and it will log a pageview before redirecting to https://console.neon.tech/signup so we can properly attribute signups.
=> Add a signup redirect that logs a pageview

src/components/pages/pricing/hero/data/plans.json
This PR changes text for "pay via aws" links on Pricing Page
Preview
=> chore: rename "pay via aws" links on pricing page

content/docs/guides/local-development-with-neon.md, content/guides/local-development-with-neon.md
- Add guide for local development with Neon
=> docs: add local development with neon

src/app/guides/[slug]/page.jsx
This PR adds authors info for guides metadata for algolia search
[Preview](https://neon-next-git-guides-metadata-authors-neondatabase.vercel.app/guides/vercel-sdk-migration)
=> feat: add authors info for guides metadata for algolia search

content/docs/reference/compatibility.md
The default Postgres version is visible in the UI. We don't need to mention it in this one place in the docs. This avoids having to update it with each default change.
=> docs: remove default mention

src/components/shared/footer/footer.jsx
This PR brings fix for Compliance section icons to inline with other menus
Reference PR: https://github.com/neondatabase/website/pull/2481
[Preview](https://neon-next-git-fix-footer-styles-neondatabase.vercel.app/)
=> fix: footer compliance section icons

content/docs/guides/neon-authorize-stack-auth.md
The example route is missing the `/api` prefix, causing a 404 Not Found error (after substituting a valid project ID)
=> docs: add missing /api prefix to stack-auth jwks example route

content/postgresql/postgresql-tutorial/postgresql-select-distinct.md
The description of the `bcolor` column mistakenly referred to "read" instead of "red." This commit corrects the typo for clarity and accuracy in the documentation.
=> docs: fix typo in postgres-select-distinct page

content/docs/guides/vercel-overview.md
The documentation was incorrectly linked to the wrong setup instructions.
=> Fix incorrect URL

content/docs/guides/neon-authorize-auth0.md, content/docs/guides/neon-authorize-clerk.md, content/docs/guides/neon-authorize-stack-auth.md
- Replace `pgPolicy` with `crudPolicy`
preview:
- https://neon-next-git-fork-dhanushreddy291-update-d-649b06-neondatabase.vercel.app/docs/guides/neon-authorize-clerk#1-add-row-level-security-policies
- https://neon-next-git-fork-dhanushreddy291-update-d-649b06-neondatabase.vercel.app/docs/guides/neon-authorize-stack-auth#1-add-row-level-security-policies
- https://neon-next-git-fork-dhanushreddy291-update-d-649b06-neondatabase.vercel.app/docs/guides/neon-authorize-stack-auth#1-add-row-level-security-policies
=> docs: replace pgpolicy with crudpolicy

content/docs/introduction/regions.md
Adds public IPs for NAT gateways in prod Azure `gwc` and `westus3`.
=> add NAT gateway documentation for new Azure regions

src/components/pages/doc/menu/icon/icon.jsx, src/icons/docs/sidebar/azure.inline.svg
This PR brings Azure icon for docs sidebar
=> chore: add azure icon for docs sidebar

content/docs/guides/logical-replication-neon.md
With this PR: https://github.com/neondatabase/neon/pull/9896 we changed the neon.logical_replication_max_snap_files default from 300 to 10000. My assumption is that this increases the amount of time before we drop an inactive slot from 75 minutes to 2500 minutes (41.6 hours)
Can you please review?
=> docs: inactive replication slot drop

content/postgresql/postgresql-tutorial/postgresql-where.md
The example description for the LENGTH() function incorrectly used "gets" instead of "to get". This commit improves the grammar for enhanced clarity.
Before:
"In this example, we use the LENGTH() function gets the number of characters of an input string."
After:
"In this example, we use the LENGTH() function to get the number of characters of an input string."
=> docs: fix grammar in BETWEEN example conclusion

content/postgresql/postgresql-tutorial/postgresql-where.md
The sentence "cause the condition evaluates to true" has been corrected to "cause the condition to evaluate to true".
Before:
"In other words, the query will include only rows that cause the condition evaluates to true in the result set."
After:
"In other words, the query will include only rows that cause the condition to evaluate to true in the result set."
=> docs: fix grammar in explanation of the WHERE clause

content/postgresql/postgresql-tutorial/postgresql-where.md
Corrected the phrase "with the first name is Jamie" to "whose first name is Jamie" in the WHERE clause and equal example description.
=> docs: fix grammatical error in WHERE clause and equal example description

src/components/pages/careers/hero/hero.jsx, src/components/pages/careers/jobs-list/jobs-list.jsx
This PR removes image from careers page
[Preview](https://neon-next-git-careers-page-hero-neondatabase.vercel.app/careers)
=> chore: remove hero image from careers page

next.config.js
This PR brings **temporary** redirect for changelog page
`/changelog` -> `/docs/changelog`
[Preview](https://neon-next-git-changelog-temp-redirect-neondatabase.vercel.app/changelog)
=> chore: add temporary redirect for changelog

src/components/pages/pricing/hero/data/plans.json, src/components/pages/pricing/hero/hero.jsx
This PR brings adds Azure to pricing plans payment methods
TODO:
[Preview](https://neon-next-git-pay-via-azure-pricing-page-neondatabase.vercel.app/pricing)
=> chore: add Azure to pricing plans payment methods

src/app/postgresql/layout.jsx, src/components/shared/header/header.jsx, src/components/shared/inkeep-trigger/inkeep-trigger.jsx, src/components/shared/layout/layout.jsx, src/lib/inkeep-settings.js
When a user is on the PGT pages at neon.tech/postgresql/tutorial the search should default to filtering only to that section https://neon-next-git-ruf-io-inkeep-filters-neondatabase.vercel.app/postgresql/tutorial
When a user is on the docs at neon.tech/docs the search should default to filtering only docs. 
https://neon-next-git-ruf-io-inkeep-filters-neondatabase.vercel.app/docs/introduction
=> InKeep: filter search to current section

.env.example
#0
It was a bad idea to put production Posthog key into `.env.example` :)
=> chore: remove posthog production key from env example

src/components/pages/home/hero/hero.jsx, src/components/shared/button/button.jsx, src/components/shared/header/header.jsx
Relates to https://linear.app/neondb/issue/GRW-290/experiment-build
Add 2 required for the experiment events:
- `header_sign_up_clicked`
- `home_hero_get_started_clicked`
=> chore: add sign up events

src/app/(home-page)/home/page.jsx, src/app/(home-page)/page.jsx, src/middleware.js
This PR refactors homepage redirects, moving them to middleware
reference: https://github.com/neondatabase/website/pull/2585
basic concepts:
- Root Path (`/`): In production, if the user is logged in, they are redirected to /home if the referer matches the current branch or default site URL; otherwise, they are redirected to the console.
- Home Path (`/home`): Users not logged in are redirected to the root path (/).
[Preview](https://neon-next-git-move-redirects-to-middleware-neondatabase.vercel.app/)
=> refactor: move redirects from homepage to middleware

src/app/(home-page)/page.jsx
we no more require the logic to run on homepage specifically, hence no need to revalidate.
=> remove revalidate from homepage

src/components/pages/pricing/plans/data/plans.json
Relates to https://linear.app/neondb/issue/GRW-327/turn-autosuspend-into-a-single-toggle-that-says-scale-to-zero
UPD: Text replaced by check marks:
=> chore: update scale to zero feature description

content/guides/local-development-with-neon.md
Fix #2651
This PR updates the configuration for the local Neon Proxy to use the `v2` API version, resolving compatibility errors in local environments.  
- Updated `neonConfig.wsProxy` to use `v2` endpoint:  
```ts
neonConfig.wsProxy = (host) =>
host === "db.localtest.me" ? `${host}:4444/v2` : host + "/v2";
```  
- The `v1` API is outdated and causes errors when working with the local proxy.  
- Switching to `v2` aligns with the latest Neon serverless driver compatibility.  
- Verified local development flow with the updated configuration.  
- Successfully connected to the local Neon Proxy without errors.
=> fix: update Neon Proxy API to use `v2` in Local Development

content/docs/guides/auth-auth0.md
Update auth0 integration docs with drizzle.
For `Config` from `drizzle-kit`...
1. `pg` is no longer assignable to `Config["driver"]` see https://orm.drizzle.team/docs/drizzle-config-file#driver
2. `connectionString` is not a key of `Config["dbCredentials"]` see https://orm.drizzle.team/docs/drizzle-config-file#dbcredentials
For `drizzle-kit` commands, the commands appear to be deprecated.
```shell
❯ npx drizzle-kit generate:pg
This command is deprecated, please use updated 'generate' command (see https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210)
```
Running the commands without the `:pg` appeared to run successfully and created the table in the neon DB. `pg` appears to still run under the covers.
```shell
❯ npx drizzle-kit push
No config path provided, using default …
```
=> Update Outdated neon+auth0+drizzle Integration Docs

content/postgresql/postgresql-tutorial/postgresql-having.md
https://neon.tech/postgresql/postgresql-tutorial/postgresql-having has next link as https://neon.tech/postgresql/postgresql-tutorial/postgresql-union but sidebar indicates that next link should be postgresql-grouping-sets
=> Update correct next link in postgresql-having.md

content/postgresql/postgresql-tutorial/postgresql-and.md
- Updated the logical operator "and" to the uppercase "AND" for consistency and correctness in the PostgreSQL documentation.
=> Fix: Correct case of "and" to "AND" in postgresql-and.md

content/postgresql/postgresql-tutorial/postgresql-subquery.md
- from to FROM
- where to WHERE
=> Fix: Correct case of "from" to "FROM" and "where" to "WHERE" in postgresql-subquery.md

content/docs/guides/schema-diff-tutorial.md, content/docs/guides/schema-diff.md
Schema diff topic update:
https://neon-next-git-dprice-schema-diff-api-neondatabase.vercel.app/docs/guides/schema-diff#using-the-neon-api
Schema diff tutorial update to include API tabs:
https://neon-next-git-dprice-schema-diff-api-neondatabase.vercel.app/docs/guides/schema-diff-tutorial
Note: The compare-schema API is not public yet. I still need to add a link to the endpoint in the API Ref.
=> docs: schema diff api docs

content/postgresql/postgresql-date-functions/postgresql-current_timestamp.md
Fixed multiple typos of `TIMESTAMP`
=> docs: 📝 Fix typos of 'Timestamp'

content/docs/guides/neon-authorize.md
Some changes to the database roles description to address customer confusion i.e, in this ticket:
https://neon.zendesk.com/agent/tickets/4724
[preview](https://neon-next-git-bgrenon-clarify-anonymous-role-neondatabase.vercel.app/docs/guides/neon-authorize#database-roles)
@davidgomes do you agree with this wording? It's revised to basically recommend against using the anonymous role
CC @KyleNeonTech
=> Clarify anonymous role in Neon Authorize

content/postgresql/postgresql-python/connect.md
Wrong statement. See here: https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#with-connection
=> Misinformation in docs regarding psycopg2's `with` statement

content/use-cases/database-per-tenant.md, content/use-cases/postgres-for-saas.md, src/app/(docs)/ai-chat/page.jsx, src/app/(docs)/docs/changelog/[...slug]/page.jsx, src/components/pages/doc/detail-icon-cards/detail-icon-cards.jsx, src/components/pages/doc/post/post.jsx, src/components/shared/cta-block/cta-block.jsx, src/styles/doc-content.css
This PR brings fixes for Docs mobile:
- Docs layout overflow - [Preview](https://neon-next-git-docs-mobile-fixes-neondatabase.vercel.app/docs/import/migration-assistant)
- detail-icons-cards auto height - [Preview](https://neon-next-git-docs-mobile-fixes-neondatabase.vercel.app/docs/introduction)
- use-cases CTA - [Preview](https://neon-next-git-docs-mobile-fixes-neondatabase.vercel.app/use-cases/postgres-for-saas)
[Preview](https://neon-next-git-docs-mobile-fixes-neondatabase.vercel.app/docs/introduction)
=> fix: docs mobile issues

src/components/pages/pricing/hero/hero.jsx, src/components/pages/pricing/plans/table/table.jsx
Relates to [linear.app/neondb/issue/GRW-290/experiment-build](https://linear.app/neondb/issue/GRW-290/experiment-build)
I want to disable this experiment in code and run experiment again to check posthog's results in this case, where we 100% sure that there are no any actual changes.
The previous results of experiment is very suspicious for me https://us.posthog.com/project/49356/experiments/68916
Later I will remove this exp from codebase completely.
=> chore: force disable "website_growth_compute_price_rising" exp

content/docs/guides/reset-from-parent.md
preview:
https://neon-next-git-bgrenon-fix-branch-reset-example-neondatabase.vercel.app/docs/guides/reset-from-parent#integrating-branch-resets-in-cicd-workflows
=> Fix branch reset instructions in CI/CD section

content/postgresql/postgresql-triggers/introduction-postgresql-trigger.md
Corrected a typo where instead of UPDATE, UDPATE was written on the "Introduction to PostgreSQL Trigger" page
=> Fix small typo in the tutorial pages

next.config.js
This PR reset cache control for docs tech logos that need to be revalidated frequently to ensure they are up-to-date
We already disabled cache for docs images in `public/docs/` folder in this PR: https://github.com/neondatabase/website/pull/1216
But it turned out that we have tech logos in the separate folder `public/images/technology-logos/`, so this PR is updating the cache control reset for this folder too.
[Preview](https://neon-next-git-tech-logos-cache-fix-neondatabase.vercel.app/docs)
=> fix: reset cache control for docs tech logos

src/app/(docs)/ai-chat/page.jsx, src/components/shared/header/header.jsx
This PR brings small style fixes for 1280px screens:
- header Log in button
- Docs AI chat
[Preview](https://neon-next-git-small-desktop-style-fixes-neondatabase.vercel.app//ai-chat)
=> fix: small desktop style fixes

content/postgresql/postgresql-getting-started/what-is-postgresql.md
Fix incorrect C++ notation in PostgreSQL language support list
=> docs:Fix incorrect C++ notation in PostgreSQL language support list

content/docs/ai/ai-intro.md, content/docs/guides/neon-identity.md
- Agentstack docs site is not yet rebuilt; linking to the docs page in the repo instead
- Added admonition about not changing the name of the users_sync table
=> docs: updated agentstack card and users_sync table name admonition

src/components/shared/inkeep-embedded/inkeep-embedded.jsx, src/components/shared/inkeep-trigger/inkeep-trigger.jsx, src/lib/inkeep-settings.js
This PR adds analytics for Inkeep:
- Search: `search_query_submitted`
- Chat: `chat_message_submitted`
- Use **Docs search** or **AI Chat** with `console.log`s for events:
[Preview](https://neon-next-git-inkeep-analytics-neondatabase.vercel.app/ai-chat)
=> feat: add analytics for Inkeep

content/docs/guides/branching-schema-only.md
Preview:
https://neon-next-git-docs-schema-only-allowances-neondatabase.vercel.app/docs/guides/branching-schema-only#schema-only-branch-allowances
=> docs: update schema only allowances

src/app/about-us/page.jsx, src/components/pages/about/open-source/open-source.jsx, src/utils/get-github-data.js
This PR updates numbers on About Us page:
- db created daily to `18k+`
- github stars and contributors fallback numbers
[Preview](https://neon-next-git-about-us-daily-db-increase-neondatabase.vercel.app/about-us)
=> chore: update about-us page numbers

content/docs/manage/organizations.md, content/docs/manage/orgs-api.md, content/docs/manage/orgs-project-transfer.md, content/docs/reference/cli-projects.md
Main update here:
[Transfer projects between organizations](https://neon-next-git-bgrenon-transfer-org-api-neondatabase.vercel.app/docs/manage/orgs-project-transfer#transfer-projects-between-organizations)
=> Add org-to-org transfer via API to the Organization docs

content/changelog/2025-01-24.md, content/changelog/2025-01-31.md, content/changelog/2025-02-07.md, content/changelog/2025-02-14.md
We now use title in the frontmatter instead of description. PP implemented title. We still had description in an open PR, which was carried forward to later changelogs.
=> docs: fix changelog social title

content/docs/guides/nextjs.md, content/docs/unused/integrations-deprecated
Fixes the link to create a Next App: https://nextjs.org/docs/app/getting-started/installation (https://nextjs.org/learn/basics/create-nextjs-app/setup is dead)
=> docs: fix link

next.config.js
This PR adds a redirect
[/early-access-program](https://neon.tech/early-access-program) → [/docs/introduction/roadmap#join-the-neon-early-access-program](https://neon.tech/docs/introduction/roadmap#join-the-neon-early-access-program)
[Preview](https://neon-next-git-early-access-page-redirect-neondatabase.vercel.app/early-access-program)
=> chore: add a redirect for /early-access-program page

src/components/pages/contact-sales/hero/contact-form/contact-form.jsx, src/components/shared/field/field.jsx
This PR brings fixed for Contact Sales page email:
- "Email" -> "Work Email"
- work email validation
[Preview](https://neon-next-git-contact-saled-page-update-neondatabase.vercel.app/contact-sales)
=> feat: contact sales page email update

src/app/(docs)/docs/changelog/[...slug]/page.jsx, src/app/guides/[slug]/page.jsx, src/components/shared/content/content.jsx
This PR brings fix for Guides and Changelog posts with custom props for Algolia:
- added `meta category`
- added `.post-title`, `.post-author` and` .post-content`
[Preview Guides](https://neon-next-git-blog-guides-changelog-algolia-neondatabase.vercel.app/guides)
[Preview Changelog](https://neon-next-git-blog-guides-changelog-algolia-neondatabase.vercel.app/docs/changelog)
=> fix: guides and changelog props for algolia

content/docs/guides/neon-private-networking.md
This PR brings fix for the Admonition comingSoon type, misused at https://github.com/neondatabase/website/pull/2885
[Preview](https://neon-next-git-fix-coming-soon-admonition-neondatabase.vercel.app/docs/guides/neon-private-networking)
=> chore: rename comingSoon type for the admonition block

content/postgresql/postgresql-indexes/postgresql-index-on-expression.md
fix column name
- index is defined on `last_name` col in `customer` table
=> fix: column name

content/postgresql/postgresql-plpgsql/plpgsql-block-structure.md, content/postgresql/postgresql-plpgsql/postgresql-create-function.md
The typo containing grammar mistake where it had a sentence like "They are have the same meaning" instead of "They have the same meaning" is fixed.
Here is the issue: https://github.com/neondatabase/website/issues/3027
=> typo fix: for issue #3027

next.config.js
New pages:
- https://neon.tech/yc-startups -> https://neon.tech/startups
- https://neon.tech/yc-deal-terms -> https://neon.tech/startups-deal-terms
=> feat: add redirect for /yc-startups to /startups

content/postgresql/postgresql-indexes/postgresql-full-text-search.md
Fixes the missing `regconfig` parameter in `to_tsvector()` function that results in throwing this error if not provided: `ERROR:  generation expression is not immutable`
Used `english` just like the correct usage when using GIN index.
=> fix: missing param in postgresql-full-text-search.md

content/docs/manage/orgs-project-transfer.md
Dependent on:
https://github.com/neondatabase/cloud/pull/24427
This switches the destination/source org id between path and body, where path now = source, and body = destination
=> Fix for org-to-org transfer

src/components/pages/contact-sales/hero/hero.jsx
This PR updates calendly link on contact sales page
[Preview](https://neon-next-git-contact-sales-link-neondatabase.vercel.app/contact-sales)
=> chore: update calendly link on contact sales page

content/docs/guides/auth-clerk.md
Updated the import path for currentUser from @clerk/nextjs to @clerk/nextjs/server to resolve an import error. This change ensures compatibility with the latest Clerk package structure and prevents runtime issues.
=> fix: correct import path for currentUser in Clerk

content/docs/reference/neon-cli.md
This PR brings a fix for the broken [neon-cli.md](https://github.com/neondatabase/website/pull/3190/files#diff-6e807124690a433d4c9a0838b0d072718d1a339bb6fa375a41c08d6e01a8ac2e) file formatting and build issues
Reference PR: https://github.com/neondatabase/website/pull/3180
[Preview](https://neon-next-git-fix-docs-cli-files-neondatabase.vercel.app/docs/reference/neon-cli)
=> fix: neon-cli.md file formatting and build issues

src/app/(home-page)/all-things-open-2023/page.jsx, src/app/(home-page)/cfe/page.jsx, src/app/(home-page)/devs/page.jsx, src/app/(home-page)/education/page.jsx, src/app/(home-page)/fireship/page.jsx, src/app/(home-page)/github/page.jsx, src/app/(home-page)/home/page.jsx, src/app/(home-page)/last-week-in-aws/page.jsx, src/app/(home-page)/pgt/page.jsx, src/app/(home-page)/radio/page.jsx, src/app/(home-page)/stackoverflow/page.jsx, src/app/(home-page)/youtube/page.jsx
This PR brings a takeover section for homepage copies
(/home, /cfe, /devs e.t.c.)
Original PR: https://github.com/neondatabase/website/pull/3154
[Preview](https://neon-next-git-fix-homepage-copies-takeover-neondatabase.vercel.app/devs)
=> fix: homepage copies takeover

src/components/pages/doc/menu/item/item.jsx, src/components/pages/doc/sidebar/sidebar.jsx
This PR brings fixes for Docs sidebar
- extra scroll for small menus
- align for icons and tags in case of the long menu item
Before/After
[Preview](https://neon-next-git-docs-sidebar-fix-neondatabase.vercel.app/docs/introduction)
=> fix: docs sidebar fixes

src/components/shared/topbar/topbar.jsx
This PR reduces next revalidate for fetching topbar from WP to 10 minutes
Preview
=> fix: reduce next revalidate for topbar to 10 minutes

content/docs/reference/glossary.md
I think ***75 %*** is correct, at least that's what's explained [here](https://neon.tech/docs/manage/endpoints#how-to-size-your-compute).
=> docs: Fix LFC size ratio

next.config.js, src/constants/links.js
This PR updates hipaa legal page url to Docs and adds a redirect
[/hipaa-compliance-guide](https://neon.tech/hipaa-compliance-guide) -> [/docs/security/hipaa](https://neon.tech/docs/security/hipaa)
NOTE:
there is was only one link on the website, in footer
TO-DO:
[Preview](https://neon-next-git-redirect-hipaa-page-neondatabase.vercel.app/hipaa-compliance-guide)
=> feat: udpate hipaa legal page url to docs, add redirect

content/docs/serverless/serverless-driver.md
was seeking guidance on configuring the serverless ws driver in place of the http one, and in the process i discovered a broken link to the GA blog post in the serverless driver docs (`/blog/serverless-driver-1-0` -> `/blog/serverless-driver-ga`).
thanks for a fantastic blog & service!
=> docs: Fix link to serverless driver 1.0 blog post

src/components/pages/doc/docs-link/docs-link.jsx
This PR brings a hotfix for docs links inline bug, caused by https://github.com/neondatabase/website/pull/3257
[Preview](https://neon-next-git-fix-docs-links-neondatabase.vercel.app/docs/introduction/usage-metrics#archive-storage)
=> fix: docs link inline format

src/components/pages/pricing/plans/data/plans.json
This PR adds a Slack Integration to Pricing page
[Preview](https://neon-next-git-pricing-page-slack-neondatabase.vercel.app/pricing)
=> chore: add slack integration to pricing page

content/postgresql/postgresql-getting-started/install-postgresql-linux.md
This PR fixes https://github.com/neondatabase/website/issues/3274
=>  docs: fix broken link in PostgreSQL tutorial

content/docs/ai/ai-rules-neon-auth.md, content/docs/ai/ai-rules-neon-drizzle.md, content/docs/ai/ai-rules-neon-serverless.md, content/docs/shared-content/ai-rule-usage.md
The shared file uses `{name}` and  `{file}` props for each individual rule. e.g.
`<AIRule file="neon-auth.mdc" name="Neon Auth" />`
preview:
https://neon-next-git-bgrenon-ai-rules-other-ide-neondatabase.vercel.app/docs/ai/ai-rules-neon-auth
=> Updated shared ai-rules-usage.md to include other IDE info + include props

src/utils/get-react-content-with-lazy-blocks.jsx
This PR brings a fix for blog post video subtitles by adding `crossOrigin="anonymous"` for them
[Preview](https://neon-next-git-fix-video-subtitles-neondatabase.vercel.app/blog/announcing-neons-remote-mcp-server)
=> fix: video subtitles

content/docs/ai/ai-concepts.md
Fixed URL Markdown formatting pointing to the "Jaccard distance" Wikipedia reference page, as the Markdown syntax was not being applied correctly.
=> Fix: URL Markdown formatting on AI Concepts page

.github/workflows/format-markdown.yml
This PR brings a fix for format-markdown action to run it only on main branch
=> fix: run format-markdown action only on main branch

src/components/pages/pricing/hero/data/plans.json
This PR removes AWS pay links from Pricing page
[Preview](https://neon-next-git-pricing-page-remove-aws-neondatabase.vercel.app/pricing)
=> feat: remove aws from pricing page

content/postgresql/postgresql-getting-started/connect-to-postgresql-database.md
Changes:
> A session is log-lived
To:
> A session is long-lived
=> docs: Update connect-to-postgresql-database.md to correct spelling

content/docs/extensions/postgis.md
Fixed documentation that incorrectly described `ST_Point` parameters as  **"latitude and longitude"** when the actual code examples correctly use **longitude,latitude** order. Also corrected the **GEOGRAPHY** description to clarify proper coordinate order. The code examples themselves were correct - only the explanatory text needed updating.
PostGIS follows the GIS convention of storing coordinates as _(x,y)_ where **`x` is longitude** and **`y` is latitude**, contrary to the common web mapping convention of **latitude,longitude** ordering.
=> docs: correct PostGIS coordinate description from lat/long to long/lat

src/components/pages/home/hero/hero.jsx
This PR brings a link to Contact Sales page on Homepage hero section
[Preview](https://neon-next-git-home-hero-buttons-neondatabase.vercel.app/)
=> feat: add contact sales link to homepage hero

src/components/pages/home/hero/hero.jsx
This PR updates [PostHog](https://posthog.com/) analytics tags for home hero cta buttons
[Preview](https://neon-next-git-home-hero-cta-posthog-neondatabase.vercel.app/)
=> feat: update posthog analytics tags for home hero cta

content/docs/sidebar.yaml
We have a good example of using Azure AI Agent Service with Neon, I added a reference to it.
=> docs: add Azure AI agent service to sidebar

content/docs/README.md, content/docs/get-started-with-neon/production-checklist.md, public/images/checklist.svg, src/components/pages/doc/check-item/check-item.jsx, src/components/pages/doc/check-list/check-list.jsx
This PR brings an update for the docs `CheckList`, implemented at https://github.com/neondatabase/website/pull/3300
- progressbar
- updated styles and check icon
- refactors checklist `id` to `title`
[Preview](https://neon-next-git-checklist-progress-neondatabase.vercel.app/docs/get-started-with-neon/production-checklist)
=> feat: docs checklist update

src/components/pages/contact-sales/hero/contact-form/contact-form.jsx, src/components/pages/landing/form/form-field/form-field.jsx, src/components/pages/landing/form/form.jsx, src/components/shared/changelog-form/changelog-form.jsx, src/components/shared/field/field.jsx
This PR brings a refactor for the landing form validation and errors style
Reference PR where error styles became broken: https://github.com/neondatabase/website/pull/2989
[Preview Extended Form](https://neon-next-git-refactor-landing-form-neondatabase.vercel.app/msbuild-meeting)
[Preview Small Form](https://neon-next-git-refactor-landing-form-neondatabase.vercel.app/500-startups)
[Preview Contact Sales](https://neon-next-git-refactor-landing-form-neondatabase.vercel.app/contact-sales)
=> fix: landing form validation and errors style

README.md
Since both these env vars are public, is there any reason not to include them in the `.env.example` file? Then we wouldn't need this step and the `cp .env.example .env` would suffice.
=> chore: add algolia env variable information to README

content/docs/guides/prisma.md
In reference to https://github.com/prisma/prisma/pull/26633
Pool is now handled by the `PrismaNeon` class (`PrismaNeonAdapterFactory`)
```ts
export class PrismaNeonAdapterFactory implements SqlDriverAdapterFactory {
readonly provider = 'postgres'
readonly adapterName = packageName
constructor(private readonly config: neon.PoolConfig, private options?: PrismaNeonOptions) {}
async connect(): Promise<SqlDriverAdapter> {
return new PrismaNeonAdapter(new neon.Pool(this.config), this.options)
}
}
```
This is the new adapter meaning that you no longer need to pass in the pool 🎉
_Please let me know if there is other parts of the docs that require changes from what I can tell nothing mentions having to instantiate Pool so this change should be enough 🙏_
EDIT: In reference to this thread on Discord …
=> docs: Updates Prisma docs to align with recent changes

src/components/pages/home/hero/hero.jsx, src/components/pages/pricing/hero/data/plans.json, src/components/shared/github-star-counter/github-star-counter.jsx, src/components/shared/header/header.jsx, src/components/shared/header/sidebar/sidebar.jsx
This PR brings:
- Github stars link in header
- Homepage hero text update
[Preview](https://neon-next-git-header-github-and-hero-text-neondatabase.vercel.app/)
=> feat: header github and hero text

content/docs/extensions/pg_search.md
This PR brings a hotfix for docs pgsearch mdx error
[Preview](https://neon-next-git-fix-docs-pgsearch-mdx-neondatabase.vercel.app/docs/extensions/pg_search)
=> fix: docs pgsearch mdx error

.github/workflows/format-markdown.yml
Reverts neondatabase/website#3294
Because it's needed to prevent build errors like [this](https://github.com/neondatabase/website/commit/48d70d411c5a5b0cad6deea8cde8cb0dc61541ec#diff-842e744f86778aff6f9b388f0a005657c96e6ce705d905f004fe8e369b978e0dR59) before merge
=> Revert "fix: run format-markdown action only on main branch"

src/components/shared/algolia-search/algolia-search.jsx
This PR brings an empty render for Algolia search component in case of missing algolia env variables
Reference PR: https://github.com/neondatabase/website/pull/3388
TO-DO:
[Preview Blog](https://neon-next-git-mmissing-algolia-env-fallback-neondatabase.vercel.app/blog)
[Preview Guides](https://neon-next-git-mmissing-algolia-env-fallback-neondatabase.vercel.app/guides)
=> feat: add fallback for missing algolia env variables

content/postgresql/postgresql-tutorial/postgresql-any.md
If the subquery returns an empty set, the result of an ANY comparison is always `false`, not `true`.
This behavior is based on logical reasoning:
- The ANY operator checks whether the condition is satisfied by any element in the set.
- If the set is empty, there are no elements to satisfy the condition.
- Therefore, the result of the comparison is false, since the condition cannot be true for any element.
``` sql
CREATE TABLE users (id INT, name TEXT);
INSERT INTO users (id, name) VALUES 
(1, 'Alice'),
(2, 'Bob'),
(3, 'Charlie');
```
Query: 
``` sql
SELECT 1 = ANY (SELECT id FROM users WHERE id > 100);
```
return `false`;
=> docs: Fix doc for ANY operator behavior with empty subquery

src/components/pages/contact-sales/hero/contact-form/contact-form.jsx
This PR brings a fix for unlocking contact form submit button
(after the first unsuccess submit attempt and errors being fixed)
[Preview](https://neon-next-git-fix-contact-form-submit-button-neondatabase.vercel.app/contact-sales)
=> fix: unlock contact form submit button

src/components/pages/contact-sales/hero/contact-form/contact-form.jsx, src/components/shared/field/field.jsx
This PR brings a new field `Surname` for Contact Sales form
[Preview](https://neon-next-git-contact-sales-form-split-name-neondatabase.vercel.app/contact-sales)
=> feat: split full name in contact sales form

src/app/enterprise/page.jsx, src/components/pages/enterprise/faq/item/item.jsx, src/components/shared/logos/logos.jsx
This PR brings a fix for logos slider in Safari
also fixes hydration error in FAQ item
[Live page](https://neon.tech/enterprise)
[Preview](https://neon-next-git-fix-clients-slider-safari-neondatabase.vercel.app/enterprise)
=> fix: logos collapse in safari

content/docs/README.md
This PR brings a guide for showing code diff to [README](https://github.com/neondatabase/website/blob/49db507f021f9c8b8bd55867892acc4ea827e658/content/docs/README.md#code-blocks)
=> chore: add code diff to readme

content/postgresql/postgresql-tutorial/postgresql-select-into.md
Corrected the SQL statement to remove the unnecessary 'I' from the SELECT clause.
```sql
SELECT
select_list I
INTO [ TEMPORARY | TEMP ] [ TABLE ] new_table_name
FROM
table_name
WHERE
search_condition;
```
```sql
SELECT
select_list
INTO [ TEMPORARY | TEMP ] [ TABLE ] new_table_name
FROM
table_name
WHERE
search_condition;
```
=> docs: fix typo in SQL statement by removing unnecessary 'I'

content/docs/extensions/hstore.md, content/docs/extensions/pg_trgm.md
=> docs: remove version info from ext guides

content/postgresql/postgresql-string-functions/postgresql-format.md
Fixed typo where the '`with`' component where referenced as '[`width`](https://github.com/neondatabase/website/blob/2c296564a08c859da9c4d7288d6500f907568828/content/postgresql/postgresql-string-functions/postgresql-format.md?plain=1#L48)' two times in the FORMAT() function documentation [page](https://neon.tech/postgresql/postgresql-string-functions/postgresql-format).
=> docs: fixed typo in FORMAT() function documentation

.github/workflows/linkinator.yml, README.md, next-sitemap-postgres.config.js, next-sitemap.config.js, next.config.js, src/app/(home-page)/page.jsx, src/app/guides/og/route.jsx, src/lib/inkeep-settings.js
In this pull request, the main domain of the website was changed from `neon.tech` to `neon.com` in critical areas
=> chore: update site URL references from neon.tech to neon.com

content/docs/reference/neon-launchpad.md, content/docs/workflows/claimable-database-integration.md
This came up during review of https://github.com/neondatabase/website/pull/3493 (thanks Daniel!)
=> docs: cross-reference launchpad and claimable db guides

content/guides/fastapi-async.md
Noticed the [FastAPI Async Guide](https://neon.com/guides/fastapi-async) includes a dependency (`requests`), which is not utilized or required in the guide. This PR introduces a patch to remove `requests` as one of the dependencies required.
**Note:** In this context, `requests` was probably included accidentally, given that FastAPI internals don't depend on it.
>This section outlines notable considerations for developers/maintainers.
This is an excellent blog from @sam-harri and the Neon team!
I'd love to hear your thoughts on the following topics. Kindly advise if they'd be a good addition to enhance the current guide:
- **Explicitly cached prepared statements to reduce SQL parsing**
- **Warm connections on startup to avoid _initial_ request latency**
The default behavior for …
=> Omit unused dependency in `fastapi` guide

content/docs/ai/connect-mcp-clients-to-neon.md, content/docs/ai/neon-mcp-server.md, content/guides/cursor-mcp-neon.md
Updated Links:
https://neon-next-git-fork-dhanushreddy291-add-docs-aed55b-neondatabase.vercel.app/docs/ai/connect-mcp-clients-to-neon
https://neon-next-git-fork-dhanushreddy291-add-docs-aed55b-neondatabase.vercel.app/guides/cursor-mcp-neon
https://neon-next-git-fork-dhanushreddy291-add-docs-aed55b-neondatabase.vercel.app/docs/ai/neon-mcp-server
Also needs to merge: https://github.com/neondatabase-labs/mcp-server-neon/pull/76
The markdown version wasn't rendering properly so added using `<a>` tags
Markdown Version
```
[![Install MCP Server](https://cursor.com/deeplink/mcp-install-dark.svg)](https://cursor.com/install-mcp?name=Neon&config=eyJjb21tYW5kIjoibnB4IC15IG1jcC1yZW1vdGVAbGF0ZXN0IGh0dHBzOi8vbWNwLm5lb24udGVjaC9zc2UifQ%3D%3D)
```
HTML Version
```
<a …
```
=> docs: add one click mcp server for cursor

content/docs/manage/roles.md
https://neon.com/docs/manage/overview#roles already talks about the limit, and it is enforced.
This page was outdated, so let's bring it in line with what's actually enforced.
=> docs: mention the roles limit

content/postgresql/postgresql-indexes/postgresql-full-text-search.md
The [Full text search using GIN indexes](https://neon.com/postgresql/postgresql-indexes/postgresql-full-text-search#full-text-search-using-gin-indexes) doesn't utilize the created index.
After creating the index:
```sql
CREATE INDEX body_fts
ON posts
USING GIN ((to_tsvector('english',body)));
```
`to_tsvector('english', body)` should be used instead of `body` in:
```sql
SELECT
id,
body
FROM
posts
WHERE
body @@ to_tsquery('basic | advanced');
```
=> Fix GIN index utilization in full-text search

.github/workflows/format-markdown.yml
The workflow was failing with "Updates were rejected because the remote contains work that you do not have locally" because it was pulling changes after committing formatting changes.
=> docs: move git pull before formatting to prevent push conflicts

src/components/pages/doc/breadcrumbs/breadcrumbs.jsx, src/constants/menus.js, src/icons/docs/home.inline.svg
This PR brings nav update:
- main navigation subtitles in Product section
- Docs breadcrumbs home link changed to icon
[Preview](https://neon-next-git-nav-update-neondatabase.vercel.app/)
[Preview Docs](https://neon-next-git-nav-update-neondatabase.vercel.app/docs/get-started-with-neon/why-neon)
=> chore: nav update

next.config.js
Create new `neon.com/support` quick link. Will help our team to quickly route people to get more information about support. I also assume we get some hits on `neon.com/support` from customers looking for our support features.
=> feat: support quick link

content/docs/neon-auth/quick-start/nextjs.md, public/llms/neon-auth-quick-start-nextjs.txt
**Summary:**  
This PR fixes minor grammatical issues in `neon-auth/quick-start/nextjs.md` for better clarity and correctness.
**Changes Made:**
-   Corrected sentence structure in the sign-up instruction.
-   Improved flow and readability in related lines.
**Before:**
> "Create a user or two, and you can them show up..."
**After:**
> "Createa user or two, and you can see them show up..."
closes #3684
=> fix: correct typo in user creation instructions for Next.js guide

content/docs/data-api/demo.md, content/docs/data-api/get-started.md, content/docs/guides/neon-rls-drizzle.md, content/docs/guides/neon-rls.md, content/docs/guides/row-level-security.md, content/docs/sidebar.yaml, content/postgresql/postgresql-administration/postgresql-row-level-security.md
1. Separate out [vanilla RLS info](https://neon-next-git-bgrenon-clarify-rls-neondatabase.vercel.app/docs/guides/row-level-security) (including drizzle policies) from Neon RLS
2. Clarify Data API is recommended, and not compatible with Neon RLS (noted in various places). e.g.
Top level TOC view:
More detail about Data API to come in separate PR later (explain roles and schemas etc bootstrapped when enabled).
=> Clarify Data API and Neon RLS are not compatible

content/docs/guides/branch-expiration.md
Branch expiration is now part of Early Access.
This is an alternative to https://github.com/neondatabase/website/pull/3754
=> docs: use comingSoon tag

content/docs/ai/ai-rules.md
Neon Serverless Driver is a more fitting name for what this links to.
=> Changes Neon Serverless to Neon Serverless Driver in AI Rules page

content/docs/guides/backup-restore.md
I don't fully understand why, but sometimes a mixed case API Reference link gives a 404 (instead of redirect) whereas lowercase always works. So, let's use lowercase.
Also, fixes the finalize_restore API ref link.
=> docs: lowercase API ref links

content/docs/introduction/regions.md
Add missing comma in NAT gateways docs for eu-central-1.
=> regions: add missing comma in NAT gateways doc

src/components/pages/doc/actions/actions.jsx, src/components/shared/content/content.jsx, src/components/shared/copy-prompt/copy-prompt.jsx
This PR brings tracking for Docs actions
[Preview](https://neon-next-git-docs-tracking-neondatabase.vercel.app/docs/guides/astro)
=> chore: add tracking for doc actions

content/postgresql/postgresql-json-functions/postgresql-jsonb_build_object.md
Correct misspelling of the function name in the docs. Replace “jonb_build_object” with “jsonb_build_object” in section headings and body text.
=> fix(docs): correct typos “jonb_build_object” → “jsonb_build_object”

src/app/layout.jsx, src/app/theme-provider.jsx
This PR brins ThemeColorUpdater to update next theme-color according to the theme toggler
fixes IPhone Safari notch and page background
[Preview](https://neon-next-git-theme-color-updater-neondatabase.vercel.app/docs)
=> feat: theme color updater for theme provider

content/docs/ai/ai-app-build.md
=> Update ai-app-build.md to not refer to the CLI anymore

content/changelog/2024-12-06.md, content/changelog/2025-05-16.md, content/docs/ai/ai-database-versioning.md, content/docs/extensions/pg_cron.md, content/docs/shared-content/feature-beta-props.md, content/docs/shared-content/feature-beta.md, content/docs/shared-content/lr-inbound-beta.md, content/docs/shared-content/private-preview-enquire.md, content/docs/shared-content/public-preview.md, public/llms/data-api-demo.txt, public/llms/data-api-get-started.txt, public/llms/extensions-pg_cron.txt, public/llms/guides-datadog.txt, public/llms/guides-grafana-cloud.txt, public/llms/guides-opentelemetry.txt, public/llms/import-import-data-assistant.txt, public/llms/neon-auth-api.txt, public/llms/neon-auth-best-practices.txt, public/llms/neon-auth-demo.txt, public/llms/neon-auth-email-configuration.txt, public/llms/neon-auth-how-it-works.txt, public/llms/neon-auth-overview.txt, public/llms/neon-auth-quick-start-javascript.txt, public/llms/neon-auth-quick-start-nextjs.txt, public/llms/neon-auth-quick-start-react.txt
I was reading the documentation [Getting started with Neon Data API](https://neon.com/docs/data-api/get-started) and noticed the Discord link is using `t.co` instead of the direct link that is used across the rest of the website (e.g: the header of neon.com). I guess this is unintentional as [there doesn't appear to be any benefits of using t.co outside of ~Twitter~X](https://help.x.com/en/using-x/url-shortener) and there aren't any other `t.co` uses in the documentation. In this Pull Request I have replaced the `t.co` link with the direct link to Discord.
=> fix: Remove `t.co` short URL for Discord links

cypress/e2e/startups-contact-form.cy.js, cypress/support/commands.js
**Context**
In https://github.com/neondatabase/website/pull/3992, we removed some logic that sent startup form data to HubSpot via the HubSpot endpoint. Our Cypress e2e test now seems to be failing as a result. **The e2e tests also have another issue that is being looked into separately, which is causing it to fail on GitHub (including within this PR).** [Slack thread for context](https://databricks.slack.com/archives/C092730799C/p1759171526733509).
**What changes are proposed in this pull request?**
This PR edits the Cypress e2e test to account for the data now only being sent to customer.io via Zaraz.
**How did we test this?**
Tested the e2e test locally
#[LKB-4026](https://databricks.atlassian.net/browse/LKB-4026)
=> fix: fix cypress e2e test for startup form

content/docs/security/compliance.md
Added link to Neon HIPAA Compliance Guide and removed redundant information about requesting a Business Associate Agreement (BAA) and HIPAA audit logs.
=> Update HIPAA compliance section with additional resources

next.config.js
Instagres demo no longer in use and broken - replaced by launchpad
=> fix: remove broken demo

next-sitemap.config.js
We used to disallow docs/postgres because it was the postgres docs, but now it's just a few of our docs pages and they should be indexed.
=> fix: allow docs/postgres

content/postgresql/postgresql-tutorial/postgresql-order-by.md
Fix the typo in ORDER BY for NULLS LAST clause. The original one has syntax error.
=> Fix typo in ORDER BY section of PostgreSQL tutorial

content/docs/guides/ruby-on-rails.md, public/prompts/ruby-on-rails.md
Ruby guide is having a typo in the example code.
Also added AI Prompt for it in the same PR to avoid merge conflicts.
https://neon-next-git-fork-dhanushreddy291-update-d-28b795-neondatabase.vercel.app/docs/guides/ruby-on-rails
=> docs: fix ruby guide

content/postgresql/postgresql-tutorial/postgresql-cube.md, content/postgresql/postgresql-tutorial/postgresql-grouping-sets.md, content/postgresql/postgresql-tutorial/postgresql-rollup.md, content/postgresql/postgresql-tutorial/postgresql-subquery.md
Fixed the navigation relationship between the GROUPING SETS, CUBE, ROLLUP, and Subquery documents to ensure the correct sequence: GROUPING SETS, followed by CUBE, then ROLLUP, and finally Subquery according to 'content/postgresql/sidebar.yaml'.
=> docs: fix navigation order for GROUPING SETS, CUBE, ROLLUP, and SubQuery
